### ISSUE TITLE
Improve explorability of ArgumentMatcher's and Answer's

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#1042]
In my last projects I found that `AdditionalMatchers` and `AdditionalAnswers` were never used, but some functionality was reimplemented like `find(regEx)` or `returnsFirstArgument()`. Since I observed it on different project/teams I guess they are hard to explore. Possibly users tend to think that all build-in ArgumentMatchers exists in `Mockito` so they don't look for other places. 

ArgumentMatcher' life in 3 classes: 
 * `ArgumentMatchers`
 * `AdditionalMatchers`
 * `Mockito` extends `ArgumentMatchers`

Answers are spread throu:
 * Answers
 * AdditionalAnswers

What about moving the methods of AdditionalAnswers to Answers and AdditionalMatchers to ArgumentMatchers?

**Comment by mureinik** [comment]
@TimvdLippe is it safe to assume that since the "please-contribute" tag was applied to this issue that @ChristianSchwarz 's suggestion ("moving the methods of AdditionalAnswers to Answers and AdditionalMatchers to ArgumentMatchers?") is accepted, and we'd like to do that?

I should have some time next week to  try to tackle this issue, but I want to confirm that there's a concesus on the suggestion beforehand.

**Comment by TimvdLippe** [comment]
Yes I think tgat is a good approach. Have to review the end result ofc

**Comment by mureinik** [comment]
@TimvdLippe My pr #1143 should handle the `AdditionalMatchers` issue (reviews are welcome!). 

Sadly, the same approach can't be taken with `AdditionalAnswers`, since `Answers` is an enum, and thus final. We could move all the methods to `Answers`, and leave a deprecated `AdditionalAnswers` that just delegates to `Answers`, but I wonder how ugly it would be to maintain it. E.g.:

```java
    /**
     * @since 1.9.5
     * @deprecated Use {@link Answers#returnsFirstArg()} instead
     */
    @Deprecated
    public static <T> Answer<T> returnsFirstArg() {
        return Answers.retrunsFirstArg();
    }
```

I'd appreciate your (or anyone else's, actually) thoughts on this before I start implementing it.

**Comment by szczepiq** [comment]
Interesting suggestion! My gut feel (without looking into AdditionalMatchers) is that there are good reasons to keep some scarcely used matchers away from the main api. The more methods, the harder the API is to use. Your point with low discoverability is valid. I will review the AdditionalMatchers and give my vote on this.

Thank you for looking into this!

**Comment by TimvdLippe** [comment]
While I do see why some matchers are more commonly used and thus important, I think it is better to improve discoverability. The official JDK usually also ships with javadoc for methods/classes that are rarely used, but it makes them more discoverable.

**Comment by ChristianSchwarz** [comment]
@mureinik 

> Sadly, the same approach can't be taken with AdditionalAnswers, since Answers is an enum, and thus final. We could move all the methods to Answers, and leave a deprecated AdditionalAnswers that just delegates to Answers, but I wonder how ugly it would be to maintain it.

I think delegating is the right approach here. Changing the type hierachy is not ideal, cause the deprecated class inherits methods it previously don't had. This may cause trouble later if user's reference these. 

@szczepiq 
> My gut feel (without looking into AdditionalMatchers) is that there are good reasons to keep some scarcely used matchers away from the main api. 

Can you tell us more of the "good reasons" you feel? 

> The more methods, the harder the API is to use. 
The API don't get more methods they simply move from one class to an other.

@all
In an ideal world I would like to see 3 different method container classes:
 * Mockito for stubbing and validating  doXXX /when / thenXXX, verifyXXX
 * Answers 
 * Matchers

This way the auto completion would show me only what I am lookin for, not just everything.

**Comment by mureinik** [comment]
> @mureinik
> 
> Sadly, the same approach can't be taken with AdditionalAnswers, since Answers is an enum, and thus final. We could move all the methods to Answers, and leave a deprecated AdditionalAnswers that just delegates to Answers, but I wonder how ugly it would be to maintain it.
> I think delegating is the right approach here. Changing the type hierachy is not ideal, cause the deprecated class inherits methods it previously don't had. This may cause trouble later if user's reference these.

That's a good point. I updated my PR to use this approach, but it still seems weird to me to add a bunch of static utility methods to an enum like `Answers`. Lets see what the rest of the community thinks about *this* PR before moving further down this road.

**Comment by szczepiq** [comment]
Sorry for late reply guys!

>>My gut feel (without looking into AdditionalMatchers) is that there are good reasons to keep some >>scarcely used matchers away from the main api.

>Can you tell us more of the "good reasons" you feel?

With designing of clean API there is a dilemma: discoverability vs. clarity. If all methods are on a single class, the discoverability is really good but it clutters the api. If we split the methods onto separate classes, we have the opposite effect. Years ago, when we have designed Mockito API we decided to push some edge-case'y matchers and answers to separate objects in an attempt to keep the API smaller. After several years of doing it this way, @ChristianSchwarz comes along with feedback that it would be better to merge the methods into a single class and optimize for discoverability. This feedback is interesting and certainly worth considering! (thanks!)

Here's my take on this. Warning - I am hesitant to make changes without compelling reasons and I am in favor of slow, deliberate evolution of the API :)

- feedback from a single person is not sufficient evidence that the change is worth doing. If we make the change, we can as easily get opposite feedback after sometime.
- if a team reimplemented an answer that already exists on AdditionalMatchers or AdditionalAnswers, I don't consider it a problem. Such implementation is super cheap to maintain and I'd rather Mockito have cleaner API even if some team will reimplement few lines of code.

Suggested next steps: Given that none of the core developers hasn't merged the PR, I promise to review it in a day or two. I will look at it from the standpoint of "is it worth to clutter the API with new methods that are hardly used, in order to maximize code reuse?". My recommendation will be subjective and based on the quality/nature/usefulness of the additional matchers/answers.

Hope that helps! This is a really good discussion. Thank you guys for bringing this up.

**Comment by mureinik** [comment]
Hey guys, can we try and reach a decision on this one? Both approaches have their merits, but let's pick one and either close this issue or move forward with reviewing/merging the PR.

**Comment by szczepiq** [comment]
Sorry for the delay!

I reviewed the matchers in AdditionalMatchers and I don't find them very useful. I think they will unnecessarily add ~70 methods to the main public API entry point. Currently the Mockito class has ~100 public methods. Adding so many new methods that are hardly useful will seriously clutter the API. By now, most users know where to find additional matchers and lots of documentation and books have been written on this subject. Having a separate class for additional, rarely used matchers is useful because we can put there matchers that we are unsure about. Reduced discoverability seems like a trade off.

Sorry guys for misguidance on our end. Sometimes we are dragged to other priorities and cannot effectively guide the contributions to a happy ending. We totally appreciate the API change suggestion and a nice pull request to finish this off!

@mureinik, how about attacking issue #1097 - it is more challenging and would create a nice new feature for the users :)
