### ISSUE TITLE
Can't mock error message is confusing when root cause is ClassNotFoundException

### ISSUE THREAD

**Issue by tyrel** [mockito/mockito#1050]
If you attempt to mock a class which has a dependency that isn't in the test classpath, you will get the standard message:
>Mockito can only mock non-private & non-final classes.
>If you're not sure why you're getting this error, please report to the mailing list.

You have to dig down through the stack trace to see that the root cause was a `ClassNotFoundException`. This can be very confusing for a user (it was for two people in my organization).

My suggestion is to detect if there's a `ClassNotFoundException` as a cause of the failure to create an instance of the class, and if so, report that, instead of the default message.

This will improve usability in Mockito, making users more productive, and help prevent future support requests.

**Comment by TimvdLippe** [comment]
Since there are numerous reasons that this exception can occur, I don't think it is maintainable to hardcode a subset of exceptions. Instead, I would prefer that users file issues. These issues can be more easily searched for, so that we can best provide assistance to users. That way, we can improve handling of any exception that might occur, rather than the ones we are actively aware of.
