### ISSUE TITLE
Javadoc Example Throws Unexpected Exception

### ISSUE THREAD

**Issue by Abasifreke** [mockito/mockito#1088]
Verify(mockedList, atLeast(2)).add("five times"); - would throw
org.mockito.exceptions.verification.TooLittleActualInvocations

Correcting this would help to make sure new devs are not confused by the verify use case there.

<img width="678" alt="screen shot 2017-05-17 at 8 40 03 pm" src="https://cloud.githubusercontent.com/assets/10499046/26181818/2241904c-3b41-11e7-8f71-6974d46d5579.png">

**Comment by trcooke** [comment]
What would you consider to be the correct behaviour here? At a push I might propose a slight change in naming to "TooFewActualInvocations" but the core behaviour is the same.

Your example is confusing because your "atLeast(2)" verification is on .add("five times"), which suggests five invocations of add() with that String, but there are no invocations with that String.

What do you expect to see here?

**Comment by szczepiq** [comment]
I think the expectation is that the code works when it is copy pasted to IDE and executed. Why don't we fix it by changing "five times" to "three times"? Do you want to contribute? Please do! :)

**Comment by trcooke** [comment]
Oh wait, I see now. It's a problem with [the documentation](http://static.javadoc.io/org.mockito/mockito-core/2.8.9/org/mockito/Mockito.html#4). Sure thing, I can update that no problem.

**Comment by Abasifreke** [comment]
Thanks folks.
