### ISSUE TITLE
NullPointerException when using argThat() for long parameter in verify

### ISSUE THREAD

**Issue by pettermahlen** [mockito/mockito#117]
A minimal code example:

```java
  @Test
  public void shouldNotBeBroken() throws Exception {
    TakesALong takesALong = mock(TakesALong.class);

    verify(takesALong).call(argThat(CoreMatchers.equalTo(11L)));
  }

  static interface TakesALong {
    void call(long l);
  }
```

This leads to an NPE logged as happening at the 'verify' call, which made me think that the the result of `verify(takesALong)` was null, but it seems like the NPE has a somewhat incomplete stack trace. Variations that don't show this problem include:

- changing the interface to take a ```Long``` instead of a ```long```, or
- using ```longThat(Matcher<Long>) ``` instead of ```argThat()```

If it is considered an error to use ```argThat``` where you're passing in a long, then I think at least there should be a better error message.

**Comment by bric3** [comment]
> Perhaps we can inspect the generic type of the matcher and if it is a primitive wrapper, it can return 0 or false.

That is probably feasible, but this won't be of any use in most cases, because most of us use existing _matchers_ where most are generic with an `Object` upper bound.

**Comment by szczepiq** [comment]
Yeah, it would be good. Who wants to contribute the fix?

**Comment by JeremybellEU** [comment]
Is this still an ongoing issue? I am willing to do some investigation on this one.

**Comment by JeremybellEU** [comment]
I did some investigation and the problem is at [the GenericTypeExtractor](https://github.com/mockito/mockito/blob/15688023419199b0a27b15a8d782848cdfaa9530/src/main/java/org/mockito/internal/util/reflection/GenericTypeExtractor.java#L78).
When executing the posted testcase, the Matcher that is created is [IsEqual](https://github.com/hamcrest/JavaHamcrest/blob/c47a7b873345ee46073707d35c6f0cc847c4baf1/hamcrest-core/src/main/java/org/hamcrest/core/IsEqual.java).
When executing `getActualTypeArguments()` on `BaseMatchers.class`, it returns `Type[] {TypeVariableImpl}` with name `T`, as `BaseMatchers` is the declared superclass of `IsEqual`.

This behaviour is because `IsEqual` is declared as generic with `<T>`. Therefore I sadly don't see a feasible solution and would alter the documentation to state that primitives should use the other methods such as `longThat(long)`.

**Comment by szczepiq** [comment]
Ah, I had high hopes for the type extracting :(. Looks like the argXxx methods need to be included in MockitoHamcrest. Do you want to contribute?

**Comment by JeremybellEU** [comment]
I can contribute yes (but have a lot of PRs open already, might cause some flooding). But what do you mean with `argXXX`?

Do you mean a signature like `public static long argThat(Matcher<Long> matcher)`? I am not sure if it compiles but I can try it out.

Still I don't think the underlying issue is solved, because `IsEqual<T>` with `T=Long` will not match the `Matcher<Long>`, but that would be left for experimentation.

**Comment by ChristianSchwarz** [comment]
@szczepiq @TimvdLippe 
Can this be closed? Since 2.x.x `Mockito.argThat(..)` accepts only `org.mockito.ArgumentMatcher` and not `org.hamcrest.Matcher`.

**Comment by ChristianSchwarz** [comment]
> Do you mean a signature like public static long argThat(Matcher<Long> matcher)? I am not sure if it compiles but I can try it out.

It doesn't compile, `argThat(Matcher<Long>)` has the same erasure as `argThat(Matcher<T>)`. I guess this issue can't be fixed. 
The workaround is to use `MockitoHamcrest.longThat(Matcher<Long>)` or better `Mockito.eq(long)`.

IMO this issue can be closed.

**Comment by bric3** [comment]
I agree, maybe with future JDK version we could do something, not right now. Thanks @ChristianSchwarz for this archelogical dive in mockito issues ;)

**Comment by bric3** [comment]
Also remove `bug` label, because it's really a bug in mockito.

**Comment by ChristianSchwarz** [comment]
@bric3 Please reopen.

> It doesn't compile, argThat(Matcher<Long>) has the same erasure as argThat(Matcher<T>). I guess this issue can't be fixed. 

After looking #246 is noticed that this issue can be fixed! Two methods don't have the same erasure if the return type is different. The java 8 compiler generates a warning in this case, don't know about other versions. We need to provide overloads for all primitives like this:

```
public static long argThat(Matcher<Long> matcher) {
        reportMatcher(matcher);
        return 0;
}
```

For the provided test case the expected `MockitoException` _"Wanted but not invoked ..."_ is thrown.

**Comment by bric3** [comment]
@ChristianSchwarz nope that doesn't work, while java byte code allows to have method based on the complete signature (ie name, arg types and return type), the compiler just look at the name and arg types.

The following code don't compile : 

```
long argThat(Matcher<Long> matcher) {}
int argThat(Matcher<Integer> matcher) {}
```

**Comment by ChristianSchwarz** [comment]
@bric3 
Crazy the JDT compile has no problem with this, it even works at runtime. After some investigation I found this answer on [stackoverflow ](http://stackoverflow.com/a/5562274/932656). It should work with javac too, as the JLS seems to allow it due to a hole in the specs (if i understand that correct).

Also interesting: [With generics, the return type is part of the method signature.](http://vanillajava.blogspot.de/2011/02/with-generics-return-type-is-part-of.html.

But I agree, keep it closed for now.

**Comment by bric3** [comment]
This hack does not work with Java 8.

**Comment by ChristianSchwarz** [comment]
Jup!

It's a bug in eclipse JDT that only occures with a non standard JRE execution environment and compiler compliance setup. I filed an issue for the JDT-Team: [Bug 499817](https://bugs.eclipse.org/bugs/show_bug.cgi?id=499817)

**Comment by bric3** [comment]
Again, something against Eclipse. It's not the first bad bug using Eclipse compiler.

-- Brice




On Wed, Aug 17, 2016 at 12:39 PM +0200, "Christian Schwarz" <notifications@github.com> wrote:












Jup!



It's a bug in eclipse JDT that only occures with a non standard JRE execution environment and compiler compliance setup. I filed an issue for the JDT-Team: Bug 499817
