### ISSUE TITLE
any not matching null reasoning

### ISSUE THREAD

**Issue by eccforgit** [mockito/mockito#1188]
Can someone please explain the reasoning behind this and why it is a long awaited feature.  This is so counter intuitive and painful to writing unit tests that I just can't understand how that many users really wanted this as a feature. Can you also explain how to work around this great change? (BTW any by definition means all possible, not all possible but this one.  If the developers wanted that they should have created a anyNonNull() set and left the any set alone).

"anyX() and any(SomeType.class) matchers now reject nulls and check type. This has been long waited feature, making Mockito syntax more intuitive. (In the following list T represents some type like Integer, List)

<T> T any() will matches anything including null
T anyT() / <T> any(Class<T>) are aliases of <T> isA(T), will matches non-null object of given type. e.g. :
int anyInt() won't match null (for Integers) anymore
String anyString() won't match null (for Strings) anymore, and will check the object is indeed a String
Map<K, V> anyMap() won't match null (for Maps) anymore, and will check the object is indeed a Map
<T> List<T> anyListOf(Class<T>) will match non-null List, and will check the object is indeed a List"_

thank you
E

**Comment by TimvdLippe** [comment]
To what extent does `any()` qualify for your usecase? That can match values including `null`. The primary reason for non-null is the confusion about "I expected this to be passed an object of type X, but I got null instead". By enforcing explicitness with `null`, we improve Mockito mocks relative to the production code. This change caught several bugs where mocks were invoked and incorrect types were passed, as well as `null` instead of a concrete value.

If you still want to match on null and type-check, use [`or(..., ...)`](http://static.javadoc.io/org.mockito/mockito-core/2.10.0/org/mockito/AdditionalMatchers.html#or-T-T-). E.g. `or(any(String.class), null)`. This notation is explicit and exactly conveys the reader of the code what is being matched on.

**Comment by TimvdLippe** [comment]
Closing per above comment. If our reasoning is still unclear, please reopen.

**Comment by DoriamVell** [comment]
It's unclear, because if we have only any() method to operate with possible null argument, we have even worse problem.
Before your changes, we must dealt with someArgument.class and possible null. Now me must dealt with only someArgument.class, OR someArgument.class and possible null and possible ALL OTHER CLASSES. Which... well - disturbing and painfully.

**Comment by TimvdLippe** [comment]
@DoriamVell I am not sure if I follow. In 1.x, `any` matched the expected class AND null. In 2.x, it only matches the expected class. If you would like to do what 1.x did, use `or()`, as described above.

**Comment by dnsmkl** [comment]
Scenario when `any(Class)` is inconsistent with `any()`.
1. `any()` is used for all mocks.
2. There is single function with one parameter, but many overloads, so can't be used because of type ambiguity.
3. `any(Class)` seems natural attempt to disambiguate the type.

This does not work.
Type specific equivalent of `any()` is `nullable(Class)`

**Comment by TimvdLippe** [comment]
@dnsmkl You can disambiguate with `ArgumentMatchers.<String>any()`.

**Comment by blajoie55** [comment]
if the hard line is going to be sentiment such as "anyString will no longer match null values", it would be nice to have an alternative API then. e.g. anyNullableString in addition to anyString. I know we can use nullable(String.class), but I personally prefer the "any" terminology, and it's boilerplate/annoying to have to use the or syntax to null check. In short, it was nice, concise, and convenient when Mockito just matched null values for things like anyString

**Comment by bohub12** [comment]
`any()` is designed to take a non-null object. If you want to match on null and type-check, you should try `nullable()`
- [`nullable(Class<T> class)`](https://www.javadoc.io/static/org.mockito/mockito-core/5.3.1/org/mockito/ArgumentMatchers.html#nullable(java.lang.Class))
