### ISSUE TITLE
Mockito should not copy annotations in all cases

### ISSUE THREAD

**Issue by ctolkmit** [mockito/mockito#1206]
When mocking an interface, Mockito 2.10.0 copies the annotations on the interface to the generated class.
I believe, Mockito  2.10.0  should just implement the class, as if the one would do new Interface(){...}
In fact, migrating to mockito 2.10 broke the tests of my working production code.
However, when mocking a class, the current behavior could be the expected behavior.

I have provided a very simple test case here: https://github.com/ctolkmit/mockito-tests, the Test-Case "interfaceMock()" fails. 

At least, it should be optional (via MockSettings?) to control this behavior.

**Comment by ChristianSchwarz** [comment]
> I believe, Mockito 2.10.0 should just implement the class, as if the one would do new Interface(){...}

I agree. Java does it that way. When an interface is implemented by a class the annotations are not present, no matter if the annotation is marked with `@Inherit` or not.

>However, when mocking a class, the current behavior could be the expected behavior.

The class object of a mocked class should look close as possible as one of the mocked type. Therefore I would assume that annotations are copied. 

Currently Mocktio uses as default the `SubclassByteBuddyMockMaker` which well subclasses the type to mock. You can try to us the Inline-Mock-Maker (by adding the dependency `org.mockito:mockito-inline:2.10.0` ), I don't know how it acually works but it may behave differently since it don't subclass the type to mock as far as i know.

**Comment by ctolkmit** [comment]
adding `org.mockito:mockito-inline:2.10.0` to my project did not change any test results

**Comment by ChristianSchwarz** [comment]
Okay, thanks for checking it out. 

Possibly @raphw has a good explanation for the current behaviour.

**Comment by raphw** [comment]
We introduced this as a feature since the mock class should be a representation of the mocked type. Many times, this is rather an advantage than a disadvantage. You are however right that it should be something that can be controlled in the mock options. We will look into it.

Already today, you can trick Mockito into not copying the annotations by creating a mock of type object and adding the interface as "additional interface".

**Comment by ctolkmit** [comment]
@raphw - great trick, I think this will work in my environment for the moment.

**Comment by ChristianSchwarz** [comment]
@raphw 

> We introduced this as a feature since the mock class should be a representation of the mocked type. 

Out of interest: Shouldn't annotations never by copied from interfaces? I mean if an interface is implemented, the compiler don't copy any annotation to the class. So it is a bit surprising that mockito does it.  I would expect this only for mocked classes.  

> Already today, you can trick Mockito into not copying the annotations by creating a mock of type object and adding the interface as "additional interface".

This should IMHO the default behaviour when an interface is mocked. Maybe mockito should take this into account. Actually I don't see a case where this would be an disadvantage.

**Comment by ctolkmit** [comment]
@ChristianSchwarz I would completely agree :)

**Comment by TimvdLippe** [comment]
This has been addressed in #1216
