### ISSUE TITLE
MockitoJUnitRunner too strict by default?

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1212]
In one of the projects being migrated to Mockito 2 I've observed that deprecated `org.mockito.runners.MockitoJUnitRunner` (tested with 2.11.0) works in a strict mode by default (fails a test on unnecessary stubbing). I wonder if it is an expected behavior?

Even Mockito rule works in a "warn" mode by default. It makes it a little bit harder to migrate from Mockito 1.10.x to 2.x.

**Comment by szpak** [comment]
What's more even using the old `@RunWith(org.mockito.runners.MockitoJUnitRunner.Silent.class)` still causes `UnnecessaryStubbingException`. The new one (`@RunWith(org.mockito.junit.MockitoJUnitRunner.Silent.class)`) has to be used to keep test passing.

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito/blob/e10c5409e460c3ecd6b2ef9513a0b3802351d85f/src/main/java/org/mockito/runners/MockitoJUnitRunner.java#L29-L31

It seems we have to change the call to this instead: https://github.com/mockito/mockito/blob/e10c5409e460c3ecd6b2ef9513a0b3802351d85f/src/main/java/org/mockito/junit/MockitoJUnitRunner.java#L107

I submitted #1226 to discuss this change in behavior. I think it is an oversight when we deprecated the runner in the old package.

**Comment by mockitoguy** [comment]
It's a bug. Thank you for reporting!

The previous runner: ```org.mockito.runners.MockitoJUnitRunner``` should behave exactly the same as the new runner: ```org.mockito.junit.MockitoJUnitRunner```

**Comment by mockitoguy** [comment]
I started reviewing @TimvdLippe PR and I came to conclusion that it the current behavior works as designed.

 - the change of strictness of the runner was an intentional incompatible change in 2.0 release
 - the deprecation of the runner was a compatible change done after 2.0. Deprecated runner does not intend to help migration.
 - the current behavior of the code (unless I'm mistaken) is that deprecated runner behaves as the new runner which is what we want.

I hope above clarifies the situation :) Please reopen if needed!
