### ISSUE TITLE
UnfinishedStubbingException when thenReturn contains mock which is used in when

### ISSUE THREAD

**Issue by mplewka** [mockito/mockito#166]
Hi, I've found something strange and would like to ask you to explain, what is the reason UnfinishedStubbingException is thrown here? My understanding is that using mock in thenReturn is forbidden when it is a part of when as well, but frankly... I don't get why :-)

    @Test
    public void shouldMockMethodButDoesNot() {
        TestInterface mock = Mockito.mock(TestInterface.class);
        when(mock.getObject()).thenReturn(Mockito.mock(Object.class));
        when(mock.returnSomething()).thenReturn(new TestInterfaceUser(mock));
    }

    static interface TestInterface {
        public TestInterfaceUser returnSomething();
        public Object getObject();
    }
    
    static class TestInterfaceUser {

        Object obj;
        
        public TestInterfaceUser( TestInterface t) {
            this.obj = t.getObject();
        }
    }

**Comment by alberskib** [comment]
If you slightly change your code to the next form:
```java
@Test
public void shouldMockMethodButDoesNot() {
    TestInterface mock = Mockito.mock(TestInterface.class);
    when(mock.getObject()).thenReturn(Mockito.mock(Object.class));
    TestInterfaceUser t = new TestInterfaceUser(mock);
    when(mock.returnSomething()).thenReturn(t);
}
```
it is working correctly.
Alternatively if you do next thing:
```java
@Test
public void shouldMockMethodButDoesNot() {
    TestInterface mock = Mockito.mock(TestInterface.class);
    when(mock.getObject()).thenReturn(Mockito.mock(Object.class));
    when(mock.returnSomething()).thenReturn(new TestInterfaceUser(mock));
}

static interface TestInterface {
    public TestInterfaceUser returnSomething();
    public Object getObject();
}

static class TestInterfaceUser {

    TestInterface obj;

    public TestInterfaceUser( TestInterface t) {
        this.obj = t;
    }
}
```
it also behave in expected way.

Your problem is connected to the fact that in one place you are trying to register mock behaviour for selected method `when(mock.returnSomething()) ` - as a result mock is in state for registering answer , and then you are interacting with the same mock by invoking method `getObj()`. As a result mock is moved from waiting for answer state to some other one without receiving answer.

I am not sure whether I explain it to you in enough clear way but I think that you should more or less catch it. I think that provided workaround should be sufficient for you.

As far as I know there is no easy way to handle exactly the same cases described by you (but maybe I am wrong).

**Comment by mplewka** [comment]
Thanks alberskib for your reply. I know how to build such a workaround :), what is more, I was almost sure that "incorrect state" is the reason why exception is thrown. Nothing new for me, but the question is if it is a desired behavior or just a bug? In my opinion it is at least weird...

**Comment by alberskib** [comment]
> the question is if it is a desired behavior or just a bug?

It is really good question but unfortunately I am not able to answer to it.
I think that @szczepiq or @bric3 will be able to answer it.

**Comment by bric3** [comment]
Hi @mplewka,

Yeah mock stubbing wasn't really designed to be _intertwined_. Things are already complicated but when mocks call another while being stubbed it becomes very difficult to actually detect the correct arguments for the correct call in intertwined mocks. I don't remember the details but if we relax this part it may blow in the wrong way for some other cases.

So in way for your case, it is expected, i.e. a mock is being used while the other mock is not yet stubbed.

Also if you want I can give more precise detail on what's really going on in the snippet you provided.
