### ISSUE TITLE
2.26.0 release crashed

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#1682]
It stopped processing the release at the task `bintrayPublish`: https://travis-ci.org/mockito/mockito/jobs/515739785#L1890 However, it successfully uploaded to Bintray: https://bintray.com/mockito/maven/mockito/2.26.0

**Comment by TimvdLippe** [comment]
It is unclear if this artifact is being pushed to Maven Central: http://central.maven.org/maven2/org/mockito/mockito-core/2.26.0/ It might require a manual central sync by @mockitoguy

**Comment by mockitoguy** [comment]
Let's move on. This was the last step of the release so even if it crashed, we are in a good state because Bintray and Maven Central have the version. I don't think this is something we can solve. My theory is that bintrayUpload task got stuck when Bintray server was syncing to Maven. I've seen something like that happening from Bintray UI in the past.

**Comment by mockitoguy** [comment]
Thank your for documenting though! If this becomes a problem again, we may revisit!

**Comment by TimvdLippe** [comment]
Right, yes the Maven Central sync actually succeeded. I was worried it didn't.
