### ISSUE TITLE
Use reflectasm instead of java.lang.reflect

### ISSUE THREAD

**Issue by SchulteMarkus** [mockito/mockito#1684]
Hi there,

Mockito is heavily using Java-reflection. As all of us know, reflection is expensive[1].

There is an alternative reflection library https://github.com/EsotericSoftware/reflectasm, maybe you want to give it a try.

[1] Some Java reflection example benchmarks at:
- https://blog.frankel.ch/performance-cost-of-reflection/
- https://github.com/EsotericSoftware/reflectasm
- https://www.optaplanner.org/blog/2018/01/09/JavaReflectionButMuchFaster.html

**Comment by TimvdLippe** [comment]
While reflection is expensive, I wonder if it is the most expensive part of Mockito. We generate class bytecode on the fly with ByteBuddy, which I think would trump any performance issues because of our usage of reflection.

If we were to consider using the library, do you mind performing a little research showing the before and after, if we were to use reflectasm?

**Comment by raphw** [comment]
Reflection generates byte code internally after 15 calls. The overhead comes from boxing mostly which we cannot avoid as we have to extract the arguments in a generic manner.

**Comment by SchulteMarkus** [comment]
Thanks for the feedback. I did not know, that Mockito is using ByteBuddy, which should/will of course improve the reflection-performance. 

Indeed a difficult topic. Is changing from java.lang.reflect to another lib useful? Does it improve the performance (enough)? Would it be future-safe? Can it be measured? Of course, performance while testing is not that important compared to performance of the production-code.

So, how to measure it? I have had a look at https://blog.overops.com/the-top-100-java-libraries-in-2018-based-on-277975-source-files/ , hopefully a good point for having information about big Java libraries.

- Spring-framwork is using Mockito a lot https://github.com/spring-projects/spring-framework/search?q=mockito.Mock&unscoped_q=mockito.Mock
- hibernate-orm uses Mockito, too https://github.com/hibernate/hibernate-orm/search?q=mockito.mock&unscoped_q=mockito.mock
- junit5 a little https://github.com/junit-team/junit5/search?q=mockito.mock&unscoped_q=mockito.mock
- aws-sdk-java-v2 a little, too https://github.com/aws/aws-sdk-java-v2/search?q=mockito.mock&unscoped_q=mockito.mock

Do you know the "biggest" or any other users of Mockito?

I suggest for measuring the performance-impact, it would be best, to use some of these frameworks/libraries.

**Comment by raphw** [comment]
Measuring microperformance is difficult in our context but you can already get rid of the overhead of reflection by using method handles and invokeExact today. However, this requires to know the exact type signature of a method what we do not know since we intercept generic methods.

I do not think there is much to gain here, to be honest, but if you would like to experiment and can provide a valid benchmark, all contributions are welcome.

**Comment by SchulteMarkus** [comment]
Thanks for your feedback here, in my opinion a constructive discussion. I am closing this issue because "not relevant".
