### ISSUE TITLE
@InjectMocks and @Spy on same field should cause MockitoException

### ISSUE THREAD

**Issue by makasprzak** [mockito/mockito#169]
Some time ago there was [@InjectMocks and @Spy cannot be used together when object initialized by mockito](https://code.google.com/p/mockito/issues/detail?id=489) issue rejected.
Checking the codebase I found a test case `WrongSetOfAnnotationsTest.shouldNotAllowSpyAndInjectMock()` which, I guess, was supposed to cover Brice's explanation. The test passes because the MockitoException **is** thrown, but it's thrown for different reason: the test tries to instantiate an interface (List). The test was there at list since 2010, so I think the behavior could have been basically forgotten.
So, although I find Brice's explanation convincing, I still think the exception should be thrown in that case, informing of wrong Mockito usage.

**Comment by makasprzak** [comment]
Now seeing the other thest: MockInjectionUsingSetterOrPropertyTest, I got a bit confused as it suggests this combination is ok (only the injection of such created spy will not happen), which seems to be in conflict with WrongSetOfAnnotationsTest.shouldNotAllowSpyAndInjectMock(). Is it an obsolete test then?

**Comment by bric3** [comment]
Hi thanks for spotting this.

So yes this is the combination of `@InjectMocks` and `@Spy` an undocumented feature, understand not promoted feature. The test is indeed wrong as the cause because `List` is an interface.

The combination of `Spy` and `InjectMocks` is not to be removed in the foreseeable future, however the issue at hand in [489](https://code.google.com/p/mockito/issues/detail?id=489) is about managing multiple `@InjectMocks` in the same unit test, which is the beginning of a DI framework as I explained it the issue page or in the [mailing list](https://groups.google.com/d/msg/mockito/dyHxTCli0YI/27tADs7wyr0J) on the same topic.

**Comment by bric3** [comment]
I have fixed the wrong unit test. Again thanks **a lot** for taking a look on the matter :)
