### ISSUE TITLE
DoubleStream.reduce() does always return 0.0 when mocked

### ISSUE THREAD

**Issue by ferstl** [mockito/mockito#1757]
When mocking `java.util.DoubleStream`, the method `reduce(int, DoublebinaryOperator)` does always return `0.0`, no matter how it was configured (The complete JUnit5 test class is [attached](https://github.com/mockito/mockito/files/3492174/MockitoTests.txt) to this issue).

```
@Test
void doesNotWork() {
  DoubleStream stream = mock(DoubleStream.class);
  when(stream.reduce(anyInt(), any())).thenReturn(42.0);

  // fails, because 0.0 is returned
  assertEquals(42.0, stream.reduce(0, (a, b) -> b), 0.001);
}
```

The same is working fine for `IntStream` and `LongStream` which have similar methods. When I adjust the configuration of the mock for explicit values, the test is also working:
```
@Test
void works() {
  DoubleBinaryOperator operator = (a, b) -> b;
  DoubleStream stream = mock(DoubleStream.class);
  when(stream.reduce(0, operator)).thenReturn(42.0);

  assertEquals(42.0, stream.reduce(0, operator), 0.001);
}
```

My Environment:
- JDK: 11.0.3
- Mockito versions:
  - 3.0.0, 2.28.2 (I tested also with some other 2.x versions, same effect)
  - It was working with version 1.9.5 when using `anyObject()`
- OS: Windows 10

check that

 - [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Please do not mock types you don't own (https://github.com/mockito/mockito/wiki/How-to-write-good-tests#dont-mock-a-type-you-dont-own) nor value objects (https://github.com/mockito/mockito/wiki/How-to-write-good-tests#dont-mock-value-objects). Is there a reason you can't use a normal `Stream`?

**Comment by ferstl** [comment]
@TimvdLippe Yes, I am writing my own [stream implementation](https://github.com/ferstl/parallel-stream-support) (which delegates to the JDK streams) and for that I need to mock the underlying streams.

**Comment by TimvdLippe** [comment]
I don't think that warrants mocking of the streams. You need to use the real versions to make sure your implementation works.

**Comment by ferstl** [comment]
Well, maybe (I'll write a bit more about that at the end). I just wanted to report an issue that I probably found when mocking the `DoubleStream` interface. This looks strange to me because this interface does not have anything special in it, except for some default methods and a generic base interface. As I mentioned, there are no problems at all with `LongStream` and `IntStream` interfaces, which are very similar. I did also try to write my own interface with similar methods but could not reproduce the problem there.

------- unrelated -------
About my Mocking of the stream interfaces: As I said, I am writing my own stream implementation that mostly delegates to the JDK stream implementation. Mocking the underlying streams is in this case very convenient to verify that the delegation is done correctly, especially when default methods are involved. The stream API is also very well encapsulated and I can only get a result, when calling a terminal method. That makes testing non-terminal methods hard. So I think I had good reasons to write my tests that way for this particular scenario.

**Comment by TimvdLippe** [comment]
Please provide a minimal reproduction case with a custom class definition that, when mocked, returns the wrong Double when stubbing. E.g. define a type yourself rather than using one from the JDK and see if you can reproduce it. If you can, it definitely is an issue in Mockito. If it is not, you are relying on an internal implementation detail of `DoubleStream` in the JDK and you should therefore use the real value rather than mock it.

**Comment by ferstl** [comment]
I [attached a JUnit5 test](https://github.com/mockito/mockito/files/3493092/Issue1757Test.txt), that reproduces the problem. I had to rename the class from `.java` to `.txt` in order to attach it here.

The class contains an inner interface that the test tries to mock.

**Comment by TimvdLippe** [comment]
Sorry for being unclear. The test would need to not reference any JDK type. E.g. without `java.util.function.DoubleBinaryOperator`. Can you extract the problematic part from `DoubleBinaryOperator` and define that as an inner class of `Issue1757Test` that shows the problem in isolation?

**Comment by ferstl** [comment]
[Here](https://github.com/mockito/mockito/files/3493154/Issue1757Test.txt) is another version that does not use any JDK type. The error message for the failing tests is always:

```
org.opentest4j.AssertionFailedError: 
Expected :42.0
Actual   :0.0
```

**Comment by TimvdLippe** [comment]
Oh, I see. Does this work?

```java
@Test
  void notWorking_2() {
    Operator operator = (a, b) -> b;
    SomeInterface mock = mock(SomeInterface.class);
    when(mock.someMethod(eq(0.0), eq(operator))).thenReturn(42.0);

    assertEquals(42.0, mock.someMethod(0, operator), 0.001);
  }
```

(I changed the `eq(0)` to `eq(0.0)`)

My current assumption is somewhere along the lines we are changing the `int` to a `double` in some cast, but I am not sure where yet.

**Comment by ferstl** [comment]
Yes, changing `eq(0)` to `eq(0.0)` works!

**Comment by TimvdLippe** [comment]
[`eq(double)`](https://github.com/mockito/mockito/blob/7041ad81250c6512d525a84add039cd2dd3441b4/src/main/java/org/mockito/ArgumentMatchers.java#L833-L835) and [`eq(int)`](https://github.com/mockito/mockito/blob/7041ad81250c6512d525a84add039cd2dd3441b4/src/main/java/org/mockito/ArgumentMatchers.java#L863-L866) both call `new Equals(value)` without any casting, so that is not the problem.

The problematic line is probably https://github.com/mockito/mockito/blob/7041ad81250c6512d525a84add039cd2dd3441b4/src/main/java/org/mockito/internal/matchers/Equals.java#L39

Here, `int.class != double.class`. When you invoke `someMethod(0, operator)` in a when-stub, we internally automatically convert it to an equals: https://github.com/mockito/mockito/blob/885e69420baa2a382f4394b85dc84cb6fe17fff6/src/main/java/org/mockito/internal/invocation/ArgumentsProcessor.java#L60

My hunch is that on that line, `arg` is of type `int` rather than `double`. I am not sure how we can work around this, as this is Java primitive-boxing rather than Mockito. It's just that Mockito uses a special syntax that allows you to run into this issue :cry:

**Comment by ferstl** [comment]
I just ran the test in the debugger. `arg` is of type `double` in https://github.com/mockito/mockito/blob/885e69420baa2a382f4394b85dc84cb6fe17fff6/src/main/java/org/mockito/internal/invocation/ArgumentsProcessor.java#L60

**Comment by ferstl** [comment]
Now, I understand. And I do also see what was wrong in my code for the first comment. Thank you for pointing that out!
