### ISSUE TITLE
Convenience factory for stubs

### ISSUE THREAD

**Issue by gilday** [mockito/mockito#1778]
A `stub(Class)` factory method on the `Mockito` class would be a convenient way to create stub-only objects:

```
List stub = stub(List.class);
```

Such a factory method improves the clarity of test code by succinctly communicating the test author's intent for the test-double.

**Comment by TimvdLippe** [comment]
> Such a factory method improves the clarity of test code by succinctly communicating the test author's intent for the test-double.

At a first glance, it was unclear what this would do. I then had to read the JavaDoc to understand what you actually meant. I am not sure if it is worth it shipping this extra method, since the options is succinct. We already have mock/spy as API entry-points and I don't think it is desirable to add convenience methods for various configurations to the existing API.

I also see that in the implementation, it is not possible to supply other options. This would limit the usage of this API. If we would need to add that, we would need to specify how to reconcile 2 different configurations, which could be unintuitive as well.

All in all I am sceptical an extra method is clear and extendable enough for the sole purpose of removing a little bit of boilerplate (where the boilerplate is very explicit and makes reading code easier).

**Comment by gilday** [comment]
That makes sense, I see where you're coming from. Do you feel the same way about the `spy` methods? I modeled the proposed `stub` method off of the existing `spy(Class)` method

```
    public static <T> T spy(Class<T> classToSpy) {
        return MOCKITO_CORE.mock(classToSpy, withSettings()
                .useConstructor()
                .defaultAnswer(CALLS_REAL_METHODS));
    }
```

Like the proposed `stub` method, the `spy` method is a convenience method which delegates to `mock` using preconfigured `MockSettings` that cannot be further customized.

**Comment by TimvdLippe** [comment]
I don't feel the same for `spy`. While the implementation definitely seems familiar, I consider `spies` and `mocks` significantly different from a user perspective. E.g. there are vastly different expectations from `spies` than from `mocks`. Since stubs are basically mocks but you can't verify them, I don't consider them a "separate concept".

Now we have implemented spies and mocks in a very similar way, but that is only for our convenience right now. I could envision a completely different implementation for the way `spies` and `mocks` work in the future, when there are some advancements in code generation.

All in all, I don't think `stubs` are significantly different from `mocks` to warrant a convenience method. If you want to have a mock which you can not verify (e.g. you want a stub), using the settings seems appropriate to me.

Does that all make sense for you?

**Comment by mockitoguy** [comment]
Hey @gilday!

I'm with @TimvdLippe on this one, we'd don't want a new ```stub()``` method in the API. In addition to @TimvdLippe's arguments:
 - stubOnly() is a performance optimization, that is intended to be used rarely, when one creates lots of mocks and the memory footprint is too large. We avoid adding more public API for rarely needed use cases.
 - having a stub() method may reduce code consistency. Some devs would use it to mark stubs, some wouldn't.
 - it is very easy to add such method in your own code if you need it (no need for new public API on Mockito's end)

Thank you for the suggestion and the pull request! (and thank you for understanding ;-)

**Comment by fioan89** [comment]
Please reconsider this issue. As [this](https://martinfowler.com/articles/mocksArentStubs.html) blog post from Martin Fowler points out, it's very important to make a clear distinction between mocks and stubs. Even though at a first glance the difference between them is not that significant - `stubs are mocks but you  can't verify them` - from a testing theory point of view the difference is significantly huge. One enables behavioural testing (i.e mocks) and the other enables state testing. Two different styles of testing with deep implications.

Having a clean  `stub(...)` API will actually encourage people to think more careful about what kind of testing they want to do and what should be actually used. 

I've seen numerous people, including myself, using the `mock(...)` API as a stub - no verify assertions done. Believe it or not, most people ignore the `MockSettings` parameter, or they don't look deep enough to what that interface provides.

I would like to argue that since mockito cared to provide a convenience factory for spies (Martin Fowler's blog post considers them as `stubs that also record some information based on how they were called`) the stub method should also be provided for better readability, encourage correctness code, ease of use and finding.

**Comment by fioan89** [comment]
As a follow up, can the issue be re-opened and have the discussion flow continue?
