### ISSUE TITLE
Argument mismatch not reported in strict stubs mode if mocked method was already called once before

### ISSUE THREAD

**Issue by pip25** [mockito/mockito#1784]
This issue occurs if the tested service is calling a mocked method more than once, but with different parameters, and only some of those invocations have actually been declared in the test.

For example, we have the following test:
```java
@RunWith(MockitoJUnitRunner.StrictStubs.class)
public class MockitoStrictnessTest {

	@Mock
	private SomeInterface someInterface;

	@InjectMocks
	private TestedClass testedInstance;

	@Test
	public void testStrictness() {

		// Mock for "anotherParam" is missing
		Mockito.doReturn("value").when(someInterface).doSomething("param");

		testedInstance.doStuff();

	}
}
```

The TestedClass and the interface definition:

```java
public class TestedClass {

	public static interface SomeInterface {
		String doSomething(String param);
	}

	private SomeInterface interfaceImplementation;

	public void doStuff() {
		// If the mocked call is before the missing one, the test will succeed
		interfaceImplementation.doSomething("param");
		interfaceImplementation.doSomething("anotherParam");
	}

	public void setInterfaceImplementation(SomeInterface interfaceImplementation) {
		this.interfaceImplementation = interfaceImplementation;
	}
}
```

The test will succeed, even though there was an argument mismatch for the declared "doSomething" method invocation. If we switch the two "doSomething" calls in the tested service, the test will fail as it should.

The cause of this seems to be in DefaultStubbingLookupListener:

```java
private static List<Invocation> potentialArgMismatches(Invocation invocation, Collection<Stubbing> stubbings) {
        List<Invocation> matchingStubbings = new LinkedList<Invocation>();
        for (Stubbing s : stubbings) {
            if (UnusedStubbingReporting.shouldBeReported(s)
                && s.getInvocation().getMethod().getName().equals(invocation.getMethod().getName())
                //If stubbing and invocation are in the same source file we assume they are in the test code,
                // and we don't flag it as mismatch:
                && !s.getInvocation().getLocation().getSourceFile().equals(invocation.getLocation().getSourceFile())) {
                    matchingStubbings.add(s.getInvocation());
            }
        }
        return matchingStubbings;
    }
```

"UnusedStubbingReporting.shouldBeReported" will only return true if the stub was not called before - but that seems to be a bug, since we should **not** be reporting unused stubbing here, but an argument mismatch.

**Comment by mockitoguy** [comment]
> we should not be reporting unused stubbing here, but an argument mismatch

There is no argument mismatch here because we matched the stubbing at least once. Mockito assumes that the stubbing is "useful" (hence no "unused stubbing" exception) and it gets a correct argument at least once (hence no "argument mismatch" exception).

I can see why you found this behavior confusing :-) We don't want Mockito to become "too strict". We want Mockito to be "strict enough" for best dev experience and highest quality of tests. If we report argument mismatch in your scenario, this would force developers to declare additional stubbings in the tests. This is not good for dev UX and for clarity of tests. Thoughts?

**Comment by pip25** [comment]
@mockitoguy 
Thanks for looking into this, but I'm not sure I completely understand. Isn't the point of the strict mode to ensure that no mock behavior is declared that is not actually needed for the test, and also that whatever behavior needs to be declared gets declared?

One of the problems here (to me) is that Mockito seems to think that just because there is a mock for a certain parameter combination, then all parameter combinations are okay, even though, considering the way Mockito works, those combinations have so little to do with each other, they might as well be for separate methods. 

The biggest problem, however, is that this behavior can produce test failures that are incredibly hard to understand and debug. Please note that whether the test succeeds or fails in my above example _depends solely on the order in which the tested code calls the mocked object_. If the those two (seemingly completely independent) calls get switched later on, the previously working test build will inexplicably fail, and for the wrong reasons - since the real reason was not the switch, but that one of the mocks were not properly set up.

**Comment by mockitoguy** [comment]
> Isn't the point of the strict mode to ensure that no mock behavior is declared that is not actually needed for the test

yes, that's one of the points of "strict stubbing"

> and also that whatever behavior needs to be declared gets declared?

no, that's not the goal of "strict stubbing". This is the goal of "strict mocks" - #1097 (not implemented as of writing this comment)

Hope that helps!

**Comment by pip25** [comment]
@mockitoguy
Okay, understood. Nonetheless, I believe the problems of inconsistent behavior and hard-to-debug testing failures, which I described above, still remain.
I'd be willing to submit a PR for this if we could work out a behavior that does not cause such inconsistency, but also does not make Mockito "overly strict". Would the removal of the _UnusedStubbingReporting.shouldBeReported_ call in the decision about argument mismatches be too much? (The whole inconsistency hinges on the fact that the argument mismatch check is internally tied to the check concerning unused stubs, which is hugely counter-intuitive.)

**Comment by mockitoguy** [comment]
> Would the removal of the UnusedStubbingReporting.shouldBeReported call in the decision about argument mismatches be too much?

Yes. For example, this use case would stop working:

```
//code
Object primary = factory.create("primary");
if (primary == null) {
  Object auxiliary = factory.create("auxiliary");
}

//test code
when(factory.create("primary")).thenReturn(null);
...
verify(factory, never()).create("auxiliary");
```

Implementing your suggestion would break the test above. It would require the test to declare an additional stubbing:

```
doNothing().when(factory).create("auxiliary");
```

I understand your point, though. It would be conceivable to implement your suggestion. However, we would have another user asking why the use case describe above does not work (and also argumenting that it is not intuitive :-). We need to balance the use cases and implement what's best for Mockito. One of the principles of Mockito is to avoid unnecessary mock declarations in the test code.

I'd like to close this ticket because I think we exploited all arguments on both sides. If you have suggestions on how to improve documentation or the exception message - let us know (or better - submit a PR!).

Hope that helps and thanks again for picking up this topic! Reopen if needed.

**Comment by pip25** [comment]
Quite frankly, the above seems like a buggy test to me, or at the very least it is impossible to tell whether the author forgot to mock the second create call or skipped it on purpose.

But maybe that's just me. For the time being, I think I'll be turning off strict stubs, at least until strict mocks are implemented, because the potential test instability I mentioned above seems like more trouble than it's worth.
