### ISSUE TITLE
Consider testing on the latest Java release

### ISSUE THREAD

**Issue by dmitry-timofeev** [mockito/mockito#1829]
Currently the project is tested with the following JDKs:
* 8
* 9
* 10
* 11

I suggest to add a job to test with the latest release, which is 13 at the moment, and move it as the next version is released, to ensure that Mockito is compatible with the latest JDK.

Don't know if it makes sense to create separate issues, but it could also be considered to:
* Test on early-access builds, to know if Mockito is compatible with _upcoming_ releases (likely, allowing failures)
* Drop jobs for 9, and 10 as these versions are not supported (to the best of my knowledge, there are no updates in the OpenJDK upstream and no updated builds either by Oracle, or AdoptOpenJDK, or other providers)

Related: #1827

**Comment by TimvdLippe** [comment]
Good point, I don't know what our official Java-compatibility matrix is now that Java is releasing every 6 months. @mockito/developers What about testing on the following versions:

* 8
* 11
* latest
* (14 when that comes out)

E.g. we test on every LTS and do a build on the latest as well so that we are aware of canary failures.

**Comment by TimvdLippe** [comment]
We are now doing this.
