### ISSUE TITLE
getArgumentAt is removed in 3.2.0

### ISSUE THREAD

**Issue by Yogyatha9** [mockito/mockito#1837]
I couldn't find this method in the 3.x version of InvocationOnMock. Referred to the below : 
https://github.com/mockito/mockito/blob/v3.2.0/src/main/java/org/mockito/invocation/InvocationOnMock.java 

Found no reference of removal in the release notes . Can you please investigate?

**Comment by TimvdLippe** [comment]
Oh I see now. This method was removed in `2.0.0-beta.112` (https://github.com/mockito/mockito/commit/dff5510cb3e97dae414e58ba85825ad01b273c72) and is indeed a breaking change. You should use `getArgument` instead. Sorry for the confusion.

The breaking change is listed in https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#incompatible

**Comment by Yogyatha9** [comment]
yeah moved on to use getArgument. Thanks

**Comment by DidierLoiseau** [comment]
I know this is a bit old now, but FYI, it was added back in #1646, actually before this issue was opened 🙂.

I think it was in version 2.25.1, based on 2a7489d3. The documentation doesn't seem to have been updated though as it is still listed as an incompatible change instead of indicating to upgrade to that version.

AFAICT it has always been there in 3.x.
