### ISSUE TITLE
Broken unused stubbing reporting when matching previous stubbed call

### ISSUE THREAD

**Issue by andreisilviudragnea** [mockito/mockito#1846]
When stubbing the same method call twice, and the second stub setup matches to first stubbed call, the first stub is not reported as unused, because Mockito detects the next stub setup as a usage of the previous stub setup. This is an example test:
```
public class UnnecessaryStubbingWithImplicitEqMatchers {
    @Mock IMethods mock;
    MockitoSession mockito = Mockito.mockitoSession().initMocks(this).strictness(Strictness.STRICT_STUBS).startMocking();

    @After public void after() {
        mockito.finishMocking();
    }

    @Test public void unnecessary_stubbing() {
        given(mock.simpleMethod("1")).willReturn("one");
        given(mock.simpleMethod("2")).willReturn("three");
        given(mock.simpleMethod("1")).willReturn("two");
        given(mock.simpleMethod("1")).willReturn("four");

        mock.simpleMethod("1");
        mock.simpleMethod("2");
    }
}
```

The test above should fail with `UnnecessaryStubbingException` containing two unused stubs, but it does not.

Mockito version: v3.2.4

**Comment by mockitoguy** [comment]
Nice catch! I'll review the PR!

**Comment by bbonanno** [comment]
Hey @mockitoguy @andreisilviudragnea, I think this PR has introduced a new bug (or a regression if you like).

The problem arises when using Deep Stubs, as every call in a deep stub counts as used stubbing, but if you end up stubbing that mock for real this change will change the state of the original stubbing and your test will fail with an `UnnecessaryStubbingException`

The following example is in Scala, I don't have a running Java project at hand, but I can provide a 100% Java example if this is not enough to explain the problem

```scala
  class Foo {
    def userClass: Bar = {...}
  }
  class Bar {
    def callMeMaybe: Baz = {...}
  }
  class Baz {
    def callMe: Option[String] = {...}
  }

val aFoo = mock[Foo](DefaultAnswers.ReturnsDeepStubs)
aFoo.userClass.callMeMaybe.callMe returns Some("my number")
aFoo.userClass.callMeMaybe.callMe.value shouldBe "my number"
```

That code will fail as there are 2 stubbings for `callMe`, one automatically created by the deep stub (see `ReturnsDeepStubs.class` line 67) and one for the actual stubbing I'm making to return `Some("my number")`.

**Comment by pkoenig10** [comment]
This also breaks tests that needs to legitimately stub the same invocation multiple times. Particularly with invocations that have to arguments (since all invocations will match a previous stub). See https://github.com/mockito/mockito/commit/ce1632ddd6c55a7e85bec606536aa582a3b3aea1#diff-90b7e8e4bd136ee96421dc2adde3a918R71.

A simple common example is when stubbing a `Clock`:
```
@Mock
private Clock clock;

@Test 
void test() {
    Instant instant1 = Instant.ofEpochMillis(...);
    Instant instant2 = instant1.plus(...);

    when(clock.instant()).thenReturn(instant1);
    // do something at instant1

    when(clock.instant()).thenReturn(instant2);
    // do something at instant2
}
```

**Comment by bbonanno** [comment]
@pkoenig10 yes, although that may not be the best example as you could use a chain of `thenReturn()` and have a single stubbing.
That said, for a non-experienced user that may not be obvious at all, so we'd have to weight it.

**Comment by pkoenig10** [comment]
It's not obvious to me how you would work around this if your code calls `clock.instant()` a large or variable number of times. I find the suggested work around to be pretty verbose and unergonomic:
```
when(clock.instant())
    .thenReturn(instant1)
    .thenReturn(instant1)
    // repeat however many times is necessary
    .thenReturn(instant2)
    .thenReturn(instant2)
    // repeat however many times is necessary
```

I think the best and simplest way to improve this behavior is to not unmark the previous stubbing if it has been used. If the stubbing has not previously been used, then I think the current behavior is appropriate. Unfortunately this does seem like it will be a simple fix since the a second stubbing causes a previous stubbing to be marked as used.

**Comment by bbonanno** [comment]
@pkoenig10 I fail to see how that is less verbose than multiple stubbings, but in any case, that's not the point.
I think this change should be reverted until it can be given a deeper thought. do you agree? @mockito/developers ?

**Comment by TimvdLippe** [comment]
Revert in progress: https://github.com/mockito/mockito/pull/1878
