### ISSUE TITLE
anyString() does not work for null

### ISSUE THREAD

**Issue by javaerb** [mockito/mockito#185]
Since we switched to 2.0, a statement like:
when(someClass.someMethod(anyString())).thenReturn("someValue");

will NOT take effect when you call
someClass.someMethod(null)

**Comment by bric3** [comment]
Yes the behavior of these matchers has changed in 2.0

At first there was `anything()`, which will match _anything_ obviously, later there was a shorter alias that was called `any()` that match anything too. Then there was the idea to avoid visible cast so a number of alias methods were introduced to hide the cast, methods like `anyString()`, `any(Class)`, `anyList()`, etc., yet internally they still matched anything (without type checking).

For a long time we felt this API was broken, hence in 2.0 we wanted to make things right. In this case for exemple, `anyString()` name is not about matching anything (including `null`) but about matching _any_ `String`. And since type cannot be inferred when the reference is _null_, it doesn't match. The Javadoc has been updated in this regard by the way.

For reference see issues #134, #141 

Also note 2.0 is still in beta, and we don't have listed incompatible change or migration guide, but if feel it we could accept a contribution on that matter, that would be awesome.

**Comment by tadaskay** [comment]
So basically, `anyString()` should be replaced by `or(isNull(String.class), anyString()`?

**Comment by jonfreedman** [comment]
There's a new `nullable` matcher in ArgumentMatchers which does the above

**Comment by mdaniyalkhann** [comment]
or you can use (String) any()

**Comment by JakeLin** [comment]
I think `Mockito.<String>any()` is better.

**Comment by YassinHajaj** [comment]
> There's a new `nullable` matcher in ArgumentMatchers which does the above

Hi, more info on this  nullable matcher ?

**Comment by TimvdLippe** [comment]
https://static.javadoc.io/org.mockito/mockito-core/3.0.0/org/mockito/ArgumentMatchers.html#nullable-java.lang.Class-

**Comment by Swoot1** [comment]
As jonfreedman said there's the nullable matcher:

`nullable(String.class)`

**Comment by StevenJack666** [comment]
thank you,Swoot. welcome to china

> As jonfreedman said there's the nullable matcher:
> 
> `nullable(String.class)`

**Comment by Lansorian** [comment]
@JakeLin @jonfreedman @Swoot1 
Could anyone please kindly explain the difference between `Mockito.<String>any()` and `nullable(String.class)`, which is better to use and why? I appreciate that a lot.

**Comment by mockitoguy** [comment]
The difference is that any() will not check the type. I recommend any() because it is simpler and the java compiler checks types for me (most of the time ;)). nullable() is useful in certain specific scenarios. @Lansorian, consider sending us a PR with javadoc updates if you don't find the javadocs clear.

**Comment by Lansorian** [comment]
@mockitoguy Thanks!

**Comment by Lansorian** [comment]
> The difference is that any() will not check the type. I recommend any() because it is simpler and the java compiler checks types for me (most of the time ;)). nullable() is useful in certain specific scenarios. @Lansorian, consider sending us a PR with javadoc updates if you don't find the javadocs clear.

Thanks a lot!

**Comment by AKrichevskiyNess** [comment]
Such a painful decision. Mostly because `any()` and `any*(*)` achieve this inconsistency in nulls.

E.g. I'm mocking a method with `any()` matcher and want to be more specific than that (maybe for cleaner code or maybe for new overloaded method) so I changing it to `anyString()`. Now if I'm happy enough test fails and I need to search a way how to specify nullable string (`any(String.class)` also does not work).

I think that `notNull(Class)` could be much better solution because it explicitly states that no nulls allowed and specifying type here makes much more sense because argument is not null so type can be checked. Usage of `any*(*)` in tests usually means that user does not care about value at all including null.

**Comment by boolivar** [comment]
Such a painful decision. Mostly because any() and any*(*) achieve this inconsistency in nulls.

E.g. I'm mocking a method with any() matcher and want to be more specific than that (maybe for cleaner code or maybe for new overloaded method) so I changing it to anyString(). Now if I'm ~happy~ lucky enough test fails and I need to search a way how to specify nullable string (any(String.class) also does not work).

I think that notNull(Class) could be much better solution because it explicitly states that no nulls allowed and specifying type here makes much more sense because argument is not null so type can be checked. Usage of any*(*) in tests usually means that user does not care about value at all including null.

**Comment by tomaszalusky** [comment]
I agree with boolivar. Just spent half day hunting issue why Mockito tests failed after upgrading Mockito 1->4 and found `any(BigDecimal.class)` does not match and then found this issue from [here](https://stackoverflow.com/a/44289476/653539). 

I understand nulls are at least suspicious if not bad. I also understand the point of view that null is actually not Object thus many people feels any(*.class) is counterintuitive to match it. Despite of this, mere fact that Java compiler permits assigning null arguments into object parameters (put aside overloading issues) makes me expect Mockito to behave the same way. I appreciate new `nullable` method though not keeping well-established nomenclature for most common case looks like outpoping the Pope to me.

**Comment by ThrawnCA** [comment]
> In this case for exemple, `anyString()` name is not about matching anything (including `null`) but about matching _any_ `String`.

See, in a lot of cases that's not how people are interested in using it.

Our typical use case for Mockito is, we want to unit-test a class, mocking out everything around it and telling the mock, "Return a fixed value when you're invoked" so that we aren't making a real file write, or a real web service call, etc. We do not care what was passed to the mock, whether it was a null or not. We just want it to be a stub, filling in for the real thing with minimal fuss.

Wanting the mock to do exactly one thing - "always return X" - but having to specify multiple conditions and join them with `or`, for _every parameter_? Pain in the backside.

**Comment by TimvdLippe** [comment]
@ThrawnCA if you don't need to check the type, use `any()`
