### ISSUE TITLE
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by mktitov** [mockito/mockito#187]
Exception throws on verifyZeroInteractions when using mock with default answer.
checked on versions 1.10.5-2.0.5
all ok on 1.9.5

**Comment by bric3** [comment]
Hi,

Do you have a JUnit test so that we could reproduce.
Also please see the [contributing guide](https://github.com/mockito/mockito/blob/master/CONTRIBUTING.md).

**Comment by mktitov** [comment]
public class MockitoTest extends Mockito {
    public interface TestMock {
        public boolean m1();
    };
    
    @Test
    public void test() {
        TestMock test = mock(TestMock.class, new Answer() {
            @Override public Object answer(InvocationOnMock invocation) throws Throwable {
                return false;
            }
        });
        test.m1();
        verifyZeroInteractions(test);
    }
}

**Comment by mktitov** [comment]
```
public class MockitoTest extends Mockito {
    public interface TestMock {
        public boolean m1();
    };
    
    @Test
    public void test() {
        TestMock test = mock(TestMock.class, new Answer() {
            @Override public Object answer(InvocationOnMock invocation) throws Throwable {
                return false;
            }
        });
        test.m1();
        verifyZeroInteractions(test);
    }
}
```

**Comment by bric3** [comment]
Hi, sorry for the late reply.

Thanks for the testcase, indeed we missed something there.

**Comment by bric3** [comment]
Actually the usage report was improved to include the mock name, however in this usage the default answer always returns `false`. So when the String message is generated there's a CCE because the default answer returns a `boolean`.

On your side the workaround is to return valid values for these `Object` inherited methods.

On mockito side there should be two possible thing to do:
 - get the name safely without invoking `toString`
 - validate more aggressively answer's result

**Comment by puneethpgowda0825** [comment]
Hello, I've one doubt, can we do casting for mocking objects?. When I tried to do that I got "java.lang.ClassCastException".
