### ISSUE TITLE
Compatibility of BDDMockito.then() with AssertJ and Catch-Exception

### ISSUE THREAD

**Issue by sedubois** [mockito/mockito#189]
Mockito's `BDDMockito.then()` clashes with AssertJ's `BDDAssertions.then()` and Catch-Exception's `BDDCatchException.then()`, meaning that in a same test class it is not possible to use BDD style to assert simultaneously:
- a mock's behaviour (BDDMockito: `then(dependency).delete(1)`)
- a return value (BDDAssertions: `then(result).isEqualTo("value")`)
- an exception throw (BDDCatchException: `then(caughtException()).isInstanceOf(BlahException.class)`)

It is not clear which library exactly could resolve this issue, but currently this conflict reduces the usability of all three of them. If they are all needed within a same test class, then static import cannot be used, and even when used in separate test classes, the developer can get quite easily confused as to which static import is required.

**Comment by bric3** [comment]
Correction ;
> it is not possible to use BDD style to assert simultaneously **when using static imports**

_catch-exception_ lib will no more be updated as stated by his author. Then I don't see any reasonable way to fix this in any lib as they are not coupled and they have no reason to. We won't remove or rename this API `BDDMockito.then`, and I'd rather not introduce too many aliases.

In the mean time the only sensible thing to do would be to create a class that can serve as an API dispatcher, in pseudo code something like:

```java
BDDDispatcher { 
    assertjThen(...)
    thenVerify(...)
    ...
}
```

**Comment by sedubois** [comment]
> catch-exception lib will no more be updated as stated by his author

Could you show where this is stated? https://github.com/Codearte/catch-exception is currently active. Or what system should be used instead to test exceptions in BDD style?

> In the mean time the only sensible thing to do would be to create a class that can serve as an API dispatcher

What do you mean by 'in the meantime'? What is the long-term solution to cleanly test mocks, exceptions and return values in BDD style? `assertjThen` and `thenVerify` are quite less readable than `then` and this places the maintenance burden on the developer.

Maybe I will try the Spock library to avoid these limitations.

**Comment by bric3** [comment]
>> catch-exception lib will no more be updated as stated by his author

> Could you show where this is stated? https://github.com/Codearte/catch-exception is currently active. Or what system should be used instead to test exceptions in BDD style?

I remember I saw it at some point last year on GC at their old home : https://code.google.com/p/catch-exception/ but it seem they have changed their plan, I didn't even know they migrated to GH. Actually I prefer AssertJ for assertions, with version 2.0.0 there's nifty API on that matter.

>> In the mean time the only sensible thing to do would be to create a class that can serve as an API dispatcher
> What do you mean by 'in the meantime'?

I mean that until mockito team reach consensus on this API change, this issue is on hold.

> What is the long-term solution to cleanly test mocks, exceptions and return values in BDD style?

It's probably a question of taste, but I don't see any clarity problem if not using _static imports_, note that the little pseudo is just random ideas, but this can of course be renamed according to your taste. Maybe asking on the mockito mailing list can help on that matter.

Spock is indeed a great tool, I don't know they integrate stuff still. I you have feedback I'm interested.

**Comment by mariuszs** [comment]
Im a guy from catch-exception team :) I would recommend to use 'BDDAssertions.then' instead of 'BDDCatchException.then'. This combo works fine for Java6 and Java7. 'BDDCatchException.then' is here only for compatibility with Java8

Java8 has some problem with generics (bug? or feature) and do not compile. I would recommend using AssertJ 'ThrowableAssert.thenThrownBy' alone (without catch-exception)

**Comment by sedubois** [comment]
OK great :) I use Java 8 and your solution works, so things are settled regarding catch-exception by using the AssertJ API (`BDDAssertions.then()`).

Now the solution on Mockito side should IMHO be the same: use the AssertJ API (a nifty API as you mentioned). Otherwise we are stuck with using `verify()` instead of `then().should...()` to check mock interactions and thus cannot use BDD style.

I also tested Spock 1.0 (spock-core + spock-spring) to write unit tests and Spring integration tests (including with `MockMvc` and transactions) and I can recommend it so far, as it covers everything I asked here and much more with a clean BDD style. Just need some patience to learn Groovy and some things which are approached in a different way (e.g. "Mocking and stubbing of the same method call has to happen in the same interaction" cfr. http://spockframework.github.io/spock/docs/1.0/interaction_based_testing.html).

**Comment by bric3** [comment]
OK, thanks for the feedback @mariuszs. And Thnaks for the feedback on Spock too :)

> Now the solution on Mockito side should IMHO be the same: use the AssertJ API.

I don't follow you there. The only possible thing to do is to add other _tactical_ aliases, @szczepiq and I have mixed feelings about that. That's why I proposed to create a custom _dispatch_ api with those tactical aliases, e.g.

```java
then(bike).contains(a_handlebar)
thenA(person).should(times(2)).ride(bike);
```

**Comment by sedubois** [comment]
From my user's endpoint, I see that Catch-Exception has been able to resolve this issue of conflicting `then()`s by checking caught exceptions through the AssertJ API. So all I'm saying is that Mockito should IMHO do the same, so that the only `then()` that the user should call would be AssertJ's (which makes sense, it _is_ an assertion API).

**Comment by bric3** [comment]
Indeed, but AssertJ has nothing to do with mocks ;)
It's not the role of AssertJ to know mockito internals to check the interactions. Also current mockito matchers API is based on hamcrest. And for several reason upgrading hamcrest has proven to be a difficult task, we now even want to remove the dependency on external framework as much as possible including hamcrest.
