### ISSUE TITLE
@Mock does not work with Maven and Java 13

### ISSUE THREAD

**Issue by schuettec** [mockito/mockito#1925]
Hi, I tried to setup a minimum example project to get Mockito working with JUnit 5, Maven and Java Open JDK 13 but the mock injection `@Mock` does not work.

The test case is simple:
```
@ExtendWith(MockitoExtension.class)
public class MockitoTest {
    @Mock
    protected MyInterface myMock;
    @Test
    public void shouldMock() {
      // Do something
    }
}
```
But I get the following error when I run Maven Surefire for testing:
```
[INFO] Running com.github.schuettec.mocktest.MockitoTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.571 s <<< FAILURE! - in com.github.schuettec.mocktest.MockitoTest
[ERROR] com.github.schuettec.mocktest.MockitoTest.shouldMockBothWithoutOpens  Time elapsed: 0.546 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: Problems setting field myMock annotated with @org.mockito.Mock(name="", stubOnly=false, extraInterfaces={}, answer=RETURNS_DEFAULTS, serializable=false, lenient=false)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected com.github.schuettec.mocktest.MyInterface com.github.schuettec.mocktest.MockitoTest.myMock accessible: module mocktest does not "opens com.github.schuettec.mocktest" to unnamed module @57fd91c9
```

My module seems not to be available for Mockito's reflective access.  Since the documentation does not say anything about `--add-opens` to be required (that also applies to Surefire Docs and so on) I expected the tests to be successfull.

The involved version are the following
- maven-surefire-plugin 3.0.0-M4
- junit-jupiter 5.7.0-M1
- mockito-core 3.3.3
- mockito-junit-jupiter 3.3.3

I uploaded an example project.
- Example Project: https://github.com/schuettec/junit5-java13-test
- Build-Logs: https://travis-ci.org/github/schuettec/junit5-java13-test/builds/683407777

Btw: If I use `Mockito.mock()` everything works fine, although Mockito does a lot more reflection stuff and the same access problems should occur, I thought.

**Comment by raphw** [comment]
So the issue here is that Mockito is trying to set the values of the fields which are in a module and therefore not accessible to the Mockito framework. We could work around using Unsafe by abusing some internal API but generally, this only works if you allow Mockito into your code by opening it.

When using the inline mock maker, we could adjust the module graph programmatically without using internal API but it's also kind of a hack.

**Comment by schuettec** [comment]
I understand the problem. But I'm confused that JUnit is able to do reflective stuff like processing annotations in my test class without the need for `--add-opens`. So some mechanism is there to get a valid reflective access. But might be that some IDE/Build-Plugin does this.

**Comment by raphw** [comment]
So, this is a consequence of the forked VM used for testing. If you set `-DforkCount=0` to disable forking, it will not happen on your VM either. It is a question of running on the module or the class path.

**Comment by TimvdLippe** [comment]
We have since improved our module handling and included numerous scenarios in our regression test: https://github.com/mockito/mockito/blob/main/subprojects/module-test/src/test/java/org/mockito/moduletest/ModuleHandlingTest.java I am pretty sure that this issue has been resolved as well. If you are still running into this issue, please feel free to reopen this issue. Thanks!
