### ISSUE TITLE
If you have both through constructor and through annotation injection fields in class, injection will be failed for the first time

### ISSUE THREAD

**Issue by soulcub** [mockito/mockito#195]
JDK 1.6 + Mockito 1.9.5

If you have some class with 2 types of injection:

```java
class A {
}
class B {
}
class C {
    public A a;
    @Inject
    public B b;

    public C(A a) {
        this.a = a;
    }
}
```
and you want to instantiate them with ```@RunWith(MockitoJUnitRunner.class)``` you will see that annotated fields will be ```null```.
```java
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.runners.MockitoJUnitRunner;

import javax.inject.Inject;

class A {
}
class B {
}
class C {
    public A a;
    @Inject
    public B b;

    public C(A a) {
        this.a = a;
    }
}

@RunWith(MockitoJUnitRunner.class)
public class Test {
    @Mock
    A a;
    @Mock
    B b;
    @InjectMocks
    C c;

    @org.junit.Test
    public void testName() {
        traceAllInstances("before initMocks");

        MockitoAnnotations.initMocks(this);

        traceAllInstances("after initMocks");
    }

    private void traceAllInstances(String message) {
        System.out.println("a to inject " + message + ": \n'" + a + "'");
        System.out.println("b to inject " + message + ": \n'" + b + "'");
        System.out.println("a in test " + message + ": \n'" + c.a + "'");
        System.out.println("b in test " + message + ": \n'" + c.b + "'");
    }
}
```
Output:
```
a to inject before initMocks: 
'a'
b to inject before initMocks: 
'b'
a in test before initMocks: 
'a'
b in test before initMocks: 
'null'
a to inject after initMocks: 
'a'
b to inject after initMocks: 
'b'
a in test after initMocks: 
'a'
b in test after initMocks: 
'b'
```
Interesting thing that if you will run ```MockitoAnnotations.initMocks(this);``` right before this code - everything will be ok, annotated field will be instantiated.

**Comment by bric3** [comment]
This is kinda wanted, and documented in the `@InjectMocks` javadoc.

InjectMocks sees that `C` has a constructor and there's a mock of type `A`, so it creates `C` with the constructor. And stop injection right there, modifying the field of an object after the constructor is wrong, mockito chose to not do it because it favors good object design.

About the interesting behavior, this is also documented. Fact is if there's already an instance in the field annotated by `@InjectMocks`, then it keeps this instance as it may have been instantiated by the user itself, this time constructor injection is skipped and the algorithm directly use the _property and setter_ injection.

This is kind of a hacky side effect, that cannot really be avoided at the moment. And clearly this is wrong to rely on such behavior, I'd favor instead a better object oriented design !
