### ISSUE TITLE
Add matchers for scala value classes containing primitives 

### ISSUE THREAD

**Issue by ppiotrow** [mockito/mockito#198]
The complete details are here
https://groups.google.com/d/msg/mockito/m_Ptz8eVH58/wS2czEAaD-oJ

**Comment by bric3** [comment]
Hi,

Actually that will probably never happen as these classes are in the scala library, which we cannot depend upon. If this lib is not there then the class won't even load. Instead I'd rather suggest that it should be mockito sugar to declare them.

**Comment by ppiotrow** [comment]
I think that there is possibility. I know that NPE in any[SomeValueClass] happens because of trying to assign null to value that looks like object but is primitive.  Maybe there is possibility to add some reflection checks in runtime. Instead of null just try to assign default primitive value as in HandyReturnValues.java.
The same could be applied to other matchers as Matcher.equal . There could be introduced some reflection check if given class has method .equals() in runtime. If not the comparison should be done as for primitives.
Thats why the hack anyObject().asInstanceOf[SomeValueClassWithStringValue] works. The String is simply not a primitive but has equals.

**Comment by bric3** [comment]
I do not think we will put scala specific inside mockito, as we just don't add groovy / android / JEE specific stuffs. Because we'd like to keep the working set as simple and focused as possible. Also there's the reason that we are not able to maintain stuff that we don't use in the team in our daily job, this is especially true for scala / groody and android.

What you are asking certainly could be implemented in the mockito sugar library, by changing the default answer of a mock at creation time (if not overridden by a user).
As for matchers these would probably have to be handled by mockito sugar as well. 

I just google and found that it is part of scalatest and that their project is host on GH too, you should report to them IMHO : https://github.com/scalatest/scalatest

**Comment by ppiotrow** [comment]
I understand that, thank you.

**Comment by bric3** [comment]
@ppiotrow Thx to you for the interest in mockito ;)
