### ISSUE TITLE
Missing OngoingStubbing thenReturn(T... values)

### ISSUE THREAD

**Issue by gnall** [mockito/mockito#2049]
I noticed that in the [OngoingStubbing](https://github.com/mockito/mockito/blob/release/3.x/src/main/java/org/mockito/stubbing/OngoingStubbing.java) class, the method thenReturn(T... values) is missing. This could be useful for cases where you have an array of string values and you want to return in a specific order. The current implementation requires the following which I feel is a weird way of doing this. If you believe there is a specific reasoning behind this please correct me.

`Mockito.when(method.invoke(mockedObject, array)).thenReturn(array[0], Arrays.copyOfRange(array, 1, array.length));`

while my future pull request will require the following

`Mockito.when(method.invoke(mockedObject, array)).thenReturn(array);`

**Comment by gnall** [comment]
Under further examination, I think I can just use..
```
for(ArrayObjectType object : Array){
    Mockito.when(method.invoke(mockedObject, array)).thenReturn(object);
}
```
Still looking into this though.

**Comment by Marcono1234** [comment]
#11 actually tried to add that, but it was refused. One of the reasons why it was refused is:
> Using varargs silently make the runtime allocate an array for each invocation, whatever the number of arguments.

Personally I don't think that this is very important for Mockito since it is a framework for testing, where performance does not play such a big role (though should not be neglected either).

One situation where such a varargs method could become confusing is when the return type is `Object` and the user wants the mock to return an `Object[]`:
```java
interface MyClass {
    Object doSomething();
}

MyClass mock = mock(MyClass.class);
Object[] result = {"a", "b"};
when(mock.doSomething()).thenReturn(result);
```
With a `thenReturn(T... args)` overload that would lead to two separate return value, `"a"` and `"b"`, instead of the intended `["a", "b"]`. This could be solved by explicitly casting the argument to `(Object)`, but might be cumbersome.

It would also require removing `thenReturn(T, T...)` because it would be ambiguous for the compiler: `OngoingSubbing<Object>.thenReturn("a", "b")`
```
reference to thenReturn is ambiguous
  both method thenReturn(T...) in OngoingStubbing and method thenReturn(T,T...) in OngoingStubbing match
```

Though I do not know how common such a use case is and whether this minor inconvenience might be acceptable.

**Comment by mockitoguy** [comment]
@Marcono1234, thank you for good analysis of this feature request.
