### ISSUE TITLE
anyUUID() (suggestion)

### ISSUE THREAD

**Issue by TVHayk** [mockito/mockito#2068]
I suggest to implement a new function: `org.mockito.ArgumentMatchers.anyUUID()`, which will replace `org.mockito.ArgumentMatchers.any(java.util.UUID.class)`.

```
    public static long anyUUID() {
        reportMatcher(new InstanceOf(UUID.class, "<any uuid>"));
        return null; // Or return UUID.fromString("0-0-0-0-0");
    }
```

**Comment by mockitoguy** [comment]
Indeed it's shorter than any(UUID class). My understanding is that parameterless ```any()``` does not fit your use case because you want to reject null value?

I'm +1 for this change. Can you submit a PR?

> // Or return UUID.fromString("0-0-0-0-0");

Yes, please.

**Comment by TimvdLippe** [comment]
I am not in favor of this change. Given that `any(UUID.class)` already works and it rejects `null`. It seems rather arbitrary to add the UUID to our API and it is unclear on what basis it should be included. E.g. why should we add support for UUID but not for any other type?

**Comment by mockitoguy** [comment]
@TimvdLippe, thank you for feedback! You convinced me.

**Comment by mockitoguy** [comment]
@TVHayk, we'd like to take conservative approach in adding new methods to the API. Please use ```any(UUID.class)```. You can always introduce a helper static method in your own test utility that provides ```anyUUID()``` method.

We added methods like ```anyString()```, ```anyList()``` to the API because we believed that they are very common use cases. UUID does not seem that common based on the demand (you're the first person to ask).

Let's avoid adding this new method at this time. Thank you for your suggestion!

**Comment by TimvdLippe** [comment]
Let's close this per the above comment. Thanks for the suggestion!

**Comment by TVHayk** [comment]
Ok. No problem. I just use `anyString()`, `anyBoolean()`, `anyList()`, `anySet()` quite often, because it is simple and easy. And nowadays more and more applications, especially in DDD use UUIDs. I make such a static method myself for now. I just thought I'm gonna make a suggestion. Further, you know it better if you want to implement that function or not.
