### ISSUE TITLE
AdditionalAnswers Answer0 ?

### ISSUE THREAD

**Issue by goughy000** [mockito/mockito#2186]
Hey,

Firstly, thanks so much for mockito - probably my most liked and often use dependency, alongside junit and assertj, mockito is always in my "must haves" for any new project :)

**Feature Request:**

Currently there are Answer1-Answer6 which can be passed to AdditionalAnswers.answer(..)

Would you be open to adding an Answer0 (and VoidAnswer0) ?

This would allow these uses cases

```java
public interface MyInterface {
    String method();
}
```

Currently have to cast, and have unused "invocation" input:
```java
@Test
void test() {
    MyInterface mock = mock(MyInterface.class);
    when(mock.method()).thenAnswer((Answer<String>) invocation -> "hello");
}
```

With Answer0:
```java
@Test
void test() {
    MyInterface mock = mock(MyInterface.class);
    when(mock.method()).thenAnswer(answer(() -> "hello"));
}
```

Also then allows for method ref:
```java
@Test
void test() {
    MyInterface mock = mock(MyInterface.class);
    when(mock.method()).thenAnswer(answer(this::theAnswer));
}

private String theAnswer() {
   System.out.println("we're in the answer!");
   return "something";
}
```

(obviously these examples are contrived, imagine there being something other than being a basic return)

Happy to make a contribution for this if it's something you agree could be useful?

Maybe there's already a helper method in Mockito for this and I've just not found it..

**Comment by TimvdLippe** [comment]
Thanks for your suggestion and glad you enjoy using Mockito!

The answer interface is used when you need to obtain the parameters that were passed in the method. If you don't care about the parameters (since there aren't any), then you should use `.thenReturn` instead. Therefore, I don't think we require an additional answer, given that `.thenReturn` already supports this use case. Let us know if we missed anything 😄

**Comment by goughy000** [comment]
@TimvdLippe Yes I think you maybe missed something.

thenReturn only allows me to pass a precalculated value, not a value calculated at time of invocation.

e.g.
```java
AtomicInteger i = new AtomicInteger();
when(mock.method()).thenAnswer(answer(() -> i.incrementAndGet()));
```

the only way to do this currently is like
```java
AtomicInteger i = new AtomicInteger();
when(mock.method()).thenAnswer((Answer<Integer>) invocation -> i.incrementAndGet());
```

my actual use case where I came across this was something (but not exactly) like this
```java
// given
CountDownLatch latch = new CountDownLatch(2);
when(mock.method()).thenAnswer((Answer<Integer>) invocation -> { latch.countDown(); return 1; });

// when
sut.call();

// then
latch.await(); // waits for 2 invocations on mock
assert(...);
```

given the Answer1-6 already existed, I felt it would have been convenient to write this if Answer0 had existed as I have no need for the InvocationOnMock parameter nor any method params
```java
when(mock.method()).thenAnswer(answer(() -> { latch.countDown(); return 1; }));
```

**Comment by TimvdLippe** [comment]
Thanks for the additional information. I am still a bit confused though, so bear with me.

As I understand it, the following works:

```java
when(mock.method()).thenAnswer((Answer<Integer>) invocation -> i.incrementAndGet());
```

I am not sure if the cast to `Answer<Integer>` is necessary, is it? I would have assumed that the Java type interference was able to do deduce that, so that you can write the following:

```java
when(mock.method()).thenAnswer(invocation -> i.incrementAndGet());
```

That seems to be the most concise way of writing what you want, is it not? I think you can even do `_ -> i.incrementAndGet()` which would avoid the need for a method call and passing in a lambda.

```java
when(mock.method()).thenAnswer(_ -> i.incrementAndGet());
```

That seems to fit the needs as posted in your use case, does it not?

**Comment by goughy000** [comment]
![image](https://user-images.githubusercontent.com/3418267/105525937-a6247d80-5cd9-11eb-8104-f2756aff54ce.png)

I've added a helper method to my test class instead

**Comment by perlun** [comment]
+1 on this one. I've also found the need from this from time to time. It feels convoluted to have to create a `Function<T, R>` when what you _really_ want to create is a `Supplier<T>`... :slightly_smiling_face:

**Comment by perlun** [comment]
My use case more specifically. But I realize this is a very very minor annoyance... :innocent: since no `answer()` call is even needed in this case, unlike when you do `Answer[1-6]`-style mocking:

```java
doAnswer( invocation ->
        networksFixture.values()
).when( networkMediatorMock )
        .getNetworks();
```

We can't use `when(mock.method())`-based mocking since we are creating our mocks like this (think of it as a "strict" mode if you like, forcing exceptions on all unmocked method calls):

```java
@Contract( pure = true )
public static <T> T createMock( Class<T> klass, String context ) {
    return mock( klass, (Answer<Object>)invocation -> {
        String method = invocation.getMethod().toGenericString();
        throw new RuntimeException( context + " method not mocked: " + method );
    } );
}
```
