### ISSUE TITLE
Calling getExceptionTypes() on concrete object that is used as interface doesn't return exception types from interface

### ISSUE THREAD

**Issue by henrykuijpers** [mockito/mockito#2201]
org.mockito.internal.stubbing.answers.InvocationInfo#isValidException is doing validation on the exception types that can be thrown from this method.

In my codebase, I'm programming against an interface, but in fact, a spy is created from an instance that is implementing the interface, that drops the exception types that that implementation does not throw. However, the code that is calling the interface is of course unaware of that fact. Also, that implementation is a mock implementation (a real mock implementation, not a Mockito mock()/spy() instance). 

A testcase here:
```
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.exceptions.base.MockitoException;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.spy;

@ExtendWith(MockitoExtension.class)
public class MockitoExceptionTypesIssue {
    @Test
    void exceptionTypeIoExceptionShouldBeMockableForObjectBeingSpyedOn() {
        final I x = spy(new C());
        final IOException ioException = new IOException("Oh my god!");
        final MockitoException e = assertThrows(
                MockitoException.class,
                () -> doThrow(ioException)
                        .when(x)
                        .m());
        assertEquals("\n" +
                "Checked exception is invalid for this method!\n" +
                "Invalid: " + ioException,
                e.getMessage()
        );
    }

    interface I {
        void m() throws IOException;
    }

    static class C implements I {
        public void m() {
            // no-op
        }
    }
}
```

**Comment by shreelakshmijoshi** [comment]
Hi @TimvdLippe !
I am a new open source contributor and would love to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?

**Comment by harshit181** [comment]
isn't it expected behavior?
From the user perspective , it look like that method can throw super method exception but from code perspective it is limited to exception of object created.
As we are spying on the object and method in that object is just throwing the sub Exception ,the code knows that it will throw only sub Exception and not exception implemented by super method .

the same issue(?) will happen when mocking a class with interface /parent class with additional method exception . 

From the implementation perspective 
As we are mocking /spying on the object of sub class ,the mockito only knows about the method and class being mocked ,not the reference class/interface ,so not sure if anything can be done even if this is considered as a bug 


`
final I x = new C();
x.getClass() ; // it will return C ,not I 


`
