### ISSUE TITLE
How to mock a static void method?

### ISSUE THREAD

**Issue by yjYinch** [mockito/mockito#2390]
I want to mock the method a, which is a static void method, so I want to know how it mock. thank you.
```
public class AUtilClass{
    public static void a(){
        // do something
    }
}

**Comment by EugeneLesnov** [comment]
Hi!
Just refactor your code..
It's considered to be a bad practice. If when you write your tests you HAVE to mock `static void` - there's something wrong with your code.

**Comment by nadernader99** [comment]
If your code dependency cannot be refactored (e.g. 3rd party framework) then MockedStatic can help you.  Below is a working test for your example class. The mockito-inline dependency must be included in your project.  You can also use other mockito features likes when-thenReturn, argument matchers, etc. The try with resources format is unusual because the class must be rewritten during the test and then restored after the test. Otherwise, you would create test crosstalk and many other problems.

The trouble dealing with static methods in testing is one of many reasons to avoid them. The reality of eventually being forced to deal with them is why this addition to Mockito is a valuable tool of last resort.

You should be aware that this feature is new and currently marked as incubating. 

```
@Test
    public void canMockStaticCalls() {

        try (MockedStatic<AUtilClass> utilClass = Mockito.mockStatic(AUtilClass.class)) {

            AUtilClass.a();
            utilClass.verify(AUtilClass::a);

        }
    }
```

**Comment by TimvdLippe** [comment]
Closing per the above comments, thanks!

**Comment by yjYinch** [comment]
Thank you for your answers
