### ISSUE TITLE
JUnit5 Mockito Extension: @InjectMocks seems to discard generic type

### ISSUE THREAD

**Issue by SaltySunlight** [mockito/mockito#2409]
Hello everybody, it seems that the Mockito JUnit 5 extension (**`@InjectMocks`**) does not properly work for generics. Declaring something like the following in a JUnit5 test:

```java
@Mock(name = "mockA")
private GenericObjectContainer<String> mockA;
@Mock(name = "mockB")
private GenericObjectContainer<Integer> mockB;
@InjectMocks
private TestClass myTestObject; // has a constructor setting the distinct fields
```

leads to only `mockA` being injected into `myTestObject` which is expected to receive `mockA` and `mockB`, which makes it impossible to apply distinct `when`-mock-behaviour for a whitebox test. A workaround is to define the mocks the old-fashioned way using `Mockito.mock(...)` and creating the test object myself via `new TestClass(mockA, mockB)`.

I've created a project that reproduces the problem: [Mockito Junit5 Generics Bug](https://github.com/SaltySunlight/MockitoJunit5ExtensionGenericsBug).

Can anyone confirm that this really is a bug?

**Comment by LeMikaelF** [comment]
The link to your project is broken, and I wasn't able to reproduce it ([gist](https://gist.github.com/LeMikaelF/a6ce6bd83709f7f8fa7e126cfdd4155b))...

**Comment by SaltySunlight** [comment]
@LeMikaelF Here's my project, that fails.: https://github.com/SaltySunlight/MockitoJunit5ExtensionGenericsBug

**Comment by SaltySunlight** [comment]
It *seems the problem is caused by the `@InjectMocks`* which I assume does not take the generic type to take into account.
In my [test](https://github.com/SaltySunlight/MockitoJunit5ExtensionGenericsBug/blob/master/src/test/java/junit/MockitoJunit5GenericsFailureTest.java) the field `GenericContainer<Integer>` receives a field `GenericContainer<String>`.

![grafik](https://user-images.githubusercontent.com/47625987/131315924-550978d7-7cbc-4da2-96b5-c1a05b029de8.png)

**Comment by LeMikaelF** [comment]
This is because `ConstructorInjection` (line 82) checks only the object types (and because of type erasure, `List<String>` and `List<AnythingElse>` are the same at runtime).

You won't get this problem with field injection, or property injection. I don't think these can be forced, however, as Mockito (per documentation) will just use the first successful strategy of: constructor injection, property injection, and field injection. It is my opinion that this would make a really nice feature (something like `@InjectMocks(InjectionStrategy.FIELD)`, akin to JPA's `@Access`). I don't really understand why the constructor injection strategy doesn't consider parameter names when multiple `@Mock` or `@Spy` fields match types, and this behaviour is not well documented.

The docs for `InjectMocks` also say

> Mockito is not an dependency injection framework, don't expect this shorthand utility to inject a complex graph of objects be it mocks/spies or real objects.

By comparison, here is how Spring Framework, an actual injection framework, deals with parameterized types for injection: [ResolvableType](https://github.com/spring-projects/spring-framework/blob/b595dc1dfad9db534ca7b9e8f46bb9926b88ab5a/spring-core/src/main/java/org/springframework/core/ResolvableType.java). I'm not a maintainer or anything, but I'd be surprised if Mockito decided to include such complex code that isn't really related to mocking. 

I think your best option would be to manually construct the object in a `@Before` method.

---

If a maintainer happens to read this, I'd be interested in giving a go at implementing a `@InjectMocks(InjectionStrategy.FIELD)` override for injection strategies. If this isn't an option, I'd also be interested in improving the documentation of `@InjectMocks`.

**Comment by SaltySunlight** [comment]
Thanks for the detailed comment @LeMikaelF ! I personally fully understand the MockitoExtension and its related annotations do not need to work as a fully-fledge CDI framework like Spring provides. **As the documenation is clear on this and it is still easily possible to create a test object with mocked dependencies**, I'm closing this issue.
All the best to you - Mockito is really nice! :)
