### ISSUE TITLE
ArgumentMatchers not working for Mockito.mockStatic

### ISSUE THREAD

**Issue by nickmafra** [mockito/mockito#2497]
When I do a mockStatic with argument matchers like this:

```
var mockedRequestClass = Mockito.mockStatic(RequestClass.class);
mockedRequestClass.when(() -> RequestClass.sendRequest(mockedUrl, any(), any())).thenReturn(null);
```

Mockito throws the following exception:
`org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.`

How can I use argument matchers with Mockito.mockStatic? Shouldn't that be possible?

**Comment by nickmafra** [comment]
Note: if I remove ArgumentMatchers no exceptions are thrown.

**Comment by Cybermite** [comment]
@nickmafra try using matchers for all the params (see the added eq matcher below):

```
var mockedRequestClass = Mockito.mockStatic(RequestClass.class);
mockedRequestClass.when(() -> RequestClass.sendRequest(eq(mockedUrl), any(), any())).thenReturn(null);
```

When using traditional mocks, it'll tell you to use matchers for all the params when at least one of them uses a matcher. My hunch is it's the same for MockedStatic and the exception you're getting is misleading because it swallowed the root cause of the issue.

**Comment by TimvdLippe** [comment]
Sounds like we should update `mockStatic` to behave similar to the others, where we validate the argument matchers. PRs welcome!

**Comment by temp-droid** [comment]
Hi @TimvdLippe , I think the issue comes from here: 
https://github.com/mockito/mockito/blob/main/src/main/java/org/mockito/internal/MockedStaticImpl.java#L48-L60

The validation is happening but ignored. Not sure why, but this could fix it if we want to keep the `catch Throwable` for backwards compatibility: 
```java
        try {
            verification.apply();
        } catch (MockitoException exception) {
            throw exception;
        } catch (Throwable ignored) {
        }
```

What do you think?

**Comment by khamidjon-khamidov** [comment]
In my case, I had to pass Integer. `any()` didn't work. I had to use `anyInt()` for some reason

**Comment by davidreis97** [comment]
This is still happening to me.

This works:

```java
MockedStatic<MyClass> myMockedStatic = Mockito.mockStatic(MyClass.class);
myMockedStatic.when(() -> MyClass.myMethod(myVariable, myOtherVariable)).thenReturn(myReturn);
```

This also works:

```java
MockedStatic<MyClass> myMockedStatic = Mockito.mockStatic(MyClass.class);
myMockedStatic.when(() -> MyClass.myMethod(any(), any())).thenReturn(myReturn);
```

The following doesn't work:

```java
MockedStatic<MyClass> myMockedStatic = Mockito.mockStatic(MyClass.class);
myMockedStatic.when(() -> MyClass.myMethod(any(), eq(myOtherVariable))).thenReturn(myReturn);
```
