### ISSUE TITLE
ContainsExtraTypeInfo interface breaks support fuzzy matchers in 4.x (from 3.9)

### ISSUE THREAD

**Issue by u3r** [mockito/mockito#2538]
Hi, 

i just updated a project with custom argument matchers from mockito 3.9.0 to 4.0.0 and noticed this:
the commit https://github.com/mockito/mockito/commit/1ad82350765566b2afabbab9ec15ad5ccd54951a?diff=split introduced a change to the `ContainsExtraTypeInfo` interface that *requires* the matcher to have a `wanted` object to return.

In my usecase we don't have a wanted object but instead check, whether the argument is of a certain type and some of the properties match expected values.
Simplified example (working with Mockito 3.9.0):
```
public static class ClientMatches implements ArgumentMatcher<ClientRepresentation>, ContainsExtraTypeInfo, Serializable {

      private final String expectedId;

      public ClientMatches( String expectedId ) {
         this.expectedId = expectedId;
      }

      @Override
      public boolean matches( ClientRepresentation argument ) {
         return Objects.equals( expectedId, argument.getClientId() );
      }

      private String describe( Object object ) {
         return ValuePrinter.print( object );
      }     

      public String toStringWithType() {
         return "(" + ClientRepresentation.class.getSimpleName() + ") with id of '" + expectedId + "'";
      }

      public boolean typeMatches( Object target ) {
         return target != null && target instanceof ClientRepresentation;
      }
      
   }
```
For Mockito 4.0.0 we now need to have a implement a `Object getWanted();` that is used in `org.mockito.internal.matchers.text.MatchersPrinter#applyPrintSettings` to get the class of object wanted and put it back into `toStringWithType( String className ) `
So the intermediate fix seems to be: 
```
[...]
      @Override
      public String toStringWithType( String ignored ) {
         return "(" + ClientRepresentation.class.getSimpleName() + ") with id of '" + expectedId + "'";
      }

      @Override
      public Object getWanted() {
         return null;
      }
[...]
```
Which seems really weird.

I don't fully understand the reason to change this in the first place (from the mentioned commit alone) 
So I'd like to open the discussion to change the Interface (again) for 5.x to something suitable for both usecases
```
public interface ContainsExtraTypeInfo {

    /**
     * @param className - name of the class to be printed in description
     * Returns more verbose description of the object which include type information
     */
    String toStringWithType(String className);

    /**
     * Checks if target target has matching type.
     * If the type matches, there is no point in rendering result from {@link #toStringWithType(String)}
     */
    boolean typeMatches(Object target);

    /**
     *
     * @return Returns the wanted argument
     */
    Class<?> getWantedType();
}
```
This would sidestep the problem of having to have an actual instance to return but still be awkward IFF (not a current usecase of mine) a matcher needs to check for polymorphic parameters (i.e. expects a subset of subclasses of some type and therefor cannot give a single `getWantedType()` ).

**Comment by TimvdLippe** [comment]
`ContainsExtraTypeInfo` is an internal interface (it resides in `org.mockito.internal`) and we therefore do not consider such changes for SemVer. Additionally, we don't include them in our official JavaDoc, as we don't support users using these interfaces directly. You can use our ErrorProne artifact to automatically prohibit usages of internal Mockito classes: https://github.com/mockito/mockito/blob/cb948d231041a7639e46e39d3456a98bf5a3daf3/subprojects/errorprone/src/main/java/org/mockito/errorprone/bugpatterns/MockitoInternalUsage.java#L29

If you feel like our public API does not support your use case, then we can consider adding a new method/interface/class to our public API. That said, I am closing this particular issue, given that it is about a change to an internal class, which we can make at any point in time. The fact that we made this change in Mockito 4.0.0 is accidental, as we could have made this change in a minor/patch release as well.

For additions on our public API, please file a separate issue so that we can take a look what would be the best way to solve your use case. Thanks!
