### ISSUE TITLE
MockitoExtension should implement BeforeAllCallback and make sure any context @Mock/@InjectMocks is initialized before a @BeforeAll

### ISSUE THREAD

**Issue by nightswimmings** [mockito/mockito#2563]
Currently @Mock is initialized later than @BeforeAll, so when used as a dependency is always null.
The issue is described here:
https://stackoverflow.com/questions/65543399/mockito-does-not-initialize-mock-in-test-running-with-junit-5-in-beforeall-anno

It should be possible a setup like:

```
@ExtendWith(MockitoExtension.class)
@TestInstance(Lifecycle.PER_CLASS)
class SampleUnitTest {

    TestSut sut;

    @Spy
    MockedDependency mockedDependency; 

    @BeforeAll
    void setUp(){ 
        sut = new TestSut(mockedDependency);
    }
    
    @Test 
    void whenSutXThenY {
        doReturn(Y).when(mockedDependency).subCall(x);
         assertThat(sut.method(X)).isEqualTo(Y);
    }
```

**Comment by TimvdLippe** [comment]
This is intentional, as we don't want mocks to be shared across individual tests. Therefore, we want mocks to be fresh for each specific test.

If you require a mock to exist in the `@BeforeAll`, you would manually have to create one. However, we advise against doing so to avoid accidentally sharing stub state across test runs.
