### ISSUE TITLE
Get NPE when using argThat with  custom ArgumentMatcher

### ISSUE THREAD

**Issue by hunao0221** [mockito/mockito#2633]
I tried to use a custom ArgumentMatcher, but I always get NPE, and for me it's hard to find the reason now, even though I found the NPE related in the documentation. 
```java
    @Test
    void debug() {

        class ListGetMatcher implements ArgumentMatcher<Integer> {
            public boolean matches(Integer index) {
                return index == 2;
            }

        }

        List mock = mock(List.class);

        when(mock.get(argThat(new ListGetMatcher()))).thenReturn(200);

        assertEquals(200, mock.get(2));

        //when(mock.addAll(argThat(new ListOfTwoElements()))).thenReturn(true);

        //mock.addAll(Arrays.asList("one", "two"));

        //verify(mock).addAll(argThat(new ListOfTwoElements()));

    }
```

**Comment by hunao0221** [comment]
I  just change to use intThat and it's works fine.
```java
doReturn(200).when(mock).get(intThat(new ListGetMatcher()));
```

But the following case will still cause the NPE. 
```java
when(substationQueryExecutor.getSubById(argThat(argument -> argument.getId() == 1L))).thenReturn(new Substation());
```
I expect a Substation to be returned when the id of argument is 999.  What should I do?

**Comment by TimvdLippe** [comment]
This is documented as the auto-unboxing caveat: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/ArgumentMatchers.html

**Comment by trung** [comment]
Recently I've run into the similar issue, but in my case, I was trying to mock the Spring JPA Repository's `save()` method.
Something like:
```java
@Repository
public interface MyRepository extends R2dbcRepository<MyTentity, ID> {
   Mono<MyEntity> save(MyEntity e);
}
```
Now when I try to mock
```java
when(myRepository.save(argThat(..)).thenReturn(..);
```
It throws `NullPointerException` due to the obvious reason explained in other comment: internal proxied implementation of `R2dbcRepository` does check for not null:
https://github.com/spring-projects/spring-data-relational/blob/dad6e056e871640ffa3da3ab6f7fb7920566e57a/spring-data-r2dbc/src/main/java/org/springframework/data/r2dbc/repository/support/SimpleR2dbcRepository.java#L116-L127

To overcome this, I use a workaround with `Optional` to wrap `argThat`:

```java
when(myRepository.save(Optional.ofNullable(argThat(..)).orElseGet(new MyEntity())).thenReturn(..);
```

I believe it mimics the same behavior of primitives `xxxThat()` in which a dummy value is returned.

Is it possible to add the `argThat()` implementation like:

```java
public static <T> T argThat(ArgumentMatcher<T> matcher, Supplier<T> defaultValue) {
   reportMatcher(matcher);
   return defaultValue.get();
}
```
