### ISSUE TITLE
Update minimum support Java version from 8 to 11

### ISSUE THREAD

**Issue by reta** [mockito/mockito#2798]
Hello!

We [1] have been using Mockito with JDK's `SecurityManager` (for historical reasons), the things worked fine for us till Mockito `4.8.0` release (and later versions). The culprit is `Java9PlusLocationImpl` (see please stack trace below):

```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.Class.checkMemberAccess(Class.java:2847)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2471)
	at org.mockito.internal.debugging.Java9PlusLocationImpl.stackWalker(Java9PlusLocationImpl.java:191)
	at org.mockito.internal.debugging.Java9PlusLocationImpl.<clinit>(Java9PlusLocationImpl.java:50)
	... 47 more

```

By all means, `Mockito` should know nothing about `SecurityManager` and the way we implemented mocking under `SecurityManager`  is by using `Mockito`'s extensibility model - plugins (primary, `MockMaker`). Sadly for `LocationFactory` / `Location` there is no such plugin available so we are stuck on 4.7.x release line. If such plugin would have been available, we could provide privileged implementation for reflection calls. Alternatively, wrapping up Java 9 implementation into multi-release JAR (and getting rid of reflection), would have helped.

We are happy to submit the pull request with either solution, but it would be helpful to know if there is an interest addressing this issue in general, and preferred approach in particular:
   - plugin for `LocationFactory` / `Location`
   - multi-release JAR for Java 9

Thank you.

 - [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

[1] https://github.com/opensearch-project/OpenSearch

**Comment by raphw** [comment]
I think it's fair to move on to Java 11. Today Spring 6 arrived which baselines to Java 17, we are not even on the edge of things with this in mind, so thumbs up for bumping to 11.

**Comment by reta** [comment]
@raphw that's unexpected win-win outcome :-), thanks @TimvdLippe for this 3rd option, I can take it (under new issue) if no one is working on it at the moment.

**Comment by TimvdLippe** [comment]
I filed #2802 to consolidate the changes for Mockito 5. For this issue, we will need to:

- [ ] Bump our minimum Java version to 11 specified here: https://github.com/mockito/mockito/blob/0ce902af967cca91cb9ff2beaac95e44406bd175/gradle/java-library.gradle#L17-L18
- [ ] Additionally, we can look into remove our JavaDoc hack (https://github.com/mockito/mockito/tree/main/gradle/mockito-core/java-8-docs) which effectively reverts #2766
- [ ] We need to update our version of JavaDoc here: https://github.com/mockito/mockito/blob/0ce902af967cca91cb9ff2beaac95e44406bd175/gradle/mockito-core/javadoc.gradle#L48
- [ ] Remove 8 from our build matrix: https://github.com/mockito/mockito/blob/0ce902af967cca91cb9ff2beaac95e44406bd175/.github/workflows/ci.yml#L32
- [ ] Update all matrix checks to run on 11 instead: https://github.com/mockito/mockito/blob/0ce902af967cca91cb9ff2beaac95e44406bd175/.github/workflows/ci.yml#L51
- [ ] Remove all checks in `.gradle` files that check for Version 8 explicitly: https://github.com/mockito/mockito/blob/0ce902af967cca91cb9ff2beaac95e44406bd175/subprojects/module-test/module-test.gradle#L5
- [ ] Remove all checks in `.gradle` files that check if we are Java 9 compatible: https://github.com/mockito/mockito/blob/0ce902af967cca91cb9ff2beaac95e44406bd175/subprojects/inline/inline.gradle#L17

We can clean up the source code in `src/main/java` to remove all reflection usages (and thus solve this ticket) in Mockito 5.1.0. I would prefer to make it a clean cut first, so that upgrading is relatively straightforward. Then fixes go in a minor release, so that we can catch regressions separately.

Let me know if you think I missed something. I would welcome some PRs to get these fixed!
