### ISSUE TITLE
NPE when explicitly casting a deep stub

### ISSUE THREAD

**Issue by Pr0methean** [mockito/mockito#289]
In an Android test, I needed my mock Context to return a mock ActivityManager. I tried this:

```
import android.app.ActivityManager;
import android.content.context;
/*...*/
@Mock Context context;
/*...*/
when(((ActivityManager) mContext.getSystemService(Context.ACTIVITY_SERVICE)).isLowRamDevice()).thenReturn(false);
```

This produced a NullPointerException in the when() call.

**Comment by JeremybellEU** [comment]
I think this is happening because `(ActivityManager) mContext.getSystemService(Context.ACTIVITY_SERVICE)` returns `null` as it was not previously stubbed. However you might have done it in left-out code.

Then you execute `.isLowRamDevice()` on this `null` which generates the `NullPointerException`.

To (presumably) fix this issue, you have to stub `getSystemService` to return a valid object, preferably a mock. Then you can execute `when(mockedActivitymanager.isLowRamDevice()).thenReturn(false)`.

**Comment by raphw** [comment]
Closing this as it seems resolved.
