### ISSUE TITLE
Mockito java8 distribution

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#297]
There's an open source java8 feature set for mockito developed by Marcin Zajączkowski, see: https://solidsoft.wordpress.com/2015/06/30/more-compact-mockito-with-java-8-lambda-expressions-and-mockito-java8-add-ons

Let's figure out a way to include this in main distribution of Mockito

Discussions on this subject on the dev list: 

1) https://groups.google.com/forum/#!searchin/mockito-dev/java8/mockito-dev/pBb0Pv6x_7E/Sz8WIew6OK8J
2) https://groups.google.com/forum/#!searchin/mockito-dev/bytebuddy$20plan/mockito-dev/dG2KltOz-gQ/VG4B5wcRL0AJ

This story needs to be scoped out. Main challenge: how do we offer java8 features with Mockito distribution and yet provide compatibility to users on java version < 8

**Comment by JeremybellEU** [comment]
Not sure if it is possible, but could Java 8 specific features be directed to a seperate module. Therefore the 'old' module supports Java <8 and the new + old module support Java >8. I am not even sure if it is able to be compiled.

**Comment by szpak** [comment]
The current features can be (and in fact are) simply integrated as a separate mockito-java8 module.

Although I cannot provide a particular feature in Mockito a case study from AssertJ. Long time ago I started implementing AssertJ module for Java 8. It turned up quickly that due to complex class hierarchy of assertions it was not possible to add a new class Assertions8 which depends on a standard Java 7 Assertions class and also allows common subclasses from Java 7 to rely on it (Assertions8). Everything ended up as a separate branch with different version number (assertj-core 2.x and 3.x).

Mockito has quite different internal structure, but in my opinion the key question is of there are known features which woudn't be able to be implemented as an add-on module? What API limitation would a separate module approach bring?

**Comment by szczepiq** [comment]
@szpak, can we have mockito-java8 __1.0__? There seems to be no big changes going on, you already are backwards compatible as you know well enough the power of server, lets do 1.0. This way, we can deemphasize java8 support.

I guess the the goal of this ticket is to pull in @szpak module into mockito codebase (and bring new fantastic team member along ;p). Since mockito-java8 is can be neatly used right now, there is no urgency on this.

**Comment by bric3** [comment]
I definately would like to have java 8 only distribution. If you look at java 9 big changes this will make sense due to the modular system where mockito will probably need to be able to work with the module system [JEP 261](http://openjdk.java.net/jeps/261).

And I'm not sure we want to do multi-release JAR files (understand java 8 / java 9 jars) [JEP 238](http://openjdk.java.net/jeps/238)

**Comment by TimvdLippe** [comment]
++ for Java 8 distribution of Mockito. A lot of Mockito code can also be cleaned up with use of lambda's and Streams.

**Comment by bric3** [comment]
I'm also in favor of macking Mockito 2 java 8 only.

**Comment by vanniktech** [comment]
I'm against Mockito 2 being Java 8 only, the complete android side which is still stuck on Java 6 would then be lost and could not use Mockito 2.

**Comment by bric3** [comment]
Mockito 1.x is already available on android.
IMHO we cannot withhold improvements just because Android, especially since there's an alternative that works with well already.

**Comment by szpak** [comment]
For me personally it would be probably ok to drop support for Java 7 even in Mockito 2.x. Nevertheless there is a group of libraries (e.g. probably all Spring related things) that still support Java 7. It slows down abandoning Java 7 by end projects, but the fact is that they exist, so I have slightly different proposal.

As the current Mockito 2 codebase is Java 7 compliant and there is a set of new features maybe it would be good to release 2.0-final soon (the end of the year is soon - even in a scope limited to original plans). It would give a stable version to all who got stuck with Java 7. Then Mockito 2.x branch would be switched to maintenance mode and the code from master could be cleaned up and extended with Java 8, followed by  immediately releases of Mockito 3.0.0-beta versions.

Assuming a small number of changes (critical fixes only) in Mockito 2.x branch the main issue would be probably releasing 2.x versions on demand (3.x could be releases automatically if the mechanism was fixed, but I don't know how hard would be to add support for releasing two lines of code).

**Comment by TimvdLippe** [comment]
If there is enough confidence Mockito 2.0 is stable, I agree with @szpak to immediately switch to Java 8 and create Mockito 3.0

**Comment by bric3** [comment]
OK let's do that

**Comment by bric3** [comment]
So we only have to work on matchers ([2.0 leftovers](https://github.com/mockito/mockito/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0))

**Comment by TimvdLippe** [comment]
:+1: Glad to see Mockito improving so fast the last couple of weeks, keep it up!

**Comment by mkordas** [comment]
:+1: for idea to release 2.0 final before end of this year and immediate switch to 3.0-beta afterwards.

**Comment by TimvdLippe** [comment]
Mockito 3 will require Java 8. What features @szpak we are missing the core library that your extension has? We do have improved compatibility with the new `AdditionalAnswers`, see #338

**Comment by szpak** [comment]
@TimvdLippe There are 3 main features available in mockito-java8 which I plan to backport *soon*:
 - Mockito API methods available via interfaces (without static imports)
 - Lambda matcher
 - Argument Captor - Java 8 edition

More [details](https://github.com/szpak/mockito-java8/#quick-start).

I also consider rewriting Java 8 default answers support from reflection to default calls.

**Comment by bric3** [comment]
@szpak cool thanks !

**Comment by wlsc** [comment]
Any news on this issue?

**Comment by TimvdLippe** [comment]
Java 8 is now fully supported and we support regular lambda's as `ArgumentMatcher` and friends.
