### ISSUE TITLE
Request to bring back support for Java 8

### ISSUE THREAD

**Issue by anuchandy** [mockito/mockito#2997]
With the recent release, the support for Java 8 is removed. 

Almost all the significant cloud libraries are still on Java 8 (due a large customer base). For example

[Azure SDK](https://github.com/Azure/azure-sdk-for-java#prerequisites), [GCP SDK](https://github.com/googleapis/google-cloud-java#java-versions), [AWS SDK](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html)

We can also see the [discussion](https://github.com/reactor/reactor/issues/705#issuecomment-1025976281) in Spring Reactor on whether to drop or keep Java 8 support. The decision was to support Java 8 for the next two years. Here is the extensive community [discussion ](https://github.com/reactor/reactor/issues/703) on the same.

With Mockito being one of the best mocking frameworks out there for Java, it's sad to see the removal of support for Java 8 when there are customers and libraries out there that still need to support Java 8 and uses Mokito. @TimvdLippe and team anychance we can bring back the support?

**Comment by TimvdLippe** [comment]
Since Mockito is a testing library, you can keep on using Mockito 4 if you require JDK 8 support. For any newer versions of JDKs, you can use Mockito 5 and onwards. As a mocking library, we need to carefully balance backwards compatibility with forwards compatibility. Mockito 5 droping Java 8 support was based on the fact that we had lackluster support for newer JDKs. Therefore, to support newer JDKs, we had to drop Java 8. Other Java libraries don't usually have such requirements, which is why I don't think they apply to us. For more information, see the rationale in the release notes: https://github.com/mockito/mockito/releases/tag/v5.0.0
