### ISSUE TITLE
.verify uses the state of reference at time of verification rather than value at time of invocation

### ISSUE THREAD

**Issue by alecswan** [mockito/mockito#343]
This has been reported on [StackOverflow](http://stackoverflow.com/questions/17027368/mockito-what-if-argument-passed-to-mock-is-modified) and the same problem persists in 1.10.16 version of Mockito.

**Comment by bric3** [comment]
Easymock can do that, because it declares the expectations _before_ the tested invocation. While we don't for better test readability.

To verify passed values, then it would require to duplicate each value graph, thus performing a deep copy. This would make tests slower, and may result in problems with exotic data structures.
