### ISSUE TITLE
Mocking static method does not work with CompletableFuture in different thread

### ISSUE THREAD

**Issue by FJiayang** [mockito/mockito#3438]
**Description**

I am trying to mock a static method using `Mockito` and test a method that returns a `CompletableFuture`. However, the mocked behavior is not applied when the method is called from a different thread.

**Reproducible Code**

Here is the code for the class I am testing:

```java
public class FileUtils {
    public static String getName(String name) {
        return name;
    }

    @SneakyThrows
    public static String asyncGetName(String name) {
        return CompletableFuture.supplyAsync(() -> getName(name)).get();
    }
}
```

The test case I wrote is as follows:

```java
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class FileUtilsTest {

    @Test
    public void test() throws ExecutionException, InterruptedException {
        try (MockedStatic<FileUtils> fileUtils = Mockito.mockStatic(FileUtils.class)) {
            fileUtils.when(() -> FileUtils.getName(Mockito.anyString()))
                     .thenReturn("test");

            String name = FileUtils.asyncGetName("name");
            assertEquals("test", name); // Expected output: "test" , actual output "null"
        }
    }
}
```

Issue Details

When running the test, the output is null instead of "test". This seems to be because the getName method is called from a different thread than the one where the mocking was set up.

Environment

Java Version: jdk1.8.0_202
Mockito Version: 4.13.2
Question

Is there a way to make the mocked behavior apply to calls made from a different thread without modifying the production code?

**Comment by AKDaksH** [comment]
When mocking a class with Mockito, it's crucial to understand that unstubbed method calls will return default values. For methods returning objects, this default value is null.

In your test case, you've mocked the FileUtils class but haven't specified any behavior for the asyncGetName method. Consequently, calling this method will result in null.

usually, in this scenario, partial mocking approach should be used.
eg : fileUtils.when(() -> FileUtils.asyncGetName(Mockito.anyString())) .thenCallRealMethod();

However, this approach is ineffective in this scenario because you're mocking the static method you're simultaneously trying to test within the same class. This creates a circular dependency.

I will try to find a suitable solution for testing this specific scenario requires a deeper analysis of the code and its dependencies. I'll continue exploring potential solutions and provide an update when I have a viable approach.

**Comment by AKDaksH** [comment]
Hi

Your problem here is describing a scenario where you want to test a method (method2) that depends on another method (method1) within the same class. This is where partial mocking comes in handy.

However, traditional mocking frameworks like Mockito are designed to mock external dependencies, not methods within the same class. To achieve this, you'd typically refactor your code to make method1 injectable or overridable.

Let's illustrate with an example:


public class ClassA {

    public boolean method1() {
        // Incomplete or complex logic
        return false; 
    }

    public String method2() {
        boolean result = method1();
        return result ? "Success" : "Failure";
    }
}



Refactored with Dependency Injection:

public class ClassA {

    private final Dependency dependency;

    public ClassA(Dependency dependency) {
        this.dependency = dependency;
    }

    public boolean method1() {
        return dependency.doSomething();
    }

    public String method2() {
        boolean result = method1();
        return result ? "Success" : "Failure";
    }
}

interface Dependency {
    boolean doSomething();
}


Test with Mocking:

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class ClassATest {

    @Test
    public void testMethod2() {
        Dependency mockDependency = mock(Dependency.class);
        when(mockDependency.doSomething()).thenReturn(true); // Mock method1's behavior

        ClassA classA = new ClassA(mockDependency);
        String result = classA.method2();

        assertEquals("Success", result);
    }
}

**Comment by FJiayang** [comment]
> Hi
> 
> Your problem here is describing a scenario where you want to test a method (method2) that depends on another method (method1) within the same class. This is where partial mocking comes in handy.
> 
> However, traditional mocking frameworks like Mockito are designed to mock external dependencies, not methods within the same class. To achieve this, you'd typically refactor your code to make method1 injectable or overridable.
> 
> Let's illustrate with an example:
> 
> public class ClassA {
> 
> ```
> public boolean method1() {
>     // Incomplete or complex logic
>     return false; 
> }
> 
> public String method2() {
>     boolean result = method1();
>     return result ? "Success" : "Failure";
> }
> ```
> 
> }
> 
> Refactored with Dependency Injection:
> 
> public class ClassA {
> 
> ```
> private final Dependency dependency;
> 
> public ClassA(Dependency dependency) {
>     this.dependency = dependency;
> }
> 
> public boolean method1() {
>     return dependency.doSomething();
> }
> 
> public String method2() {
>     boolean result = method1();
>     return result ? "Success" : "Failure";
> }
> ```
> 
> }
> 
> interface Dependency { boolean doSomething(); }
> 
> Test with Mocking:
> 
> import org.junit.jupiter.api.Test; import static org.junit.jupiter.api.Assertions.assertEquals; import static org.mockito.Mockito.*;
> 
> public class ClassATest {
> 
> ```
> @Test
> public void testMethod2() {
>     Dependency mockDependency = mock(Dependency.class);
>     when(mockDependency.doSomething()).thenReturn(true); // Mock method1's behavior
> 
>     ClassA classA = new ClassA(mockDependency);
>     String result = classA.method2();
> 
>     assertEquals("Success", result);
> }
> ```
> 
> }

This is indeed a new perspective, and it's useful for me. Thank you.
