### ISSUE TITLE
@Mock-annotated fields are null for inner test classes (e.g. when using junit-hierarchicalcontextrunner)

### ISSUE THREAD

**Issue by UrsMetz** [mockito/mockito#353]
Using the two current versions of Mockito (1.10.19 and 2.x-beta) and the JUnit-Mockito-Rule together with JUnit extensions like [junit-hierarchicalcontextrunner](https://github.com/bechte/junit-hierarchicalcontextrunner/) that use inner classes causes fails with `NullPointerException`s:
```java
@RunWith(HierarchicalContextRunner.class)
public class HierarchicalMockitoTest {
    @Rule
    public MockitoRule mockitoRule = MockitoJUnit.rule();

    @Mock
    private Runnable runnable;

    public class Context {
        @Test
        public void test() throws Exception {
            runnable.run();
        }
    }
}
```

With older 1.x versions that didn't not contain the new JUnit rule API (e.g. where `MockitoJUnitRule` was not deprecated yet) the above test pass. I guess the reason is that the old rule's constructor had the current test instance passed in. In newer versions the rule uses the `target` from `org.junit.rules.MethodRule#apply()` which in this example is an instance of `HierarchicalMockitoTest.Context` so the `@Mock`-annotated fields of the outer classes are not seen and the mocks won't get instantiated.

**Comment by bric3** [comment]
@UrsMetz This is not yet supported, feel free to craft a pull request for that ;)

**Comment by UrsMetz** [comment]
@bric3 I will take at pull.

Maybe it was not clear from my original post: This is a regression because when updating to the latest 1.x release tests like the one above will fail: when though the constructor of `MockitoJUnitRule` gets the target (e.h. `this`) passed it doesn't use it in the newest version and as a consequence the test fails with a `NullPointerExeception`. Earlier version used the parameter so that the mocks got initiated and the test was green. So even when the old now deprecated API is used tests start to fail after updating Mockito. So maybe a back port to the 1.x branch should be considered too?

**Comment by bric3** [comment]
Oh I didn't get that indeed. Actually the this was removed because JUnit passes the target when the rule is applied see [MockitoJunitRule](https://github.com/bric3/mockito/blob/master/src/main/java/org/mockito/junit/MockitoJUnitRule.java#L39-L39). With these _exotic_ JUnit runners I'm not sure how to solve this in a proper way, maybe adding a hierarchical mockito rule.

**Comment by bric3** [comment]
Or maybe with such exotic runner, the PR could be on their project ? https://github.com/bechte/junit-hierarchicalcontextrunner/

**Comment by UrsMetz** [comment]
I was also thinking whether it is not a issue with the junit-hierarchicalcontextrunner. I will investigate this and either raise an issue over there (and reference this issue) or take a stab at a fix and pull request for Mockito. I'm not one hundred sure whether it worked in all corner case with the old version where the parameter of `MockitoJUnitRule` was used instead of the parameter `target` of the `apply` method of the rule. I will also look into that.

**Comment by UrsMetz** [comment]
@bric3 After playing a bit around with the example above and different versions of Mockito (pre 1.10.17 where the internal implementation of the JUnit rule changed and >= 1.10.17) I figured out that only some corner cases worked in the old version (exactly those we are using right now in my team at work); now different case work and the old cases stopped working. As you said it seems to be an issue with junit-hierarchicalcontextrunner. I raised the issue bechte/junit-hierarchicalcontextrunner#26 over there.

**Comment by bric3** [comment]
@UrsMetz Cool if you're ok with that let's close the issue there ?

**Comment by UrsMetz** [comment]
Sure, I'm closing it.

**Comment by bric3** [comment]
Cool thanks :)

**Comment by mouyang** [comment]
The HierarchicalMockitoTest fails even with @UrsMetz's fix for [bechte/junit-hierarchicalcontextrunner#26](https://github.com/bechte/junit-hierarchicalcontextrunner/issues/26).  Since a new version of the dependency has not been released, the test failure can be demonstrated by following the steps below (after a new version of the dependency has been released, building my feature branch will be sufficient):

1. Build and install (requires Maven) https://github.com/bechte/junit-hierarchicalcontextrunner/tree/master.  This pulls in @UrsMetz's fix with a version 4.12.2-SNAPSHOT.
1. Clone https://github.com/mouyang/mockito/tree/mouyang-gh-353.  In build.gradle, change [this line](https://github.com/mockito/mockito/compare/release/2.x...mouyang:mouyang-gh-353?expand=1#diff-c197962302397baf3a4cc36463dce5eaR81) to `testCompile 'de.bechte.junit:junit-hierarchicalcontextrunner:4.12.2-SNAPSHOT'` to match the artifact produced previously.
1. `./gradlew build` as-is results in a pass.
1. `./gradlew build` with my change to JUnitRule reverted results in HierarchicalJUnitRuleTest.java failing due to the UnfinishedMockingSessionException I cited previously.

This issue would have happened with any Runner that enabled hierarchical test classes ([such as the NitorCreations NestedRunner](https://github.com/NitorCreations/CoreComponents/tree/master/junit-runners)).  JUnitRule overwrites the MockitoSession instantiated in the outer call in the nested case; this seems wrong and it seems reasonable to augment the existing session with the mocks from the inner class.

I haven't submitted a PR at this time, eventhough the test suite passed, because I have no idea if my changes are oblivious to other exception cases.  But I would like to re-open a discussion on this ticket since I still believe this is a legitimate issue.  Thanks.

**Comment by UrsMetz** [comment]
@mouyang I had a quick look at it (I don't know why but I had to tweak `gradle.build` in your repo a bit further so that the `junit-hierarchicalcontextrunner` SNAPSHOT version in my local Maven repository was found as a `testCompile` dependency: I had to add a top level `repositories` section with `mavenLocal()` in it).

I can reproduce your error when using some 2.x versions of Mockito (I tried 2.13.0, 2.1.0-beta.125, and the master).
With a Mockito version 1.x and 2.0.0-beta.118 I cannot reproduce the failure.
So at the time when I was working on this it worked(tm) ;-), but with the current 2.x version it is broken. So I think you're right that there is an issue (please note that I'm not a maintainer of Mockito. I just saw that there was some activity on an old issue I once created).

**Comment by mouyang** [comment]
From your clarifications it makes more sense to keep this ticket closed, and for me to create a new ticket for my issue as it is clearly different. Thanks @UrsMetz!
