### ISSUE TITLE
Mockito JAR is not a valid OSGi bundle because illegal version format

### ISSUE THREAD

**Issue by SourcePond** [mockito/mockito#383]
Hi,

The current Mockito JAR is not a valid OSGi-bundle because it uses an illegal version for exporting its packages. I get the following error when I run my PAX-EXAM tests with the latest Mockito version:

org.ops4j.pax.exam.TestContainerException: Problem starting test container.
Caused by: org.osgi.framework.BundleException: Could not create bundle object.
Caused by: java.lang.IllegalArgumentException: invalid version "2.0.44-beta": non-numeric "44-beta"
Caused by: java.lang.NumberFormatException: For input string: "44-beta"

The version should be **2.0.44.beta** (with a dot instead a dash). This is since 2.0.28-beta, the last valid bundle was 2.0.27-beta.

**Comment by szczepiq** [comment]
Can you help us out? If you build locally a regular version, e.g. 2.1.0 or something (version can be changed in 'version.properties' file), you can test it out locally and let us know.

I think I will not change the -beta notation now but I take the feedback will update the automation after 2.x final release.

THANKS for reporting!

**Comment by seanrohead** [comment]
We are having the same problem. This was working in 2.0.27-beta and was broken in 2.0.28-beta. Why are you not planning to fix it until the final release?

**Comment by szczepiq** [comment]
I'm sorry the changes in beta are causing troubles!

In order to be able to maintain and evolve the code base, we had to start using latest OSGi Gradle plugin (we couldn't sustain using ant-based manifest generation that was 5 years old and coupled us with ant). We do not use OSGi and rely on the external contributors to fix any problems with the bundle.

I'd love to fix this problem ASAP - we need help from you to make it happen.
