### ISSUE TITLE
Mocking Class that inherits from Abstract class in a different JAR doesn't override methods

### ISSUE THREAD

**Issue by trasa** [mockito/mockito#398]
Here's a full description of the issue that I came across today:
http://stackoverflow.com/questions/36725689/mocking-hystrixobservablecommand-results-in-real-toobservable-getting-called

In summary: I have a `Foo`, it inherits from `abstract class SomeOtherJarClass<T>`, which implements `public void doThing()`.  

I want to mock(Foo.class), supplying my own answer for doThing(). 

However, the original SomeOtherJarClass.doThing() implementation gets called by the test no matter what. 

A workaround: I create a package-local `BaseClass extends SomeOtherJarClass<T>` and have Foo inherit from that, instead. And now mocking works as it should. 

Is this a known issue? Just the way the JVM rolls?

This is using mockito 1.10.19.

**Comment by raphw** [comment]
Could you try with a recent beta? We change the byte code generation and this would give us a hint if it is the code generation that is the problem.

**Comment by trasa** [comment]
I changed the mockito version to 2.0.48-beta and changed nothing else. The 'previously working' tests now fail with:

    java.lang.IllegalAccessError: tried to access class com.netflix.hystrix.AbstractCommand from class com.example.LoginWithEmailCommand$MockitoMock$225546493

**Comment by raphw** [comment]
If I guess, then your methods are defined in a package-private type. Is that correct?

**Comment by trasa** [comment]
The AbstractCommand<R> is package-private, correct. And that is where our problematic toObservable() method is implemented.

This class is extended by a public abstract class in hystrix-core-1.5.1.jar and extended further in my local project 'BaseCommand' with the empty-override for toObservable(). That hack worked in Mockito 1.10 but as-is does not work with Mockito 2.

**Comment by raphw** [comment]
I just looked into it and the problem is that Byte Buddy resolves the methods to the overridden instances by looking them up via the reflection API. In order to speed this up, Byte Buddy uses a constant pool reference to the declaring (but non-visible) class. This causes the illegal access error. Thanks for reporting, I am fixing this some time soon.

But to answer your question: It did not work with cglib but Byte Buddy works around this limitation. In many cases that does work but in this particular case, you found a bug. I hope to update Mockito this week and you should be able to do what you are doing without any workarround once the update is released.

**Comment by trasa** [comment]
Excellent, thank you!

**Comment by raphw** [comment]
Should work with beta 50. Please reopen the ticket if it does not.
