### ISSUE TITLE
JUnit runner and Rule should detect unused mocks

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#405]
This is a follow up of
-  #401 _"JUnit runner detects unused stubs"_ 
-  #384 _"JUnit rule on test failure logs warnings about unsued / misused stubs"_

It would be good to have warning log's for unused mock objects. If a developer knows unused mock he/she can remove them, this provides test clarity. 

Sample test with unused mock of type `Foo`:

```
43  @Test
44  public void testFoo(){
45     Foo foo = mock(Foo.class);
46     Bar bar = mock(Bar.class);
47     foo.doSomething();
48  }
```

Sample Log-Message: Should be IDE friendly so dev's can click on the stack-element to navigate to line of the mock creation:

```
[WARNING] unused mock of type "Bar" was instantiated
 at org.blah.blub.FooTest.test(FooTest.java:46) 
```

**Comment by szczepiq** [comment]
I think it is a great idea but how do we detect unused mocks? What if the mock is a 'dummy' object, created just to satisfy some != null conditional?

**Comment by ChristianSchwarz** [comment]
I agree, the IDE should take care of unused variable's

The alternative could be to generate a info message:
```
[INFO] No interaction detected with mock of type "Bar". It may possibly be removed
 at org.blah.blub.FooTest.test(FooTest.java:46) 
```

**Comment by ashleyfrieze** [comment]
Would it make sense to log if a method on a stub, prepared by when, is never called in that way?

This takes us into the realms of old school dynamic mocks where you set expectations and then verify all at the end.

**Comment by bric3** [comment]
This could be part of the JUnit rule

**Comment by szczepiq** [comment]
> The alternative is to log a info message if no mock method was reverenced. With this info dev's can check manually if the mock is unused. Thats better than nothing.

Interesting. We could try adding this warning and see if users like it. In general, I'm not a fan of warnings that cannot be 'fixed'. Reason: people stop caring about warnings :)

**Comment by ChristianSchwarz** [comment]
A different approach is to solve this issue at compile time using a [javac plugin](https://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/com/sun/source/util/Plugin.html), an IDE plugin or an FindBugs extension. 
An IDE-plug in would be awsome cause it would allow auto correction, auto refactoring from version 1.x -> 2.x -> 3.x,  you name it....

**Comment by ashleyfrieze** [comment]
Let's imagine that the whole thing exists for a second. What if you did this:


````
@RunWith(MockitoJUnitRunner.class)
@VerifyUnusedMocks
public MyTest {
    @Mock
    private Foo mockFoo;

    @Mock
    @IgnoreUnused
    private Bar bar;

    private FuzzService service = new FuzzService();

    @Test
    public void expectsFooToBeUsed() {
       // bar is just a dummy and won't get called
       service.doSomething(foo, bar);
    }

    @Test
    public void testingSomethingWhereFooIsntUsed() {
        service.doSomethingElse();

        // bar can be left unusued
        // foo should be unused - by verifying it, we tell the rule that tries to prove it wasn't used
        // not to run - we also set the expectation that foo should NOT have been used in this situation
        verifyUnused(foo);
    }

}

// without MockitoJUnitRunner you could have
verifyUnused(bar);
verifyWasUsed(foo);
````

The above is just a thought experiment. If people like it, maybe the next step is to have a go at making it...?

**Comment by szczepiq** [comment]
Yeah, I was thinking about adding some API to detect unnecessary stubbings. For now (2.0), I'll settle for new behavior of JUnit rule & the runner. Down the road, it would be nice if we offered this feature for people who don't use the rule/runner. Not sure about the API, though.

**Comment by imod** [comment]
We think about migrating from EasyMock to Mockito, but as described in this SO Question: http://stackoverflow.com/questions/25564154/mockito-how-to-identify-unused-when-in-tests we fear to have unused stubs and mocks - specially over time, when refactoring happen...
So I guess the feature described here would be very helpful.

My expectation would be, that if I have something like this:

```
given(sns.doXX(any(MyClass.class))).willReturn(response);
given(repository.save(any(MyEntity.class))).willAnswer(returnsFirstArg());

// run test
service.execute();

verifyAllMocksHaveBeenCalled(); // I expect this call to verify that the two 'given(...)' have been called during test.
```

**Comment by szczepiq** [comment]
I'm very happy that you're considering Mockito for your project!!!

This is really good feedback. Thanks!

1. We do not recommend strict mocking by default because it has negative effect on overall quality of tests.
2. In order to mock strictly, you can create a JUnit rule for your codebase (or a base class with setup() method). There, you can use APIs like: verifyNoMoreInteractions(), verifyNoMoreInteractions(ignoreStubs()), MockCreationListener for getting hold of all the mocks.
3. In order to detect unused stubs, currently the best way is to use the JUnit runner (JUnit rule only emits a warning).
4. The implementation of strict mocks is in progress: #649 

I will think through your feedback and formulate a proposal for further API improvements. Perhaps MockitoRule.strict() method for strict mocking with JUnit?

Thanks again for taking the time and providing us with the feedback!

**Comment by ashleyfrieze** [comment]
Forgive this question, but I thought that the above behaviour was IN Mockito 2.

From https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2

> Mockito JUnit runner and rule can now detect unused stubs. It is possible to revert this behaviour.

```
// detect unused stubs
@RunWith(MockitoJUnitRunner.class)

// don't detect, old behaviour
@RunWith(MockitoJUnitRunner.Silent.class)
or with the rule

// detect unused stubs
@Rule public MockitoRule mrule = MockitoJUnit.rule();

// don't warn user about misusage, old behaviour
@Rule public MockitoRule mrule = MockitoJUnit.rule()
                                             .silent();
```

Have I misunderstood the above?

**Comment by imod** [comment]
thanks!

Just be clear, I'm not really asking for strict mocking - I only wanna make sure the mock calls I defined with e.g. `given(...)` are really used, but there might very well be any other methods called on the mock object. I wanna make sure there are no methods mocked/stubed that I don't even call in the given test. 

Thanks for the hint about the JUnit runner, but we need to use the `SpringRunner` already, so that makes it a bit harder.

**Comment by TimvdLippe** [comment]
@imod If you use the default Mockito runner (or rule, so you can use `SpringRunner`!), it will fail if a stub was not used in a test. E.g.:

```Java
@Before
public void setup() {
  when(mock.call1()).thenReturn(...)
  when(mock.call2()).thenReturn(...)
}

@Test
public test_that_only_invokes_call1() {
  subject.doSomethingThatOnlyInvokesCall1()
  verify(mock).call1()
}
```

This test will fail since the stub of call2 was not invoked.

**Comment by imod** [comment]
@TimvdLippe I know, this works, but I really don't wanna do a `verify(...)` for each of the method mocks/stubs I created two lines above. This seems like a saying the same thing twice in about 5 lines of code. I would like to have this done automatically or at most one call that does test all mocks.

**Comment by TimvdLippe** [comment]
Okay the confusion is probably that there are two different mechanics going on here. My example was probably also confusing in that respect.

First of all: stubs that are not invoked are now by default reported. E.g. if a stub was invoked on a mock during a regular invocation on the subject, it will be fine. If the stub was not invoked at all, it will throw a failure.

Secondly: verification usually happens on methods that are not stubbed. This is where my example was probably confusing.

In other words: verify that a certain method is invoked. Stub when you need to return something. If a stub was not invoked -> test fails. If a method you are verifying has not been invoked -> test fails.

```java
@Before
public void setup() {
  when(mock.call1()).thenReturn(...)
}

@Test
public test_that_only_invokes_call1() {
  subject.doSomethingThatOnlyInvokesCall1()
}
```
This test succeeds.

```java
@Before
public void setup() {
  when(mock.call1()).thenReturn(...)
  when(mock.call2()).thenReturn(...)
}

@Test
public test_that_only_invokes_call1() {
  subject.doSomethingThatOnlyInvokesCall1()
}
```
This test fails

**Comment by imod** [comment]
@TimvdLippe do you have a full example of your last post? I really don't get this stuff to fail as you describe it :(

**Comment by szczepiq** [comment]
>This seems like a saying the same thing twice in about 5 lines of code. I would like to have this done automatically or at most one call that does test all mocks.

I agree. We plan to address it with #303

**Comment by szczepiq** [comment]
I'll close the ticket because I don't see a clean way of detecting truly unused mocks.

**Comment by imod** [comment]
@szczepiq really? well, thats at least a clear statement for us to stay on easymock...

**Comment by ChristianSchwarz** [comment]
At least logging potential unused mocks should be possible.

**Comment by ashleyfrieze** [comment]
@imod - can you provide a snippet of what you're currently doing in EasyMock. I'm pretty sure Mockito 2 already supports it, but at least, if we convert it across to Mockito syntax we can see the gap.

As a previous user of EasyMock, I can safely say, I'd never go back and use it!

**Comment by szczepiq** [comment]
@imod, @ashleyfrieze, I closed this ticket because "detecting unused mocks" is something we cannot cleanly implement. This ticket sidetracked into a different problem - boilerplate code when verifying stubbed invocations (see https://github.com/mockito/mockito/issues/405#issuecomment-260749592). The latter use case is currently addressed with "strict stubbing" feature. See the [blog post](http://blog.mockito.org/2017/01/clean-tests-produce-clean-code-strict.html) or the [Javadoc](https://static.javadoc.io/org.mockito/mockito-core/2.7.2/org/mockito/Mockito.html#40).

@imod, can you check out strict stubbing API? It eliminates the need to verify stubbed invocations.

@ChristianSchwarz, you are right we could log unused mocks using some kind of warnings. If you are interested in this feature, do you want to create a separate ticket and put together a design note?

**Comment by imod** [comment]
@ashleyfrieze 

here is an example:

```
	@Mock
	private IntercomService intercomService;
	@Mock
	private SalesforceService salesforceService;

	@Test
	public void userMustBeUpdatedWhenRequested() {

		UserDto userDto = new UserDto(new CorporateUserAccount("me@mail.com", "n/a"));
		CommandXEvent event = new CommandXEvent(userDto);

		intercomService.createOrUpdateUser(isA(UserDto.class), isNull());
		expect(salesforceService.createOrUpdateContact(isNull(), isA(UserDto.class))).andReturn("salesforce-contact-id");

		replayAll();
		handler.onCommandXEvent(event);
		verifyAll();
	}
```

This is a very simple example, but the essence of it is, that my test cases fails when my expected service calls are not done, or if more then these service calls are done on the mocks.

@szczepiq I will try again, but if this is the same as @TimvdLippe described above, then I fear I will have the same question again: how can I make his example fail?

**Comment by szczepiq** [comment]
@imod, here's Mockito equivalent of your EasyMock code sample:

```java
	@Rule public MockitoRule mockito = MockitoJUnit.rule().strictness(Strictness.STRICT_STUBS)
	
	@Test
	public void userMustBeUpdatedWhenRequested() {
		//given
		UserDto userDto = new UserDto(new CorporateUserAccount("me@mail.com", "n/a"));
		CommandXEvent event = new CommandXEvent(userDto);

		given(salesforceService.createOrUpdateContact(isNull(), isA(UserDto.class))).thenReturn("salesforce-contact-id");

		//when
		handler.onCommandXEvent(event);
		
		//then
		verify(intercomService).createOrUpdateUser(isA(UserDto.class), isNull());
		verifyNoMoreInteractions(intercomService, salesforceService);
	}
```

**Comment by imod** [comment]
@szczepiq many thanks! 
what I don't get by this example, is that I have to call `verifyNoMoreInteractions(...);` I already defined all the calls I expect and the rule is defined as strict - this should be clear enough from my PoV

**Comment by szczepiq** [comment]
The discussion seems to have moved to https://github.com/mockito/mockito/issues/1097 but I feel that the thread needs a closure ;)

>what I don't get by this example, is that I have to call verifyNoMoreInteractions(...); I already defined all the calls I expect and the rule is defined as strict - this should be clear enough from my PoV

The reason you need to call 'verifyNoMoreInteractions' is because "strict stubs" is not all mighty "strict all". Strict stubs does not verify that nothing else happens besides stubbing which is what you seem to want :) Strict stubs ensures that:
 - declared stubs are called
 - typos/bugs in stubbing are detected earlier
 - declared stubs are implicitly verified (so that you don't have to repeat "verify" for them in case you use verifyNoMoreInteractions

What you are after seems to be "strict mocks" mode so that your Mockito experience is similar to EasyMock. Discussion about this feature request is here: https://github.com/mockito/mockito/issues/1097 

Mockito is different library that EasyMock. We don't want to offer EasyMock strict style under a veneer of Mockito sweet API. We believe that strict mocking is bad for the codebase in the long run. However, we are open to offer and opt-in strictness level that is stricter than current. Please contribute: https://github.com/mockito/mockito/issues/1097
