### ISSUE TITLE
Verification fails when arguments passed to mocked methods are modified

### ISSUE THREAD

**Issue by austinmoore-** [mockito/mockito#406]
This is not exactly a bug but something odd that I ran into. While it's not incorrect, it is unexpected (in my opinion).

When a method is called on a mocked class, if the argument passed to the method is modified after the call, the verifications will fail. This is a bit odd to me because the method was actually called with that argument, and not with the modified argument that Mockito prints out when it fails.

Here's a test shows this behavior:

```java
public class MockitoExampleTest {

    class ClassA {
        ClassB classB;

        ClassA(ClassB classB) {
            this.classB = classB;
        }

        Set<String> doSomething(String element) {
            Set<String> set = new HashSet<>(Collections.singleton(element));

            set.addAll(classB.toBeMocked(set));

            return set;
        }
    }

    class ClassB {
        Set<String> toBeMocked(Set<String> arg) {
            throw new UnsupportedOperationException();
        }
    }

    @Test
    public void argumentTest() {
        ClassB mockedClassB = mock(ClassB.class);

        when(mockedClassB.toBeMocked(anySetOf(String.class)))
                .thenReturn(Collections.singleton("mocked"));

        Set<String> expectedResults = new HashSet<>(
                Arrays.asList(new String[]{"element", "mocked"}));

        ClassA classA = new ClassA(mockedClassB);
        Set<String> results = classA.doSomething("element");

        verify(mockedClassB).toBeMocked(Collections.singleton("element"));
        assertEquals(expectedResults, results);
    }
}
```

You can see that in `ClassA#doSomething(String)`, `ClassB#toBeMocked(Set<String>)` is called with a set that contains only `[element]`. Then Mockito mocks the return, which is added to the set, which is then returned. Now the set contains `[element, mocked]`, and the verification will now fail. I believe this is because Mockito keeps a reference to the argument, instead of copying it.

So I guess now, I'm wondering, is my assumption correct? Is there a way to change this behavior? If not, I'd also like to hear what other people's thoughts are about adding functionality that allows for you to specify that you want copies of the arguments, instead of references.

**Comment by raphw** [comment]
Mockito stores argument groups for invocations within maps internally. This is required to make something like the `times(...)` verification work. If you change the state of an object and therewith its hash code, Mockito cannot longer locate the argument within this map and the verification fails.

**Comment by mistercam** [comment]
I'm curious if this behaviour is present in the current version of Mockito (5.2 at the time of writing this.) Or are maps keyed off of hash codes still utilized to track argument groups?

**Comment by branch-whisperer** [comment]
This is definitely still happening, I spent at least an hour today on an issue caused by this. Here's a [minimal demo](https://github.com/branch-whisperer/mockito-collection-bug-poc).

Mockito will say that the method was called with a Collection containing the first value, which is not true. The value was added after the call. I've added an example workaround, but I think it's dirty. In my real world scenario I want to check that when there are two values a second call includes the first value in the Collection correctly, so using the "any" matcher would not be great.

High level suggestion: Mockito should keep record of passed Collection **classes** and their entries in a stable order (like a List) instead of keeping the Collections themselves. That way it should still be able to check for equivalency of method calls later but avoid failures due to modification.

**Comment by raphw** [comment]
The problem here is that anybody can implement a list with custom behaviour. We cannot, on a general basis, clone an object and expect it to retain its contract. This would already fail for objects with identity based equality, or methods that mutate the state within. If you want this behaviour, I would suggest to pass a copy already when specifying the matchers to a mock.

**Comment by branch-whisperer** [comment]
> The problem here is that anybody can implement a list with custom behaviour. We cannot, on a general basis, clone an object and expect it to retain its contract. This would already fail for objects with identity based equality, or methods that mutate the state within.

I'm not suggesting cloning the Collection, because then you might run into special or private constructors on the Collection. I'm suggesting storing that class and adding all of it's contents to a Collection that you control, like a new ArrayList. As for the Contract, I think it's true that the Collection interface leaves it up to each implementation to define their equals and hashCode implementations. But [List](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/List.html#equals(java.lang.Object)) and [Set](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Set.html#equals(java.lang.Object)) are very specific, they both make it clear and Lists and Sets are equal if are also Lists or Sets respectively, have the same size and all elements are equal. I linked to the documentation for convenience.

> If you want this behaviour, I would suggest to pass a copy already when specifying the matchers to a mock.

I think this is the most important part. **The issue is not on the matchers to a mock.** It happens in the business code. The business code modifies the List it passes to the mocked method after calling it, and when the Mock is verified at the end of the test it claims that it was called with a List containing the modified contents, not the contents that were actually passed when calling the Mock, which causes the test to fail.
I would need to modify the business code to copy Collections that they intend to pass to mock method calls during their tests. I tried to show that as clearly as possible on[ the demo](https://github.com/branch-whisperer/mockito-collection-bug-poc) I provided by creating both a working business method and a failing business method. The tests are identical.
I think Mocks should work reliably for anyone who is following the equals and hashCode contracts from Lists and Sets, and if someone does create a custom List or Set that violates that contract they should be the ones having to work around that when mocking, not everyone whose business code modifies a List or Set after passing it to a method that might be mocked during tests. I think it's a fair point that the behaviour should not be changed for Collections, since they make no such promises of behaviour.

**Comment by raphw** [comment]
This might however break code, if someone relies on the equality of identical collections, even after alteration. That's why I am not convinced that this is a good change. I think this can only be handled reliably by the user. I am however open to suggestion on how this can be made more obvious and/or convenient.

**Comment by branch-whisperer** [comment]
> more obvious

Maybe remember the Collection size, and if a mock verification fails (the "verify" method) or the unecessary stubbing message is triggered, check if the collection size was different and include that in the message?

> or convenient

I was looking at the Mockito docs. Maybe there could be another Mock settings, something like "Collection Equality Strategy", and the current strategy could be called something like "Collection equals" and a new type could be something like "Class and Iterables equal"?

I'm just throwing ideas, I don't know the code base all that well and I think my use of Mockito is very basic. But on a high level you could either note that the Collection's content has changed on error messages to help diagnose issues or let us pick how the Mock decides whether it was called with the configured parameter so that it does not fail in these situations.

**Comment by raphw** [comment]
I could consider adding matchers that copy a collection in a matcher, but this would likely be solved as easily with an explicit copy. I still don't think it's a good change, also since it favours a particular data type.

**Comment by branch-whisperer** [comment]
Maybe I'm not understanding what you mean by an explicit copy. Here's the failing test from the demo:
```
    @Test
    void thisTestShouldPassButDoesnt() {
        int firstInput = 2;
        given(importantService.isAcceptableHierarchicalInput(firstInput, new ArrayList<>()))
            .willReturn(true);

        boolean result = importantOperation.areInputsOkFails(List.of(firstInput));

        assert(result);
        then(importantService).should().isAcceptableHierarchicalInput(firstInput, new ArrayList<>());
    }
```
It's already receiving a new ArrayList on the configuration and on the verification.
I would have to change the business code itself and duplicate my Collection everytime I call the method just because during some tests it is mocked. This fails:
```
public boolean areInputsOkFails(SequencedCollection<Integer> inputs) {
        List<Integer> previousInputs = new ArrayList<>();
        for (Integer anInput : inputs) {
            if (!importantService.isAcceptableHierarchicalInput(anInput, previousInputs))
                return false;
            previousInputs.add(anInput);
        }
        return true;
    }
```

This passes: 
```
    public boolean areInputsOkWorkaround(SequencedCollection<Integer> inputs) {
        List<Integer> previousInputs = new ArrayList<>();
        for (Integer anInput : inputs) {
            if (!importantService.isAcceptableHierarchicalInput(anInput, new ArrayList<>(previousInputs)))
                return false;
            previousInputs.add(anInput);
        }
        return true;
    }
```

But again, this is code from the test package, it's from the main package.

**Comment by raphw** [comment]
If this is an ordering problem, I would implement a more flexible matcher as with `argThat(...)`.

**Comment by branch-whisperer** [comment]
"areInputsOkFails" calls "importantService.isAcceptableHierarchicalInput" with an empty list and adds an item to the list after the call, Mockito says the method was called with the list containing the item, says the mock wasn't used and that the method was called with a list containing an item (it wasn't).
The mock setup was correctly used, the test only fails because Mockito claims I passed it something different from what was actually passed.

**Comment by raphw** [comment]
I would use a spy for this, to be honest. Have you considered that?

**Comment by branch-whisperer** [comment]
The real mocked method calls the database through Hibernate. I just tried to create the simplest scenario possible that showed the behaviour that fails the test.
