### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#421]
There are 3 branches which are over 2 years old and I think they can be removed. @szczepiq @bric3 could you confirm? https://github.com/mockito/mockito/branches

**Comment by bric3** [comment]
I deleted the old travis branch, I don't think the previous work there is relevant anymore.
Also for other branches I think they can be deleted :

* `release` branch has only one commit on `.gitignore` that isn't in `master`. 
* `sf-spy-hack` do seem like an experiment that somehow led to actual feature now implemented since mockito 1.10x+ (the idea was to be able to mock abstract class). @szczepiq do you confirm ?

**Comment by TimvdLippe** [comment]
I have deleted these branches as they were unused. We can always restore if we want to at a later point.
