### ISSUE TITLE
ArgumentCaptor should be type aware

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#565]
Assume we have the following test.

```
 @Mock
 private Consumer<Collection<?>> consumer;

 @Test
 public void test() throws Exception {

    consumer.accept(new HashSet<>());
    consumer.accept(new ArrayList<>());

    ArgumentCaptor<ArrayList<?>> captor = ArgumentCaptor.forClass(ArrayList.class);
    verify(consumer).accept(captor.capture());
 }
```

The test fails with:

```
org.mockito.exceptions.verification.TooManyActualInvocations:
consumer.accept(<Capturing argument>);
Wanted 1 time:
-> at foo.TestClass.testName(TestClass.java:64)
But was 2 times. Undesired invocation:
-> at agh.TestClass.testName(TestClass.java:61)

    at foo.TestClass.test(TestClass.java:64)
    [..]
```

The problem here is that ArgumentCaptor is not type aware. That should be fixed.

This issue was extracted from #358 and relates to #439.

**Comment by bric3** [comment]
We are aware of that issue, the design of this tool is to rely on the method signature.

**Comment by szczepiq** [comment]
@ChristianSchwarz, guys any ideas how to improve it?

**Comment by ChristianSchwarz** [comment]
The `CapturingMatcher` can use the Class-Object passed to the `ArgumentCaptor` and capture only arguments that are instances of the expected type. This solution has a down side the captor still matches anything which may surprise users, here is an example:

```
stringArgs= ArgumentCaptor.forClass(String.class);
mock.call(123);
mock.call("abc");
verify(mock).call(stringArgs.capture()); //fails with too many invocations cause call(123) matches too.
```

If the `CapturingMatcher` matches only instances of the expected type then existing client tests may break. But if we go this way we  open a "can of worms™" cause `CapturingMatcher` implements `VarargMatcher` and there are many corner case that must be handled in `ArgumentsComparator`. I currently write regression tests to explore these. When I have more details I will post them here.

**Comment by terebesirobert** [comment]
@ChristianSchwarz Hi,
This seems to be related to #358. WDYT?

**Comment by ChristianSchwarz** [comment]
@terebesirobert 
> This seems to be related to #358. WDYT?

Absolutly, I splitted #358 cause it included two toppics:

1. adding a new captor API `captureIf( )`,still ticket #358
1. type safe capture, this ticket

I think your PR #358 can be used to fix this issue. Since the the new API captureIf(..) is not approved by the mockito-core-team I think it should be excluded for this issue. Maybe you can create a branch of your solution and send a new PR to fix this issue.

**Comment by bric3** [comment]
This work is not yet accepted because, we want to freeze new features for mockito 2.0, we will explore new API — thanks to @ChristianSchwarz  and others contributors — in version 2.1.

@ChristianSchwarz I'm eager to see what's possible to do. I'm leaning for a builder style API from the actual `ArgumentCaptor`. For annotations a reduced set of features might be added via either boolean and/or enum.

Also about type safety, let's keep in mind that Java 8 compiler can resolve type on a callsite. which is not available on previous java versions.

**Comment by paulduffin** [comment]
What is the status of this (or #358)?

**Comment by TimvdLippe** [comment]
Type-safety is still something I am investigating, targeting Mockito 3. It seems that fixing it without strong typing, e.g. dynamically checking the generics, is very hacky and error-prone. It would be nice to have a solution where the compiler can catch these issues and make sure the verification is working, rather than on run-time failing.

**Comment by adriangalera** [comment]
What's the status on that?
