### ISSUE TITLE
In javadocs and exception messages favor issue tracker over mailing list

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#575]
In javadocs and exception messages we often recommend using mailing list to reach out to the team. I think it's better to favor issue tracker instead. This way, users can track progress / update comments and all the goodness of managing conversations we cannot do with emails.

**Comment by bric3** [comment]
I do not agree, the mailing-list works well, there's still people watching the ML. And lots of messages sent over there are mockito usage issues (like I didn't read this part of the javadoc).
Also this will transform the issue tracker to a support issue tracker, and this will flood dev related work. Also the mailing-list allows triage.

Just look at what happened in one week-end :

<img width="1697" alt="screen shot 2016-08-22 at 10 39 20" src="https://cloud.githubusercontent.com/assets/803621/17848631/c9e6a032-6854-11e6-8864-b5d0bdd9d98c.png">


> This way, users can track progress / update comments and all the goodness of managing conversations we cannot do with emails.

Instead I'd rather redirect users to stackoverflow, which has an even more active community, which is eager to answer people in need. Bug report posted first on SO where reported to us because other members thought it was a bug.

**Comment by TimvdLippe** [comment]
I agree with @bric3 , let's keep the issue tracker for issues/feature requests and resort debugging matters to the mailing list/stackoverflow.

**Comment by szczepiq** [comment]
Thanks for feedback guys! I'll close this ticket, then.
