### ISSUE TITLE
Make manual release of Mockito versions possible

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#586]
The automatic beta publisher is nice, but sometimes we want to manually release an artifact. For example Mockito 2.0 or a release candidate.

For this we most likely need to fix the credentials to the maven central, which now only exist on Travis.

**Comment by szczepiq** [comment]
+1

**Comment by bric3** [comment]
Don't forget bintray ;)

**Comment by bric3** [comment]
Also what do you think of this idea ? https://github.com/mockito/mockito/pull/483#issuecomment-241795084

**Comment by TimvdLippe** [comment]
Ah that seems like a good solution. These should only be possible on master.

**Comment by TimvdLippe** [comment]
Accidently pushed to master, but this should now be possible, see: https://github.com/mockito/mockito/commit/b6a402f16e9222605638efe9b57eccc80a197f9e

**Comment by bric3** [comment]
@TimvdLippe Nice.

In order to allow to patch version x, while allowing big refactorings on master. I propose that the project branch out the version like for version 2.x we could do a `release/2.x` (as commented in https://github.com/mockito/mockito/pull/483#issuecomment-231323266).


That also means that we can have a better control on versions, if we check the branch match the version to release :
https://github.com/mockito/mockito/commit/b6a402f16e9222605638efe9b57eccc80a197f9e#diff-33cf41d9669aaef72ca19c641dc57d47R68

**Comment by bric3** [comment]
We could create another issue in that regard...

**Comment by TimvdLippe** [comment]
Yes lets create a different issue for that. It should be fairly straightforward since we read from the file. Therefore if one branch has a different value in the file, it will bump to a different version

**Comment by bric3** [comment]
@TimvdLippe done : #594

**Comment by szczepiq** [comment]
Is this ticket done? Can anyone release manually now?

**Comment by TimvdLippe** [comment]
Yes if you use the correct commit message
