### ISSUE TITLE
Create Bintray account for Mockito

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#631]
Right now we are publishing to @szczepiq personal account, we should change this to a Mockito organization account. This makes it easier for credentials to be passed around of core developers.

**Comment by szczepiq** [comment]
+1
-- 
Szczepan Faber
Founder @ mockito.org | Twitter @ szczepiq
Author @ https://www.linkedin.com/today/author/6016386

**Comment by TimvdLippe** [comment]
So I was working on this one and tried to make an organization for Mockito on bintray, until I discovered that https://bintray.com/mockito already exists. However, I assume only @szczepiq has access so all developers will need to request to join the Bintray organization.

**Comment by szczepiq** [comment]
@TimvdLippe, I approved you and accidentally transferred ownership of the repo to you. Since there can be a single owner of the repo, I'd like to keep the owner role for the time being. Can you transfer the ownership back to me at https://bintray.com/mockito/organization/edit This will make you the admin of the repo with all required permissions to move Mockito forward. Thanks for driving this!

**Comment by TimvdLippe** [comment]
@szczepiq You are owner again :)

**Comment by szczepiq** [comment]
Sweet :)

**Comment by TimvdLippe** [comment]
Closing this as we do have the account, the others need to request access to join https://bintray.com/mockito

We can update the build script later when Mockito 3 is mature enough to publish beta releases.

**Comment by bric3** [comment]
OK added access
