### ISSUE TITLE
Update core dev team in gradle

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#633]
For example https://mvnrepository.com/artifact/org.mockito/mockito-core/2.1.0-RC.1 only lists @bric3 and @szczepiq. We need to include all @mockito/developers e.g. @timvdlippe, @raphw, @marcingrzejszczak and @szpak 

@szczepiq For the 3.0.0-beta.1 should we remove you from the list or what is the expected timeline for you?

**Comment by TimvdLippe** [comment]
P.S. @szczepiq if you still want to contribute to Mockito that is of course possible too. We are just wondering what the status is :) (if you decide to stay, we also have to invite you for our Slack, which I need your email for)

**Comment by szpak** [comment]
I haven't done much for 2.x. I'm comfortable with not being on the list right now. Maybe with 3.x I would have bigger contribution to the project.

I'm against removing Szczepan from the list. He created this project and he deserves to be on the developers list forever. What's more Szczepan currently is quite active, so maybe he will change his mind to leave the project :).
At the worst I would change developer to former-developer, founder or something like that.

**Comment by marcingrzejszczak** [comment]
Yeah the same with me in terms of 2.x. I did close to nothing.  I fully agree with @szpak  about Szczepan.

**Comment by szczepiq** [comment]
@TimvdLippe, the list can be updated in "pom.gradle". I don't see good reasons why we should remove people from this list. All former and current team members should happily remain there, including @szpak and @marcingrzejszczak :)

I'll let you know when I step down completely, not just yet ;) If I become inactive due to other priorities the team should move forward with growing and improving Mockito.

**Comment by TimvdLippe** [comment]
@szczepiq Yes I agree with the others to not remove people so I submitted #641 which does not remove anyone from the list, only add them :smile:
