### ISSUE TITLE
Better support of strict mocks

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#649]
## Introduction

**Better support for "strict" mocks will help with test debuggability in certain scenarios.**

Mockito mocks are loose by default - methods can be freely invoked on a mock, non-void methods will return default empty value. "Strict" mock works differently, you are not allowed to invoke a method on a strict mock unless this method was previously "configured". This is how traditional mocking frameworks like JMock or EasyMock work by default. Strict mocks offer better debuggability in certain scenarios, however overusing strict mocks leads to overspecified, brittle tests. Strict VS loose mock explanation deserves a separate article, this ticket does not elaborate it further.

**Mockito mocks will remain loose by default but we want to offer better support for strict mocks.**

Useful links:
- discussion in #303
## Implementation

Initial implementation, the goal is to satisfy the main use case and flesh out further improvements based on user feedback:
- Add new [Answer](http://site.mockito.org/mockito/docs/current/org/mockito/stubbing/Answer.html) implementation - **Strict**:

``` java
@Mock(answer=STRICT) Foo mock;
//or
Foo mock = mock(Foo.class, withSettings().defaultAnswer(STRICT);
```
- Strict answer fails fast when non-void method is invoked on mock without previous stubbing. No effect on void methods.
- Good documentation for strict VS loose mocks and clear recommendation what to use and when;   necessity of using doReturn() API instead of when() API when working with strict mocks.
## Next steps

**User feedback requested!**
- In order to streamline debugging, make it easy to opt-in for strict mocks temporarily, during debugging of specific test method. Current design (feedback requested):

``` java
//given
someSetup();

//when
Mockito.setStrict(mock1, mock2, ...);  // <--- temporarily added
methodUnderTest();

//then
assertions();
```
- Support teams that prefer strict mocking. Document how to use [MockitoConfiguration](http://www.javadoc.io/page/org.mockito/mockito-core/2/org/mockito/configuration/IMockitoConfiguration.html). Documentation needs to include call for feedback - we want to know what is the most convenient way for our users to configure default answer of the mock objects.

**Comment by ryan-gustafson** [comment]
In answer to a question on the other issue, in my custom Answer that does strict behavior I allowed void methods to be optionally strict, you can specify what you want you create the mock. I think I defaulted to not strict, as they have no return values that can affect flow control.

I pair this with rigorous verification through, so it's listed at the end of the test method.

If we could verify on stubbing, I'd do that instead, at which point I'd probably switch to strict style so voids are stub/verified up front like other methods, and fail on unstubbed use as others.

Would be nice to modify the default setting.

**Comment by Sarev0k** [comment]
One other option for void methods, considering that they won't affect your control flow, would be to not throw immediately at the time they are called, but allow us to verify at the end of the test method that there were no unstubbed interactions with a mock.

```java
final Foo foo = mock(Foo.class);
foo.bar(); // does not throw, because it is a void method
verifyNoUnstubbedInteractions(foo); // Fails, because bar() was not stubbed.
```

This could be beneficial, because it would allow me to see that the base test case passed, but find out afterwards, that I had one or more unstubbed interactions, that should be stubbed.  Maybe this check could even happen by default when using MockitoJunitRunner in a stricter strict mode.

**Comment by ryan-gustafson** [comment]
For voids, I think the choice is arbitrary on whether to fail immediately or defer to later. Both should be supported.  The former so that trailing verify boilerplate can be eliminated, the later for cases like you outlined.

**Comment by szczepiq** [comment]
Thanks again. Let's say that we offer an API for strict mocks:

1. Easy way to configure all mocks in codebase to be strict
2. New annotation @Mock(strict = true)
3. New convenience Answer so that one can do: mock(Foo.class, STRICT)

What is the desired behavior of the void methods? Are they strict as well? Options:

a) they are strict. Users are forced to write series of "doNothing().when(foo).bar()". It is not a very nice experience (cluttered test)
b) they are not strict, need to be verified at the end of the test.

>I think I defaulted to not strict, as they have no return values that can affect flow control

Cool idea. It ties nicely with striving for the balance between: debuggability and clarity of the test

BTW. Guys, did you try RETURNS_SMART_NULLS?

**Comment by Sarev0k** [comment]
> What is the desired behavior of the void methods? Are they strict as well? Options:
>
> a) they are strict. Users are forced to write series of "doNothing().when(foo).bar()". It is not a very nice experience (cluttered test)
> b) they are not strict, need to be verified at the end of the test.

I think both can be equally verbose, depending on how the test is written.  Assuming you actually want to capture these void interactions in your test, regardless whether you configure these void interactions up front, or you verify them after the test has executed, I think your test is equally cluttered.

Personally I prefer option B, because it gives me more control over how strict I actually want to be with specific mocks.  For some mocks, I might care about interactions with void methods, and for others I may not.  If you were also to provide a convenience verification method to allow me to check for unconfigured interations with my mocks, that would make it easier to verify the cases where I do care about void interactions.  Perhaps `verifyNoUnconfiguredInteractions(myMock)`.

> BTW. Guys, did you try RETURNS_SMART_NULLS?

I hadn't noticed this before, this is very neat.  My understanding is that this feature will basically create a mock of the return type instead of just passing back a null, and it will fail on interactions with the mocked return type containing helpful information about what unconfigured mock method created it.

Where this falls short is the cases where we are still passing back default values for primitive data types which could cause the code under test to go down unexpected call paths, and obfuscate the true cause of a test failure.

I would be open to a hybrid solution, where smart nulls are returned, and unconfigured interactions with methods that return primitive data types, or unmockable classes immediately throw instead.

**Comment by szczepiq** [comment]
Good feedback. We need more feedback such as this and formulate the design clearly (probably a separate ticket to keep things clean).

My thoughts:
1. Treating void method differently than returning methods is inline with Mockito spirit (making ask VS tell interaction explicit in the API).
2. Treating Object returning methods differently than primitive returning methods makes the API harder to grok, inconsistent.

**Comment by szczepiq** [comment]
I updated the ticket description. Feedback welcome! Otherwise the implementation starts!!! :)

**Comment by Sarev0k** [comment]
@szczepiq The description looks great.  Thanks for doing this.

> Good documentation for strict VS loose mocks and clear recommendation what to use and when; necessity of using doReturn() API instead of when() API when working with strict mocks.

I think this should be expanded on more.  Are you thinking it would always be necessary to use doReturn() to define strict mocks?  If so, is there a way to avoid this?  Having to change the way you define mock behavior will make it difficult to quickly and easily enable strict mocking to debug a single test.

Does this requirement come from the fact that the mock must be invoked when used in conjunction with when()?

> Support teams that prefer strict mocking, make it easy to opt-in for strict mocks for the entire codebase (currently supported by MockitoConfiguration but user experience of using MockitoConfiguration is poor and it competes with Mockito plugin API).

One way to do this could be to add support for a Java System Property that points to the fully qualified name of a default answer class.  Something like: `-Dmockito.defaultAnswer=my.default.Answer`.

> In order to streamline debugging, make it easy to opt-in for strict mocks temporarily, during debugging of specific test method.

Were you thinking of adding a new test annotation that could be used in conjunction with the MockitoJUnitRunner to accomplish this?  Something like:
```java
@Test
@DefaultAnswer(STRICT)
public void testMyStuff() {
}
```

**Comment by szczepiq** [comment]
Thanks for feedback!

>Does this requirement come from the fact that the mock must be invoked when used in conjunction with when()?

Yes. Following does not work with strict mock:

```java
when(mock.getStuff()).thenReturn(x); // mock.getStuff() throws strict exception
```

>Were you thinking of adding a new test annotation

That's one of the options. Brainstorming other options:

```java
Mockito.setStrict(mock1, mock2);
Mockito.debugMocks(mock1, mock2);
Mockito.debugTest(this);
Mockito.framework().debug();

//Java8
Mockito.strict { ->
  methodUnderTest()
}
```

**Comment by Sarev0k** [comment]
>> Does this requirement come from the fact that the mock must be invoked when used in conjunction with when()?

>Yes.

What if instead of immediately throwing, Mockito just kept track of all stack traces used in unstubbed interactions (the mocks would continue to return nulls and default values when called).

When the MockitoJUnitRunner is running in strict mode, usage of unstubbed methods would result in the following behavior at the end of the test:
* In the event there were no unhandled exceptions/assertion failures, the test would fail due to usage of unstubbed methods, with stack traces for all unstubbed calls output.
* In the event there were already unhandled exceptions/assertion failures, additional stack traces for all unstubbed calls would be output to aid in debugging the test failure.

I think this would be more compatible with being able to turn this feature on or off at any time, without needing to rewrite your tests.

**Comment by szczepiq** [comment]
The purpose of strict mock is to fail immediately when it is incorrectly invoked (e.g. without prior stubbing) - this gives best debugging experience. I'm curious what others think about your idea of 'softening' the strict mocks :)

FYI: Mockito already offers debugging hints vis [MockitoHint](http://static.javadoc.io/org.mockito/mockito-core/2.2.7/org/mockito/quality/MockitoHint.html).

**Comment by Sarev0k** [comment]
> The purpose of strict mock is to fail immediately when it is incorrectly invoked (e.g. without prior stubbing)

I understand, but I don't see how else it would be possible to temporarily opt into strict mocks in the future, if you have to stub your methods in a specific way to accomplish this.  Unless you specifically had using this feature in mind when writing your Mockito tests, you'd have to completely rewrite your stubbings in order to debug your test in strict mode.

Do you have something in mind for how this might eventually be accomplished given your current proposal?

> FYI: Mockito already offers debugging hints vis MockitoHint.

This is awesome! I didn't see mention of this when I read [what was new in 2.1](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2).  If there was an option to turn these warnings into assertions, I think that would perform exactly as I described above.

**Comment by szczepiq** [comment]
Fleshed out 'Next steps' section in the main ticket description.

**Comment by szczepiq** [comment]
>Do you have something in mind for how this might eventually be accomplished given your current proposal?

I've added Mockito.setStrict() method in 'next steps section' of the ticket description. If one "turns on" the strict mocks just before the tested method is invoked, there is no need to rewrite the stubbing code.

The purpose of Strict answer in the API is to get it to the hands of users and get more feedback (and new interesting ideas). We already had feedback that teams would prefer strict mocking. I want an evidence that it is really useful and practical.

**Comment by Sarev0k** [comment]
> We already had feedback that teams would prefer strict mocking. I want an evidence that it is really useful and practical.

I have no objections to this feature as you've defined it, I'm just concerned that adoption may be affected by the extra friction added by the requirement that stubs must be defined in a specific way, that in my opinion is currently only used in rare circumstances.

> Mockito.setStrict(mock1, mock2, ...);  // <--- temporarily added

Have you considered what this might look like if a mock was using the [DEEP_STUBS](http://site.mockito.org/mockito/docs/current/org/mockito/Mockito.html#RETURNS_DEEP_STUBS) default answer?  Would this recursively enable strict mocking for nested mocks?

I could see the call to setStrict being quite large for some tests, with the possibility that some mocks being accidentally left out.  Would it be possible to make this even simpler by doing something like:
```java
// enable strict mode for all defined mocks in this test
Mockito.enableStrictMode();
```

**Comment by szczepiq** [comment]
@Sarev0k, great feedback!

I want to start with something simple. Either Mockito.enableStrictMode(); or Mockito.setStrict(mock1, mock2); work for me (method names to be confirmed), then I'd wait for feedback. The question is what is the better default? Strict per mock is fine grained but annoying if you need to list all mocks. Strict framework is easier to use but you're busted if you want to make strict only few mocks ;)

**Comment by Sarev0k** [comment]
> The question is what is the better default?

I think this depends on what you expect the usage pattern to be.  Are you expecting users of this feature to only want to enable strict mode on a select few mocks in their tests, or are you thinking they'd prefer to enable strict mode across all their mocks.

In my opinion, the latter is more useful to enforce strict interactions with all your mocks.  This is the method I would prefer to use in my tests.

The former is useful if you just want to debug interactions with a specific set of mocks, but don't care about the rest.  I'm not sure under what circumstances I'd prefer to use this method instead.

**Comment by szczepiq** [comment]
>In my opinion, the latter is more useful to enforce strict interactions with all your mocks. This is the method I would prefer to use in my tests.

I also lean towards having a single method that would enable strictness for all mocks. However, this is harder to implement because it would require the user to disable that mode afterwards. Otherwise, that mode would influence other test methods, too.

Given lack of clean implementation options for all-mock strictness, I want go ahead with setStrict(). Feedback / ideas are very welcome!

**Comment by Sarev0k** [comment]
> However, this is harder to implement because it would require the user to disable that mode afterwards.

What if you were to implement this as a method that accepts a Java8 lambda?  That way you could control when strict mode is enabled and disabled for all mocks?

```java
Foo foo = mock(Foo.class);
when(foo.bar()).thenReturn("baz");

Mockito.runInStrictMode(() -> foo.bar());
```

Alternatively you could make the MockitoJunitRunner automatically disable strict mode for all mocks as clean up after every test case.

**Comment by szczepiq** [comment]
Lambda is a viable option.

Runner clean up sounds good but it only covers the case when the runner is used. Hence, it is not sufficient to maintain safety.

**Comment by dmak** [comment]
Is there any idea how "strict mocks" feature is going to be combined with "ordered mocks"? Something like that?
```
Foo foo = mock(Foo.class);
Moo moo = mock(Moo.class);

Mockito.when(foo.getMoo()).thenReturn(moo);
Mockito.when(moo.toString()).thenReturn("moo");

Mockito.setStrict(foo, moo);
Mockito.inOrder(foo, moo);

Bar bar = new Bar();
bar.doSomething(foo);
```

**Comment by szczepiq** [comment]
I'm closing this ticket and opening a new one for fresh discussion. This issue contains too much discussions around the API that we probably won't use because we currently have the new "Strictness" API. New ticket is #1097, please leave feedback there!

Thank you for all the discussions in this ticket!
