### ISSUE TITLE
Configure the release branch to publish automatically

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#681]
Let's configure the release branch release/2.x to automatically publish / increment versions so that we can improve Mockito 2.x continually.

**Comment by szpak** [comment]
+1 (unless manually skipped with a comment in a commit message - i.e. when no value is added - for example a typo in documentation).

**Comment by bric3** [comment]
I'd rather continue with the milestone, otherwise we may introduce wrong changes, that already happened in the past in the 1.10.x

**Comment by szczepiq** [comment]
The best way to avoid wrong changes is to write hight quality code that includes design and testing ;)

@bric3, please suggest a release procedure so that we can review it. At the moment, we have the same model as started 2 years ago and documented on the wiki.

**Comment by bric3** [comment]
The issue is that when we merge PR some changes can be included. While those appear tested and good enough designed, they reveal short-sighted etc after example experience the wild.

Also for changes that may require multiple PR in order to keep reviews easy, this model don't fit.

**Comment by TimvdLippe** [comment]
I was under the impression that we already settled on a release procedure, but I will reiterate what I was thought was decided upon:

1. We create a separate Bintray project for beta releases
* `release/2.x` and `master` publish `2.y.0-beta.x` and `3.0.0-beta.x` versions respectively to this project
* When we have finished a milestone, we publish `2.y.0` or `3.0.0`

This was 1 to prevent a beta version overload because we did not have a strict feature set and 2 misuse maven central for non-final versions of Mockito.

For this we need to fix the target of beta releases, fix the issues with publishing custom versions and correctly set our milestones.

On a related note: if we keep on discussing our release procedure instead of working on actual features, I think we are not using any of the benefits of continuous delivery nor the automatic release procedure.

**Comment by szczepiq** [comment]
Guys, I love the way you continue to challenge how we do stuff. Keep doing this!!! This way we can all learn.

Mockito continuously delivers, real versions, not betas.

**Comment by TimvdLippe** [comment]
> Mockito continuously delivers, real versions, not betas.

Well I think we have to revisit that statement. See my above comment.

**Comment by szczepiq** [comment]
The old style release model, where multiple changes are stacked into single release is not sustainable. It _makes releases harder_, puts testing, documenting effort to end of the cycle. It makes it harder because it introduces decision points around dates, features to include in milestones, time pressure, etc. It makes it harder to provide high quality features to users. For example, I cannot give feature #676 to the users because Mockito no longer publishes automatically :)

Old style release model distracts from the real work, e.g. focusing on features like new stubbing api, Java8, etc.

The solution to prevent beta proliferation by not releasing betas to central / jcenter does not really solve the core problem. The core problem is inability to release. To fix this problem, releasing needs to be very easy, automatic, incremental and pushing hard for highest quality PRs.

The old style release model is not sustainable in an Open Source environment where maintainers can change priorities and stop actively participate in the project, leaving milestones half-finished.
