### ISSUE TITLE
@InjectMocks not working for multiple mocks of the same type via constructor injection

### ISSUE THREAD

**Issue by mgrodek** [mockito/mockito#686]
Hi,

I have created an issue on [SO](http://stackoverflow.com/questions/39911735/injectmocks-not-injecting-2-mocks-of-the-same-type-when-using-constructor-injec). It's about @InjectMocks when using constructor injection. Could you help me with that? If it's not possible at the moment maybe it's good idea to enhance Mockito with that feature?

Best regards,
Mariusz

**Comment by TimvdLippe** [comment]
You need to name your Mocks. E.g. `@Mock(name = "bar1")`. Then Mockito can deduct from the name the correct field with the same name.

**Comment by mgrodek** [comment]
Heh, ok, I tried that and it is not working. There was an answer to my question on SO and that person confirmed it is not working. I don't know why he deleted this answer.

**Comment by TimvdLippe** [comment]
Ah the naming actually works on setters and not constructors. I am not sure if it is even possible to extract the names of the constructor arguments. Could you add setters for the fields and try again?

**Comment by bric3** [comment]
This case is not supported. In any java version.

That being said, it's possible to improve a bit the engine to look at parameter names...
Until java 8 method or constructor parameters are not named so it's impossible to perform the correct parameter assignment. Even with Java 8 you have to explicitly pass an option `-parameters` to the compiler in order to have parameter names. But this is of course limited to code compiled with that option ie your code.

**Comment by bric3** [comment]
@TimvdLippe They can be. But as mentioned, chances are that those parameters names are compiled in.
