### ISSUE TITLE
When overriding a stub, the original stub should not be invoked

### ISSUE THREAD

**Issue by rdicroce** [mockito/mockito#773]
Situation: I have a test class in which a mock should invoke a custom Answer during most test methods, but a couple test methods need different behavior. So I created a Before method to stub the mocks, then in the relevant test methods, I stub them again to override. The problem is that Mockito invokes the original Answer when I stub the mock the second time, which in my case causes a NPE because the custom Answer is doing things with the invocation parameters.

I'm working around the problem by creating an OverridableAnswer that gets attached to the mock, and delegates to the real Answer. But this creates a bunch of unnecessary boilerplate. It would be nice if Mockito noticed that the stubbed method is being invoked during a new stubbing, and skip calling the originally stubbed Answer.

This issue was discovered on Mockito 1.10.19 (we currently can't upgrade to 2.x because PowerMock's support for Mockito 2 is broken), but I confirmed it still exists in 2.2.22.

Here's a simple reproducer:
```java
	@Test
	public void testOverrideStub() {
		A instance = Mockito.mock(A.class);
		Mockito.when(instance.foo()).then(new Answer<Integer>() {
			public Integer answer(InvocationOnMock invocation) throws Throwable {
				invoked = true;
				return 1;
			}
		});
		Mockito.when(instance.foo()).then(new Answer<Integer>() {
			public Integer answer(InvocationOnMock invocation) throws Throwable {
				return 2;
			}
		});
		Assert.assertFalse("Overriding stubbing should not invoke original stub", invoked);
	}
	
	private static class A {
		public int foo() {return 0;}
	}
```

**Comment by szpak** [comment]
You can use:
```
Mockito.doAnswer(...).when(instance).foo();
```

as a workaround. Method `foo()` is executed on the proxy, so the original stubbing shouldn't be called on the second stubbing. This syntax in general should be rather used for spies and void methods as it doesn't provide compile time type checking.

**Comment by rdicroce** [comment]
Unfortunately, I can't use that workaround. It would work for the reproducer I provided, but the real code is using PowerMock to mock a static method, so there is no instance to provide. I tried PowerMock's when() for private static methods, but that didn't work either.

**Comment by szczepiq** [comment]
@rdicroce, thank you for submitting the report!

I'm with you that it's really annoying that Mockito invokes the "previous" stubbing when you attempt to stub the same method again in the same test. This is trade off of the original, super readable when() API. It is not really fixable without changing the API drastically. The current workaround for this is using the doReturn() syntax.

If you have ideas how to fix this problem, let us know. We do brainstorm and experiment on creating new APIs for stubbing that would resolve this gotcha. For the time being, I will close this ticket because there is nothing we will do to address it at this time.

Also, in the future we plan to offer static method mockability from inside Mockito directly.

**Comment by rdicroce** [comment]
@szczepiq What about adding a method to the Mockito class that just temporarily disables invocation of stubs? I know that's not ideal, but at least it provides a solution, and it's less annoying than what I'm doing now. Something like

```java
Mockito.withStubInvocationDisabled().when(Static.foo()).then(someAnswer);
```

Stub invocation could be automatically re-enabled by the next when() or then() call, so the user doesn't need to make a second explicit call to re-enable stubs.

Or, for those of us on Java 8, maybe a lambda approach:

```java
Mockito.withStubInvocationDisabled(() -> {override some stubs here});
```

Regarding static method mocking being added to Mockito, that would be fantastic. Is there any timeframe on that? Any open issue I could track?

**Comment by szczepiq** [comment]
The solution you suggest already exists and it's the doReturn() API :)

If doReturn() does not work for you (PowerMock?) why would withStubInvocationDisabled() work?

**Comment by rdicroce** [comment]
As I explained previously, I'm using PowerMock to mock a static method. doReturn() chains to when() which requires a mock instance to be passed. No such instance exists because it's a static method. Thus, doReturn() cannot solve my problem. withStubInvocationDisabled() would work around that problem by allowing me to instead chain to Mockito#when(), which is what I'm already using.

**Comment by bric3** [comment]
Closing right now, as it's more of a problem with powermock.

**Comment by haarts** [comment]
Sorry to comment on this closed issue. But I can't seem to grok this. 
I have simple test class which defines a `@Before` method. Therein I mock a certain call. This mock is good for all but two of my `@Test`s. That looks something like this:

```java
    public void stubTanks() {
        when(tankRepository.findAll())
                .thenReturn(new HashSet<>(Arrays.asList(new Tank())));
    }
```

In the two deviates I overwrite (or so I thought) the stub like so:

```java
    doReturn(new HashSet<>(Arrays.asList(new Tank(), new Tank()))).when(tankRepository).findAll();
    // actual method call
    verify(someOtherMock, times(2)).someMethod(); 
```

This fails. `someMethod` is still only called once (I expected twice, once for each item in the list). Am I mixing `doReturn` and `when` wrong?

**Comment by shivanisky** [comment]
I am also seeing this issue and it has nothing to do with powermock - looks like a mockito bug. FYI - I did not write these test cases I am migrating from jmockit.

Have something like:

testMethod(@Mock Bla bla) {
   check(bla, 5);
   check(bla, 6);
}

void check(Bla bla, int num) {
   when(bla.method()).thenAnswer(invocation -> {
         //some operations involving num and invocation.getArgument(0)
   });
   someMethod(bla); // this calls bla.method
}

Because check executes twice, what happens is that the second time around, the stub gets executed BEFORE the method invocation. 

I used Mockito.reset(bla) to workaround for now. But this looks like a bug to me. I don't have time to rewrite the test case as this is purely a migration work and have tight deadlines.

Alternatively I guess I could do thenAnswer(. ... ) and then .thenAnswer() again. That could also work. But I would expect the above to work with restubbing?
