### ISSUE TITLE
Defining a new mocked method invokes previously defined one

### ISSUE THREAD

**Issue by Antolius** [mockito/mockito#78]
For instance, the following test fails with java.lang.RuntimeException: Init mock exception:
```
interface Mockable {
	public int method(int param);
}

public class MockitoTest {
	private Mockable myMock;

	@Before
	public void init() {
		myMock = Mockito.mock(Mockable.class);
		when(myMock.method(anyInt())).thenThrow(new RuntimeException("Init mock"));
	}

	@Test
	public void test() {
		when(myMock.method(eq(1))).thenReturn(1);
	}
}
```
So, the parameter in when statement in test actualy invoked previously defined mock method from init.

Consequently, this means that I can't define more abstract mock in my init method and override it, if necessary, in some of my tests.

**Comment by snargleplax** [comment]
I think the problem is slightly more specific.  From what I've seen, if all the mocked methods use thenReturn(), everything works as you'd want -- any new invocation as in your test() method clobbers the previously mocked behavior.  However, it appears that this clobbering fails to take place if the first mock uses thenAnswer(), and apparently you've run into it for thenThrow() as well.

Looking at the code for MockHandler.handle(), it's pretty clear why this is happening.  It checks hasAnswersForStubbing() (which maybe also finds stuff set up by thenThrow()?  The comments also mention stubVoid()), and if it finds something there it uses it and exits early without hitting the the code with the matchers and all.

Definitely seems like a bug to me -- I expect thenReturn() to be interchangeable with an equivalent thenAnswer(), without functional changes.  Same goes for thenThrow() or whatever else is used in the same way.

**Comment by kflorence** [comment]
+1

**Comment by szczepiq** [comment]
I'm afraid this is not solvable with this api. I believe it is documented.
Please use do return api. Hope that helps!
