### ISSUE TITLE
Add default answers for java.util.Optional{Double,Int,Long} and java.util.stream.{Double,Int,Long}Stream

### ISSUE THREAD

**Issue by Stephan202** [mockito/mockito#781]
A natural generalization of #191 and #429 is to add default answers for the primitive `Optional` and `Stream` variants as well. I'm working on a PR proposal; will file soonish.

**Comment by bric3** [comment]
When mockito runs on Java 8 it already provide default answers for `Optional` / `Stream`

**Comment by Stephan202** [comment]
I tested that before filing this issue; that's true for `Optional`, but not for `OptionalInt` and friends.

**Comment by bric3** [comment]
Oh ok I read too fast the issue description. Sorry ;)

**Comment by Stephan202** [comment]
No worries :). PR filed: #782.

**Comment by Stephan202** [comment]
NB: I opened this ticket before opening the PR only because the contribution guidelines [state](https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md) that at least one commit must be of the form `Fixes #id :`. But it seems a number of PRs (like the aforementioned #429) don't follow this guideline. Also, the guidelines indicate there should be a colon after the issue ID, but that rule seems to be followed "almost never". So what's your current view on this?

**Comment by bric3** [comment]
@Stephan202 Sorry for the late reply, I'm in the middle of painful refactoring at work.

Well this generally apply when there's a separate issue either because it's the same person, or because there's delay between the issue and the pull request, but you can propose a pull request that fixes an issue, that's ok, just as long as you describe properly the problem or motivate properly the change ;)
