### ISSUE TITLE
Expose 'internal' classes so Powermock-osgi can be incorporated without special builds of Mockito

### ISSUE THREAD

**Issue by jcantrill** [mockito/mockito#80]
I'm trying to get Powermock and mockito into the JBoss Tooling Target plaform and is being placed on hold (https://issues.jboss.org/browse/JBIDE-18053).  This thread (https://code.google.com/p/powermock/issues/detail?id=204) mentions there are some dependencies on internal classes.  I would like to expose those internals such that mockito and powermock can be pulled into the eclipse repos as part of the target platform.  I'm available to help if someone can point me where to start

**Comment by TimvdLippe** [comment]
Hm I am not sure if we want to expose more of our internal implementation. @mockito/developers what is your opinion?

**Comment by jcantrill** [comment]
Is there a way to place public interfaces that can be exposed around these classes?

**Comment by TimvdLippe** [comment]
The problem with exposing our internal implementation is that we need to support it. As a result, every breaking change requires major version upgrades since we have to commit to semver. Even if such classes are internal, whenever we make a change to them they could potentially break other dependencies including PowerMock.

Directly exposing of internal implementation is therefore a no-go for me. That said, I do think Mockito should provide more hooks to support potential dependencies relying on the Mocking engine. E.g. a hook which notifies a mock has been created. This is for example tracked in [the listener branch](https://github.com/mockito/mockito/commits/listener).

These hooks can be implemented in any way possible, allowing the Mockito developers freely improving the backing engine without fearing backwards compatibility issues. Would such hooks be a good replacement, and if so what kind of hooks are you looking for?

**Comment by jcantrill** [comment]
I understand the limitations and the desire not to want to support the internal classes in a versioned mannor but I am not able to answer your question.  The obvious answer IMO is that one should be able to deploy powermock within an OSGI env and not be concerned about its dependency on internal classes; I would hope there were a way for powermock to get access to the meta it requires via a public api.  Is that via these hooks?  That would be for you and the powermock team to determine.  I suspect if you spin through powermock code you could determine what exactly they need.  Ideally, the features provided by powermock could  be just rolled into mockito which would alleviate the necessity to begin with.

**Comment by bric3** [comment]
As of now I propose that we keep exposing internal API on the OSGI manifest entries as long as we don't have those hooks available. It less than ideal, but this should definitely be possible for OSGI environment to run powermock.

@jcantrill Did you tried to package mockito without the `internal` exclusion ?

Current export rule in `osgi.gradle` :

```
instruction 'Export-Package',
        '!org.mockito.asm.*',
        '!org.mockito.cglib.*',
        '!org.mockito.internal.*',
        "org.mockito.*;version=${version}"
```

------

By the way we should remove `'!org.mockito.asm.*'` and `'!org.mockito.cglib.*'` in mockito 2.0

------

could become

```
instruction 'Export-Package',
        "org.mockito.*;version=${version}"
```

**Comment by jcantrill** [comment]
@bric3 I did not.  This request really stems from pushback from the JbossTools team not wanting to include powermock in one of my PRs because it exposes/depends upon internal mockito packages.

**Comment by szczepiq** [comment]
>As of now I propose that we keep exposing internal API on the OSGI manifest entries as long as we don't have those hooks available.

+1

@jcantrill, do you represent PowerMock team? Are you interested in working together to expose public API in Mockito that you could use? From Powermock we would need use cases. E.g. the list of internal classes PowerMock uses is not good enough - we need to know the use cases to design & implement good API.

**Comment by jcantrill** [comment]
@szczepiq I am a dev for Red Hat that works with JbossTools and Openshift and do not represent the PowerMock team.  I am interested in helping to the point I am able given other time constraints and responsibilities.

**Comment by szczepiq** [comment]
Great. Thanks a lot @TimvdLippe for cleaning up the backlog!!!
