### ISSUE TITLE
Unable to Debug Asynchronous block using Mockito 2.2.22

### ISSUE THREAD

**Issue by SriPalla** [mockito/mockito#806]
Below is the source code

```java
public class Calculator {
	@Inject AsyncExecutor async;
	
    public int sum(int add1, int add2) {
    	System.out.println("Before Aync call");
    	async.submit(new Callable<Void>() {
			@Override
			public Void call() throws Exception {
				System.out.println("Inside Async Block");
				return null;
			}
		});
        return add1 + add2;
    }
}
```

Below is the test case

```java
@RunWith(MockitoJUnitRunner.class)
public class CalculatorTest {
	@Spy
	private AsyncExecutor async = new AsyncExecutorImpl();
	@InjectMocks
	private Calculator calculator;

	@Test
	public void testSum() throws Exception {
		int result = calculator.sum(1, 2);
		assertEquals(3, result);
	}
}
```

Control is not halting at `System.out.println("Inside Async Block");`  in case of above Junit being debug with a break point inside async block

**EDITED by @bric3**: correct snippet code block

**Comment by bric3** [comment]
@SriPalla I don't have the code of `AsyncExecutorImpl` but I suppose that the `submit` method works the same as `ExecutorService.submit` i.e. it takes a task (`Runnable` or `Callable`) reference to be **executed later**. Since `AsyncExecutorImpl` is spied the _real_ code is executed.

I'am pretty sure that the task will be executed if the JVM has enough time to run it, i.e. add a `TimeUnit.SECONDS.sleep(30)` after `calculator.sum(1, 2)`.

But what you probably really want is to either change the spied implementation of `AsyncExecutor` or more simple mock the `submit` method to execute immediately the given task.
