### ISSUE TITLE
Proposal for lambda and void friendly when+then syntax

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#815]
This is a API proposal for an "when+then" that can be used to stub void methods (and static calls if they will be suported in the future) with a lambda friendly "then" API.

This ticket relates to #643 

Uses case:

 * Stubbing using an instance method reference: `when(mock::voidMethod).then(...);`
 * Stubbing using an Lambda expression:` when(()-> mock.voidMethod(gt(4))).then(...);`
 * Possible future use case, stubbing a static method:` when(()->Util.voidMethod(4)).then(..);`
 * Stubbing and processing the first argument:` when(()-> mock.voidMethod(gt(4))).then(firstArg -> println(firstArg));`
  * Stubbing and processing the InvocationOnMock: `when(mock::voidMethod).thenAnswer(invocation -> println(invocation.getMethod()));`

The API:
```java
class Mockito{
    OngoingVoidStubbing when(VoidCall call);
}

interface VoidCall { 
    void run() throws Throwable;
}

interface OngoingVoidStubbing {
    OngoingVoidStubbing thenAnswer(VoidAnswer answer);
    OngoingVoidStubbing then(VoidAnswer0 answer);
    <A> OngoingVoidStubbing then(VoidAnswer1<A> answer);
    <A,B> OngoingVoidStubbing then(VoidAnswer2<A,B> answer);
    <A,B,C> OngoingVoidStubbing then(VoidAnswer3<A,B,C> answer);
    OngoingVoidStubbing thenDoNothing();
    //... all other thenXXX methods from OngoingStubbing except thenReturn(..)
}

interface VoidAnswer{
     void answer(InvocationOnMock invocation) throws Throwable;
}

interface VoidAnswer0{
     <A> void answer(A firstArg) throws Throwable;
}
```
     
Current state: I have a working prototype ([gist patch](https://gist.github.com/ChristianSchwarz/db9973bb4a7043d4db410d36b7cf87d1)), currently I can't send a PR cause I am behind a firewall.

**Comment by TimvdLippe** [comment]
Isn't this duplicate of #643? Adding the interfaces for void methods seems sufficient to include in that implementation to achieve this goal.

Do note that `OngoingVoidStubbing` must have generic arguments to obtain typesafety between the `when` and the `then`

**Comment by ChristianSchwarz** [comment]
This proposal can be seen as different approach to realize stubbing of void methods, it just a base for further discussions. 

Other than #643 the primary goal is not to provide typesafe answers. The goal is to stay as close as possible to the well known when+then syntax for returning methods. Therefore the `when(VoidCall)` API is not meant to replace the existing `when(T)` API for returning methods, it should be seen as an addition.

**Comment by szczepiq** [comment]
I lean towards not offering such additional alias.

I really like the fact that it introduces similarly looking API for void methods (and spying, static mocking, edge cases). Thing is, the more aliases the more complex API. We would also need to offer it for given() syntax.

Some options (v3 gives opportunity to change the API):
- get rid of doReturn() API, replace with this api
- get rid of when() API, leave only given() :D

@ChristianSchwarz suggests to add new aliases for stubbing in this PR. I'm curious what other team members say.

Note that static mocking will most likely require slightly different api anyway, for example:

```java
mockClass(Foo.class).given( <lambda> ).willReturn();
```

**Comment by TimvdLippe** [comment]
I do agree that we should try to prevent additional aliases. Still this functionality is included in the other PR (as I took inspiration from this PR) and I think replacing is the best solution. All functionality can be handled in a uniform way with the lambda syntax.

**Comment by szczepiq** [comment]
@TimvdLippe, can you link to the PR that you promote?
@ChristianSchwarz, this ticket has fantastic description! Minor feedback: "VoidCall" naming family does not seem to be correct because the syntax is essentially for all methods, not only void methods.

**Comment by TimvdLippe** [comment]
PR is at #742

**Comment by ChristianSchwarz** [comment]
@szczepiq 

> Minor feedback: "VoidCall" naming family does not seem to be correct because the syntax is essentially for all methods, not only void methods.

Yes it is possible to write a lambda that contains a call to a non void method. It is also possible to call more that one mock method or even to pass a lambda body that is empty. These cases are already covered by the current implementation by throwing an Exception.  So the type `VoidCall` tries to underline the fact that only one void call is allowed.

**Comment by ChristianSchwarz** [comment]
Since there is no interest in different API proposals to use lambdas for stubbing I close this ticket. See #742

**Comment by Marcono1234** [comment]
Should this issue here maybe be reopened (at least to keep tracking the idea)? If I understand it correctly some of the concerns with #742 and #1264 were that it creates a completely new API and might also be a bit verbose, and that it has issues with overloads, see https://github.com/mockito/mockito/pull/1264#issuecomment-736126839.

Whereas the proposed idea here is pretty close to the existing API:
- existing: <code>when(_invocation_).then(...)</code>
- suggested: <code>when(() -> _invocation_).then(...)</code>

It 'merely' suggests to additionally (or instead?) be able to use a lambda in `when`. This is also the same way the already existing `MockedStatic#when` works, so it would not be that unfamiliar to users.

I would suggest to not limit it to `void` methods though, because this lambda approach could also solve issues such as #500 or #1381 where Mockito currently for <code>when(_invocation_)</code> does not understand that you want to _stub a method_, but instead thinks you want to _call a method on the mock_.

But as mentioned in https://github.com/mockito/mockito/pull/1264#issuecomment-2254653813, if such a new lambda supporting `when` is added, maybe it should not be named `when` since in some corner cases the compiler might pick the wrong overload of `when`, which can lead to a `ClassCastException`.
