### ISSUE TITLE
Feature request: ArgumentMatchers.matches(Pattern regex)

### ISSUE THREAD

**Issue by Mrodent** [mockito/mockito#838]
you ladies and gentlemen are geniuses by the way.

ArgumentMatchers.match( String regex ) exists... but wouldn't it be slightly better if it were match( Pattern regex )? (i.e. catering for multi-line Strings, etc.).

Also, devising a regex which distinctly does NOT match a given String is non-trivial.  And yet not atypical of a mocking use case.  Hence I suggest you clever people take the heavy lifting away from grunts like me by offering ArgumentMatchers.doesNotMatch( Pattern regex ).

I posed this question today on Stack Overflow [here](http://stackoverflow.com/questions/41270738/mockito-argumentmatchers-doesnotmatch?noredirect=1#comment69745269_41270738).  

------

**EDIT 1** by @bric3 : removed the issue guidelines
**EDIT 2** by @bric3 : Renamed the issue title. Previous title was `Feature request: ArgumentMatchers.doesNotMatch( Pattern regex )`

**Comment by bric3** [comment]
As the answer in SO, you can negate matchers using `AdditionalMatchers.not()`.

I think I can close this issue.

**Comment by Mrodent** [comment]
OK... but this question highlights the fact that the online documentation and tutorials are not optional, they are essential ... and they are currently inadequate.  People who are willing to learn shouldn't have to pose a question for such an obvious use case on SO.

**Comment by bric3** [comment]
Hi,

I closed the issue because it is about a feature request that is not valid since the feature is already present in a different form. Now documentation and tutorial is another thing.

`AdditionalMatchers` is mentionned on the first line of the [ArgumentMatchers javadoc](https://static.javadoc.io/org.mockito/mockito-core/2.4.0/org/mockito/ArgumentMatchers.html). The Mockito javadoc gives plenty of code examples on the public API, which is already more than most javadoc in almost every project. 

I'm not saying it can't improved or we won't improve it, it can and we will! On the matter at hand those matchers can be promoted a bit more to enhance discoverability.

Regarding tutorials I believe it is the responsibility of respective blog authors.

In the mean time pull requests are welcome, and the wiki can be edited by any benevolent soul.

**Comment by Mrodent** [comment]
Yup, understood.

**Comment by bric3** [comment]
Also it seems I skipped the part on the `Pattern` class, reopening for the `matches(Pattern)` matcher.

**Comment by Mrodent** [comment]
Oh... good.  No really!  The multi-line challenge has me foxed... indeed.  :)

**Comment by bric3** [comment]
The builds should propagate within an hour

**Comment by Mrodent** [comment]
Hi Brice... thanks for doing this so quickly.  I have upgraded my gradle.build and got hold of your new build.  But I am still having problems using "not" with this... if you have a moment maybe you might look at my new edit at [SO](http://stackoverflow.com/questions/41270738/mockito-argumentmatchers-doesnotmatch).

**Comment by bric3** [comment]
It looks like an import issue, either for `not` or `matches`. I've tested it yesterday, when I added the API.

**Comment by Mrodent** [comment]
Yes, you're right: it's an AssertJ confusion: Eclipse imported NotFilter.not() automatically.  Apologies.
