### ISSUE TITLE
No way for user to tell Mockito about matchers that take matchers

### ISSUE THREAD

**Issue by dmstocking** [mockito/mockito#877]
I was trying to write a new Matcher that would take a lambda, and a matcher. This might sounds familiar because I am trying to create a PropertyMatcher for Mockito with lambdas. I made the following matcher.

```
public class PropertyMatcher<T, S> extends ArgumentMatcher<T> {

    @NonNull private final Func1<T, S> map;
    @NonNull private final S matcher;

    @SuppressWarnings("unchecked")
    public static <T,S> T propertyThat(@NonNull Func1<T, S> map, @NonNull S matcher) {
        return Matchers.argThat(new PropertyMatcher<>(map, matcher));
    }

    public PropertyMatcher(@NonNull Func1<T, S> map, @NonNull S matcher) {
        this.map = map;
        this.matcher = matcher;
    }

    @SuppressWarnings("unchecked")
    @Override
    public boolean matches(Object item) {
        try {
            // pretty sure this won't work because mockito doesn't work like hamcrest
            Matcher<S> m = (Matcher<S>) matcher;
            return m.matches(map.call((T) item));
        } catch (ClassCastException cce) {
            return matcher.equals(map.call((T) item));
        }
    }

    @Override
    public void describeTo(Description description) {
    }
}
```

Now this works ONLY if you use nothing but values. So a working example would be
```
verify(managerMock).manage(propertyThat(Request::id, 1)); // ok
```
However once I start to use a matcher, I get an error saying that I am mixing matchers and real values.
```
verify(managerMock).manage(propertyThat(Request::id, eq(1))); // error
```
This is because the argument matcher storage has no idea I am a matcher taking matchers. All of that is private so I don't really have a way to get to it (without reflection). That is only the part I know I would need to fix. I don't know the implementation all that well so I don't know if there is something else that would be required. Is there any expectation that this could be done? Should I just not even bother with this and just make a matcher that is a lambda with the checks? I will admit that I am still on version 1.10.19. When I went to figure this out I was quite surprised that 2 had been release. I haven't tried it yet, but I don't know if Android's sorta Java 8 would work with Mockito 2 anyway.

**Comment by bric3** [comment]
Mockito 2 is Java 8 aware, but it is still compiled with Java 6. Many people already use it with their Android code. There's some things to change as well, like use the linkedin version of dexmaker and soon there will be a mockito-android probably with better dex support.

-----

I'm not sure of the imports here as `ArgumentMatcher` seems to be Mockito 2 type, `Matchers` is Mockito 1 type (or even an Hamcrest one).

Mockito rewrote mockito matchers to avoid dependency on Hamcrest. Using Hamcrest matchers is still possible when using `MockitoHamcrest`.

------

Now regarding your question, this not possible to use Mockito matchers inside Hamcrest matchers with the current API. There's still a way when using reflection API, but this would be brittle at best, since this require understanding and adapting to the internal API, which is subject to change in signature, type and / or behavior.

The best way imho, is to use Hamcrest Matchers instead of mockito matchers.

**Comment by dmstocking** [comment]
Ok I'll try changing this matcher to use Hamcrest matchers and try it out. Thanks for the quick response. When I tried, I kind of got the feeling that what I was trying to do wasn't feasible. :)

**Comment by bric3** [comment]
I'm thinking ways to improve this use case.
