### ISSUE TITLE
java.lang.IllegalStateException: Could not initialize plugin

### ISSUE THREAD

**Issue by RajuSE** [mockito/mockito#910]
I'm trying to run instrumentation test on AS.

stuck with this Error:
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:66) at java.lang.reflect.Proxy.invoke(Proxy.java:393) at $Proxy4.isTypeMockable(Unknown Source) 

Stackoverflow : 
http://stackoverflow.com/q/41850779/4903889

**Comment by tmurakami** [comment]
Hi.

Try adding the following snippet to the dependencies section in your build.gradle.
```groovy
dependencies {

    def mockito_version = 'latest.release'

    // For local unit tests on your development machine
    testCompile "org.mockito:mockito-core:$mockito_version"

    // For instrumentation tests on Android devices and emulators
    androidTestCompile "org.mockito:mockito-android:$mockito_version"

}
```

**Comment by RajuSE** [comment]
@tmurakami Thanks!

**Comment by IgorGanapolsky** [comment]
@tmurakami What is **latest.release**?

**Comment by tmurakami** [comment]
@IgorGanapolsky, `latest.release` is one way to specify the dynamic version of Gradle.
https://docs.gradle.org/current/userguide/dependency_management.html#sub:dynamic_versions_and_changing_modules
https://docs.gradle.org/current/userguide/dependency_management.html#component_metadata_rules

On Android Studio, when using the Gradle setting described in [Mockito's Javadoc](https://static.javadoc.io/org.mockito/mockito-core/2.7.13/org/mockito/Mockito.html#0.1), the following warning will be displayed.

> Avoid using + in version numbers; can load to unpredictable and unrepeatable builds (org.mockito:mockito-android:+)
> 
> Using + in dependencies lets you automatically pick up the latest available version rather than a specific, named version. However, this is not recommended; your builds are not repeatable; you may have tested with a slightly different version than what the build server used. (Using a dynamic version as the major version number is more problematic than using it in the minor version position.)

So, I prefer `latest.release` rather than `+`.

However, if extracting the version to a variable as in the example above, you can avoid warnings even using `+`.

```groovy
def mockito_version = '+'
testCompile "org.mockito:mockito-core:$mockito_version"
androidTestCompile "org.mockito:mockito-android:$mockito_version"
```

**Comment by IgorGanapolsky** [comment]
@tmurakami I've been doing Android dev for six years.  And this is first time I've learned of **latest.release**.  Super helpful.  Thanks

**Comment by schwiz** [comment]
Using 
androidTestCompile 'org.mockito:mockito-android:2.7.14'

and I am getting the same exception when I try to mock a final class in device tests. 

java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker
Caused by: org.mockito.exceptions.base.MockitoInitializationException:
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Is there no work around? Can you only mock on unit tests not device tests?

**Comment by tmurakami** [comment]
@schwiz You cannot use the inline mock maker on Android devices.

This is described in the  [Javadoc](https://javadoc.io/page/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.1).
> Be aware that you cannot use the inline mock maker on Android due to limitations in the Android VM.

If you want to mock final classes on Android devices, try using my [DexOpener](https://github.com/tmurakami/dexopener) library.
Although the performance of test execution may be poor. . .

**Comment by schwiz** [comment]
Thanks for the tip!

**Comment by liangxianshen** [comment]
All the solutions above have been tried, or not
