### ISSUE TITLE
Recruite more core developers

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#950]
Currently there are a lot of PRs and that don't get comments or merge approvals from the core developers. Since contributing mockito it a hobby of all of us it is clear that you the core dev cant do all the work alone. Maybe you should recruite more core developers or grant individuals more priviliges like closing and labeling bugs, approve or merge PRs.

Why not define a requirements lists, for a first start?

**Comment by TimvdLippe** [comment]
The current slowdown in development is primarily because both @bric3 and @raphw are heavily involved in organizing their respective conference. Once these conferences are finished I suppose there is a bigger influx in development again. In the mean time @szczepiq is working on several features and it is primarily me looking at community PRs. I am regularly skimming the list, but as I see it right now there are a large number of PRs that are simply not ready. In most cases we indicated what is required for them to get merged.

This weekend I will go over the list again and state what is required for it to be merged if it wasn't stated yet.

**Comment by TimvdLippe** [comment]
Today I have cleaned up numerous PRs for various reasons: 1. They became stale due to external contributors not responding 2. They became stale because there was no action possible 3. Some small PRs which were approved by others.

As I discussed with the other core developers, I do not think we should merge PRs because they are open for too long. There was a large influx of contributions of the core team around the Mockito 2 release and right now we are a bit less active due to other real life activities that require attention.

Lastly I think we can be very grateful for the wonderful contributions of external contributions. As core developer we are now more reviewing and not so much developing. That said, I think this project is in a healthy state right now with a manageable amount of open PRs and issues.

Concluding I do not think we need to expand the core team. Especially as this will make communication by the team harder (which sometimes already is tough). If we realize that we are lacking the manpower to review PRs in a reasonable amount of time, we can of course look for expanding the team. That said we greatly value your time spend reviewing and giving your opinion!

I hope this gives you enough information, I will be closing this ticket for now. Please continue giving your feedback it is greatly appreciated and I hope I addressed your concerns thoroughly.
