### ISSUE TITLE
anyString returning an empty string

### ISSUE THREAD

**Issue by aarangara** [mockito/mockito#951]
Does it make sense to refactor `anyString` method of `Matchers` class to return non-empty string instead of empty?

When checking on string, I (and I have seen others as well) normally use `StringUtils#isEmpty` method so that it covers both `null` and not-empty check for me. So when I test the part of code which uses this method, my test fails as `anyString` returns an empty string.

I would normally expect `anyString` to return an actual non-empty string. 

We can create a new method as `anyEmptyString` (or any name that suits) which returns an empty string and change method `anyString` to return an actual string like `return UUID.randomUUID().toString();` (just an example).

**Comment by ChristianSchwarz** [comment]
In fact it doesn't matter what `anyString()` returns, what matters is the condition that is checked by the matcher. The return value of any matcher should not find its way to your code under tests, since argument matchers are only passed to mock-object in a when/verify clause. I wonder how you use `anyString()` can you add a code snippet?

**Comment by ChristianSchwarz** [comment]
@aarangara can this ticket be closed?

**Comment by aarangara** [comment]
Hi Christian, yes closing it and I can't remember the exact problem that I came across for which I raised this bug.

**Comment by isplendid** [comment]
ava.lang.RuntimeException:    is empty for:
