### ISSUE TITLE
Release commits do not trigger code coverage report

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#984]
Found out at https://github.com/mockito/mockito/pull/980#issuecomment-285124740
This was initially fixed in #493, but I think the adoption of the new mockito-release-tools repository introduced this regression. All pull requests now have a failing status as CodeCov is unable to provide any feedback.

Commits should instead of `[ci skip]` use `[ci skip-release]`. Therefore Travis will kick off, but the release mechanism is not triggered.

**Comment by szczepiq** [comment]
Sorry for slow turnaround. It will get fixed soon!

**Comment by szczepiq** [comment]
My understanding is that code cov comparisons need every commit to produce report. Otherwise codecov "cannot find base report".

Running build for every commit defeats the purpose of "ci skip" :) Can we work with codecov tooling to accommodate this? Even if we make automated commits trigger builds, we still want to use "ci skip" at times.

Do you advocate to use "ci skip release" in place of "ci skip" for mockito project in general?

**Comment by TimvdLippe** [comment]
Asked upstream: https://github.com/codecov/support/issues/355#issuecomment-292707657

**Comment by szczepiq** [comment]
Thank you for asking! I'll unassign myself from the ticket for the time being.

**Comment by szczepiq** [comment]
Created ticket for it: https://github.com/mockito/mockito-release-tools/issues/92

**Comment by TimvdLippe** [comment]
This was fixed some time ago, probably in #1052.
